export const Property = [
  { id: 1, name: "Adiabatic Index", link: "/adiabatic_index" },
  { id: 2, name: "Allotropes", link: "/allotrope" },
  { id: 3, name: "Atomic Radius", link: "/atomic_rad" },
  { id: 4, name: "Atomic Weight", link: "/atomic_weight" },
  { id: 5, name: "Boiling Point", link: "/boiling_point" },
  { id: 6, name: "Brinell Hardness ", link: "/brinell_hardness" },
  { id: 7, name: "Bulk Modulus", link: "/bulk_modulus" },
  { id: 8, name: "CAS Number", link: "/cas_number" },
  { id: 9, name: "CID Number", link: "/cid_number" },
  { id: 10, name: "Color", link: "/color" },
  { id: 11, name: "Covalent Radius", link: "/covalent_rad" },
  { id: 12, name: "Crystall Structure", link: "/cryst_struc" },
  { id: 13, name: "Curie Point", link: "/curie_point" },
  { id: 14, name: "Decay Mode", link: "/decay_mode" },
  { id: 15, name: "Density", link: "/density" },
  { id: 16, name: "Discoverer", link: "/discoverer" },
  { id: 17, name: "Discovery", link: "/discovery" },
  { id: 18, name: "Dot Number", link: "/dot_number" },
  { id: 19, name: "Abundance Earth Crust", link: "/earth_crust" },
  { id: 20, name: "Electrical Conductivity", link: "/electrical_conductivity" },
  { id: 21, name: "Electrical Type", link: "/electrical_type" },
  { id: 22, name: "Electron Affinity", link: "/electron_affinity" },
  { id: 23, name: "Electron Configuration", link: "/electron_config" },
  { id: 24, name: "Electronegativity", link: "/electronegativity" },
  { id: 25, name: "Fusion Heat", link: "/fusion_heat" },
  { id: 26, name: "Gas Atom Multiplicities", link: "/gas_multi" },
  { id: 27, name: "Half Life", link: "/half_life" },
  { id: 28, name: "Hazard Class", link: "/hazard_class" },
  { id: 29, name: "Abundance In Human", link: "/human" },
  { id: 30, name: "Ionization Energy", link: "/ionization_energy" },
  { id: 31, name: "Isotopes", link: "/isotopes" },
  { id: 32, name: "Latin Name", link: "/latin_name" },
  { id: 33, name: "Lattice Angle", link: "/lattice_angle" },
  { id: 34, name: "Lattice Constant", link: "/lattice_constant" },
  { id: 35, name: "Lifetime", link: "/lifetime" },
  { id: 36, name: "Liquid Density", link: "/liquid_density" },
  { id: 37, name: "Magnetic Type", link: "/magnetic_type" },
  {
    id: 38,
    name: "Mass Magnetic Suspectibility",
    link: "/mass_magnetic_suspectibility",
  },
  { id: 39, name: "Melting Point", link: "/melting_point" },
  { id: 40, name: "Abundance Meteorites", link: "/meteorites" },
  { id: 41, name: "Mohs Scale", link: "/mohs_scale" },
  {
    id: 42,
    name: "Molar Magnetic Suspectibility",
    link: "/molar_magnetic_suspectibility",
  },
  { id: 43, name: "Molar Volume", link: "/molar_volume" },
  { id: 44, name: "Neel Point", link: "/neel_point" },
  { id: 45, name: "Neutron Cross Section", link: "/neutron_cross_section" },
  { id: 46, name: "Neutron Mass Absorption", link: "/neutron_mass_absorption" },
  { id: 47, name: "Abundance In Ocean", link: "/ocean" },
  { id: 48, name: "Oxidation State", link: "/oxidation_state" },
  { id: 49, name: "Phase", link: "/phase" },
  { id: 50, name: "Poisson Ratio", link: "/poisson_ratio" },
  { id: 51, name: "Quantum Number", link: "/quantum_number" },
  { id: 52, name: "Radioactive", link: "/radioactive" },
  { id: 53, name: "Refractive Index", link: "/refractive_index" },
  { id: 54, name: "Resistivity", link: "/resistivity" },
  { id: 55, name: "RTECS Number", link: "/rtecs_number" },
  { id: 56, name: "Shear Modulus", link: "/shear_modulus" },
  { id: 57, name: "Electron Shell Configuration", link: "/shell_config" },
  { id: 58, name: "Sound Speed", link: "/sound_speed" },
  { id: 59, name: "Space Group Name", link: "/space_group_name" },
  { id: 60, name: "Space Group Number", link: "/space_group_number" },
  { id: 61, name: "Specific Heat", link: "/specific_heat" },
  { id: 62, name: "Stable Isotopee", link: "/stable_isotope" },
  { id: 63, name: "Abundance In Sun", link: "/sun" },
  { id: 64, name: "Superconducting Point", link: "/superconducting_point" },
  { id: 65, name: "Thermal Conductivity", link: "/thermal_conductivity" },
  { id: 66, name: "Thermal Expansion", link: "/thermal_expansion" },
  { id: 67, name: "Abundance Universe", link: "/universe" },
  { id: 68, name: "Valence", link: "/valence" },
  { id: 69, name: "Van Der Walls Radius", link: "/van_der_wall_rad" },
  { id: 70, name: "Vaporization Heat", link: "/vaporization_heat" },
  { id: 71, name: "Vickers Hardness", link: "/vickers_hardness" },
  {
    id: 72,
    name: "Volume Magnetic Suspectibility",
    link: "/volume_magnetic_suspectibility",
  },
  { id: 73, name: "Young Modulus", link: "/young_modulus" },
];
