import ElementDetailsProps from "@/types/ElementTypes";

export const RowTwoElem: ElementDetailsProps[] = [
  {
    id: 3,
    neighbour: ["Helium", "Beryllium"],
    description:
      "Lithium is the lightest metal and the least dense solid element. It is the first alkali metal in the periodic table. It is highly reactive and flammable, and must be stored in mineral oil. When cut, it exhibits a metallic luster, but moist air corrodes it quickly to a dull silvery gray, then black tarnish. It never occurs freely in nature, but only in (usually ionic) compounds, such as pegmatitic minerals which were once the main source of lithium. Due to its solubility as an ion, it is present in ocean water and is commonly obtained from brines. Lithium metal is isolated electrolytically from a mixture of lithium chloride and potassium chloride.",
    general_properties: {
      name: "Lithium",
      atomic_number: 3,
      group: 1,
      period: 2,
      block: "s",
      cas_number: "7439-93-2",
      symbol: "Li",
    },
    particles: {
      electrons: 3,
      protons: 3,
      neutrons: 4,
    },
    overview: {
      latin_name: "Lithium",
      discovery: 1817,
      discoverer: "Augustus Matthiessen, Johan August Arfwedson, Robert Bunsen",
    },
    atomic_properties: {
      atomic_weight: 6.94,
      oxidation_states: [1],
      electron_shell_configuration: "K2 L1",
      electron_configuration: "<p>1s<sup>2</sup> 2s<sup>1</sup></p>",
      atomic_radius: 167,
      covalent_radius: 128,
      van_der_walls_radius: 182,
      crystall_structure: "Cubic (Face Centered)",
    },
    thermodynamic_properties: {
      boiling_point: "1342℃",
      melting_point: "180.54℃",
      phase: "Solid",
      fusion_heat: 3.0,
      specific_heat: 3570,
      vaporization_heat: 147,
      thermal_expansion: "4.6*10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silvery-white",
      molar_volume: "<p>1.46*10<sup>-2</sup><p>",
      liquid_density: 512,
      density: 535,
      young_modulus: 4.9,
      bulk_modulus: 11,
      mohs_hardness: 0.6,
      shear_modulus: 4.2,
      thermal_conductivity: 85,
      sound_speed: 6000,
    },
    reactivity: {
      electronegativity: 0.98,
      valence: 1,
      electron_affinity: 59.6,
      ionization_energy: 520,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 71,
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagentic",
      resisitivity: "9.4*10<sup>-8</sup>",
      electrical_conductivity: "1.1*10<sup>7</sup>",
      volume_magnetic_suspectibility: "<p>1.37*10<sup>-5</sup></p>",
      mass_magnetic_suspectibility: "<p>2.56*10<sup>-8</sup></p>",
      molar_magnetic_suspectibility: "<p>1.78*10<sup>-10</sup></p>",
    },
    prevalence: {
      universe: "6*10<sup>-7</sup>%",
      sun: "6*10<sup>-9</sup>%",
      meteorites: "0.00017%",
      earth_crust: "0.0017%",
      ocean: "0.000018%",
      human: "3*10<sup>-6</sup>%",
    },
  },
];
