import ElementDetailsProps from "@/types/ElementTypes";

export const ActinideElem: ElementDetailsProps[] = [
  {
    id: 89,
    neighbour: ["Radium", "Thorium"],
    description:
      "Actinium starts the series of actinoids(elements 90-103), which named after this element. It naturally occurs from Uranium decay, the half life of its most stable isotope 227 is less than 22 years. It has very few applications, because it is difficult to handle and very dangerous. Chemically it is similar to lanthanum. Most Actinium decays to Thorium. about 1.4% to Fracium.",
    general_properties: {
      name: "Actinium",
      atomic_number: 89,
      period: 7,
      block: "F",
      cas_number: "7440-34-8",
      cid_number: "167378",
      symbol: "Ac",
    },
    particles: {
      electrons: 89,
      protons: 89,
      neutrons: 138,
    },
    overview: {
      latin_name: "Actinium",
      discovery: 1899,
      discoverer: [["André-Louis Debierne", "André-Louis_Debierne"]],
    },
    atomic_properties: {
      atomic_weight: 227,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N32 O18 P9 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 6d<sup>1</sup>",
      covalent_radius: 215,
    },
    thermodynamic_properties: {
      boiling_point: "3200℃",
      melting_point: "1050℃",
      phase: "Solid",
      fusion_heat: 14,
      specific_heat: 120,
      vaporization_heat: 400,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.25•10<sup>-5</sup>",
      density: 10070,
      thermal_conductivity: 12,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.1,
      ionization_energy: 499,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "6.8706•10<sup>8</sup>",
      lifetime: "9.9121•10<sup>8</sup>",
      neutron_cross_section: 880,
      neutron_mass_absorption: 0.078,
      quantum_numbers: "<sup>2</sup>D<sub>3/2</sub>",
      decay_mode: "Beta",
      isotopes: [
        206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,
        220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
        234, 235, 236,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Actinium",
      youtube: "https://youtu.be/rKm0ShaJNFM",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [567, 567, 567],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
  },
  {
    id: 90,
    neighbour: ["Actinium", "Protactinium"],
    description:
      "Thorium by far is the most stable and frequent actinoid, the half-life of <sup>232</sup>Th is 14 billion years. The soft, in pure form silvery metal is chemically reactive and light toxic. However, its weak radioactivity can become dangerous, if it is inhaled. Therefore it is not longer much used for mantles in gas lights, which it was for a long time. It is used for some special alloys and in good camera lenses (as ThO<sub>2</sub>). Thorium Decays to Radium.",
    general_properties: {
      name: "Thorium",
      atomic_number: 90,
      period: 7,
      block: "F",
      cas_number: "7440-29-1",
      cid_number: "23960",
      symbol: "Th",
    },
    particles: {
      electrons: 90,
      protons: 90,
      neutrons: 142,
    },
    overview: {
      latin_name: "Thorium",
      discovery: 1829,
      discoverer: [["Jöns Jacob Berzelius", "Jöns_Jacob_Berzelius"]],
    },
    atomic_properties: {
      atomic_weight: 231.0377,
      oxidation_states: [4],
      electron_shell_configuration: "K2 L8 M18 N32 O18 P10 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 6d<sup>2</sup>",
      covalent_radius: 206,
    },
    thermodynamic_properties: {
      boiling_point: "4820℃",
      melting_point: "1750℃",
      phase: "Solid",
      fusion_heat: 16,
      specific_heat: 118,
      vaporization_heat: 530,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.9792•10<sup>-5</sup>",
      density: 11724,
      thermal_conductivity: 54,
      brinell_hardness: 400,
      bulk_modulus: 54,
      mohs_hardness: 3,
      poisson_ratio: 0.27,
      shear_modulus: 31,
      sound_speed: 2490,
      vickers_hardness: 350,
      young_modulus: 79,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 587,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "4.434•10<sup>17</sup>",
      lifetime: "6.397•10<sup>17</sup>",
      neutron_cross_section: 7.4,
      neutron_mass_absorption: 0.001,
      quantum_numbers: "<sup>3</sup>F<sub>2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222,
        223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238,
      ],
      stable: [232],
    },
    prevalence: {
      universe: "4•10<sup>-8</sup>%",
      sun: "3•10<sup>-8</sup>%",
      ocean: "4•10<sup>-12</sup>%",
      earth_crust: "0.0006%",
      meteorites: "3.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "6.7•10<sup>6</sup>",
      resistivity: "1.5•10<sup>-7</sup>",
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "8.4•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "7.2•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "1.7•10<sup>-9</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Thorium",
      youtube: "https://youtu.be/zjDw1VWJ_RU",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [508.42, 508.42, 508.42],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 7,
      dot_number: 1975,
      rtecs_number: "XO6400000",
    },
  },
  {
    id: 91,
    neighbour: ["Thorium", "Uranium"],
    description:
      "Protactinium primarily is generated from decay of rare isotope uranium 235 (via very unstable thorium 231). Therefore it only exists in small amounts, most of it is found in nuclear waste. the half life of the most stable isotope 231 is 32760 years. Outside of science, no application for protactinium exist. Nearly all protactinium further decays to Actinium.",
    general_properties: {
      name: "Protactinium",
      atomic_number: 91,
      period: 7,
      block: "F",
      cas_number: "7440-13-3",
      cid_number: "23945",
      symbol: "Pa",
    },
    particles: {
      electrons: 91,
      protons: 91,
      neutrons: 140,
    },
    overview: {
      latin_name: "Protactinium",
      discovery: 1913,
      discoverer: [
        ["John Arnold Cranston", "John_Arnold_Cranston"],
        ["Oswald Helmuth Göhring", "Oswald_Helmuth_Göhring"],
        ["Lise Meitner", "Lise_Meitner"],
        ["Alexander Fleck", "Alexander_Fleck"],
        ["Otto Hahn", "Otto_Hahn"],
        ["Kasimir Fajans", "Kasimir_Fajans"],
        ["Frederick Soddy", "Frederick_Soddy"],
      ],
    },
    atomic_properties: {
      atomic_weight: 231.03588,
      oxidation_states: [4, 5],
      electron_shell_configuration: "K2 L8 M18 N32 O20 P9 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>2</sup> 6d<sup>1</sup>",
      covalent_radius: 200,
    },
    thermodynamic_properties: {
      boiling_point: "4000℃",
      melting_point: "1572℃",
      phase: "Solid",
      fusion_heat: 15,
      specific_heat: 99.1,
      vaporization_heat: 470,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.5032•10<sup>-5</sup>",
      density: 15370,
      thermal_conductivity: 47,
    },
    reactivity: {
      valence: 5,
      electronegativity: 1.5,
      ionization_energy: 568,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "1.034•10<sup>12</sup>",
      lifetime: "1.491•10<sup>12</sup>",
      neutron_cross_section: 200,
      quantum_numbers: "<sup>4</sup>K<sub>11/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
        226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
        240,
      ],
    },
    prevalence: {
      universe: "4•10<sup>-8</sup>%",
      sun: "3•10<sup>-8</sup>%",
      ocean: "4•10<sup>-12</sup>%",
      earth_crust: "0.0006%",
      meteorites: "3.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "5.6•10<sup>6</sup>",
      resistivity: "1.8•10<sup>-7</sup>",
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "4.995•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "3.25•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "7.509•10<sup>-9</sup>",
      superconducting_point: 1.4,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Protactinium",
      youtube: "https://youtu.be/bsIMMa7iEKU",
    },
    atom_structure: {
      crystal_structure: "Centered Tetragonal",
      lattice_angle: [90, 90, 90],
      lattice_constant: [392.5, 392.5, 323.8],
      space_group_name: "I4/mmm",
      space_group_number: 139,
    },
  },
  {
    id: 92,
    neighbour: ["Protactinium", "Neptunium"],
    description:
      "Uranium is a chemically very reactive, highly toxic, grey heavy metal. Like all actinoids it is radioactive, after thorium it is the second most stable of those. The most abundant natural isotope is <sup>238</sup>U with a half-life of 4.5 billion years. The basis for neuclear power plants is the fissile isotope <sup>235</sup>U. The fission products often are highly radioactive isotopes of lower elements, like cesium 137 and strontium 90. Uranium 235 is used for atomic bombs, too, like the one in Hiroshima. It has a natural abundant of Only 0.7% and has to be enriched in an extensive process.",
    general_properties: {
      name: "Uranium",
      atomic_number: 92,
      period: 7,
      block: "F",
      cas_number: "7440-61-1",
      cid_number: "23989",
      symbol: "U",
    },
    particles: {
      electrons: 92,
      protons: 92,
      neutrons: 146,
    },
    overview: {
      latin_name: "Uranium",
      discovery: 1789,
      discoverer: [["Martin Heinrich Klaproth", "Martin_Heinrich_Klaproth"]],
    },
    atomic_properties: {
      atomic_weight: 238.02891,
      oxidation_states: [3, 4, 5, 6],
      electron_shell_configuration: "K2 L8 M18 N32 O21 P9 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>3</sup> 6d<sup>1</sup>",
      covalent_radius: 196,
      van_der_walls_radius: 186,
    },
    thermodynamic_properties: {
      boiling_point: "3927℃",
      melting_point: "1135℃",
      phase: "Solid",
      fusion_heat: 14,
      specific_heat: 116,
      vaporization_heat: 420,
      thermal_expansion: "1.39•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.2495•10<sup>-5</sup>",
      density: 19050,
      liquid_density: 17300,
      thermal_conductivity: 27,
      brinell_hardness: 2400,
      bulk_modulus: 100,
      mohs_hardness: 6,
      poisson_ratio: 0.23,
      shear_modulus: 111,
      sound_speed: 3155,
      vickers_hardness: 1960,
      young_modulus: 208,
    },
    reactivity: {
      valence: 6,
      electronegativity: 1.38,
      ionization_energy: 597.6,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "1.41•10<sup>17</sup>",
      lifetime: "2.034•10<sup>17</sup>",
      neutron_cross_section: 7.57,
      neutron_mass_absorption: 0.0005,
      quantum_numbers: "<sup>5</sup>L<sub>6</sub>",
      decay_mode: "Alpha",
      isotopes: [
        217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
        231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
      ],
    },
    prevalence: {
      universe: "2•10<sup>-8</sup>%",
      sun: "10<sup>-7</sup>%",
      human: "10<sup>-7</sup>%",
      ocean: "3.3•10<sup>-7</sup>%",
      earth_crust: "0.00018%",
      meteorites: "9.8•10<sup>-7</sup>%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "3.6•10<sup>6</sup>",
      resistivity: "2.8•10<sup>-7</sup>",
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "4.11•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "2.16•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "5.14•10<sup>-9</sup>",
      superconducting_point: 0.68,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Uranium",
      youtube: "https://youtu.be/Kkd2bYAVtOU",
    },
    atom_structure: {
      crystal_structure: "Base Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [285.37, 586.95, 495.48],
      space_group_name: "Cmcm",
      space_group_number: 63,
    },
    health_safety: {
      Hazard_class: 7,
      dot_number: 2979,
      rtecs_number: "YR3490000",
    },
  },
  {
    id: 93,
    neighbour: ["Uranium", "Plutonium"],
    description:
      "Neptunium, a radioactive, silvery heavy mwtal, is quite stable for an element with a high and odd atomic number, <sup>237</sup>Np has a half-life of 2 million years. On earth, it naturally occurs in tiny traces in Uranium ore, it is found in much bigger amounts as waste in neuclear reactors. It is scarcely used, although it is fissionable. Most of it decays to Protactinium.",
    general_properties: {
      name: "Neptunium",
      atomic_number: 93,
      period: 7,
      block: "F",
      cas_number: "7439-99-8",
      cid_number: "23933",
      symbol: "Np",
    },
    particles: {
      electrons: 93,
      protons: 93,
      neutrons: 144,
    },
    overview: {
      latin_name: "Neptunium",
      discovery: 1940,
      discoverer: [
        ["Edwin McMillan", "Edwin_McMillan"],
        ["Philip Hauge Abelson", "Philip_Abelson"],
      ],
    },
    atomic_properties: {
      atomic_weight: 237,
      oxidation_states: [3, 4, 5, 6],
      electron_shell_configuration: "K2 L8 M18 N32 O22 P9 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>4</sup> 6d<sup>1</sup>",
      covalent_radius: 190,
    },
    thermodynamic_properties: {
      boiling_point: "4000℃",
      melting_point: "644℃",
      phase: "Solid",
      fusion_heat: 10,
      vaporization_heat: 335,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.6•10<sup>-5</sup>",
      density: 20450,
      thermal_conductivity: 6,
    },
    reactivity: {
      valence: 6,
      electronegativity: 1.36,
      ionization_energy: 604.5,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "6.766•10<sup>13</sup>",
      lifetime: "9.761•10<sup>13</sup>",
      neutron_cross_section: 180,
      quantum_numbers: "<sup>6</sup>L<sub>11/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
        239, 240, 241, 242,
      ],
    },
    electromagnetic_properties: {
      electrical_conductivity: "8.3•10<sup>5</sup>",
      resistivity: "1.2•10<sup>-6</sup>",
      electrical_type: "Conductor",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Neptunium",
      youtube: "https://youtu.be/1D75B0_URbE",
    },
    atom_structure: {
      crystal_structure: "Simple Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [666.3, 472.3, 488.7],
      space_group_name: "Pnma",
      space_group_number: 62,
    },
  },
  {
    id: 94,
    neighbour: ["Neptunium", "Americium"],
    description:
      "Plutonium, a silvery, very heavy and hard metal, is perhaps the most dangerous of all elements. It was in the bomb of Nagasaki and, together with Uranium, involved in the Chernobyl and Fukushima disasters. In multiple nuclear tests it devasteted huge areas. <sup>244</sup>Pu the most stable isotope, has a half-life of 80 million years. In nature, Plutonium only occurs in extremely small amounts, all that is in use is artificially made from Uranium.",
    general_properties: {
      name: "Plutonium",
      atomic_number: 94,
      period: 7,
      block: "F",
      cas_number: "7440-07-5",
      cid_number: "23940",
      symbol: "Pu",
      allotropes: [
        [
          "Alpha Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
        [
          "Beta Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
        [
          "Gamma Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
        [
          "Delta Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
        [
          "Delta Prime Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
        [
          "Epsilon Plutonium",
          "https://en.wikipedia.org/wiki/Allotropes_of_plutonium",
        ],
      ],
    },
    particles: {
      electrons: 94,
      protons: 94,
      neutrons: 150,
    },
    overview: {
      latin_name: "Plutonium",
      discovery: 1789,
      discoverer: [["Martin Heinrich Klaproth", "Martin_Heinrich_Klaproth"]],
    },
    atomic_properties: {
      atomic_weight: 244,
      oxidation_states: [3, 4, 5, 6],
      electron_shell_configuration: "K2 L8 M18 N32 O24 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>6</sup>",
      covalent_radius: 187,
    },
    thermodynamic_properties: {
      boiling_point: "3230℃",
      melting_point: "640℃",
      phase: "Solid",
      vaporization_heat: 325,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.23•10<sup>-5</sup>",
      density: 19816,
      liquid_density: 16630,
      thermal_conductivity: 6,
      poisson_ratio: 0.21,
      shear_modulus: 43,
      sound_speed: 2260,
      young_modulus: 96,
    },
    reactivity: {
      valence: 6,
      electronegativity: 1.28,
      ionization_energy: 584.7,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "2.5•10<sup>15</sup>",
      lifetime: "2.6•10<sup>15</sup>",
      neutron_cross_section: 1.7,
      quantum_numbers: "<sup>7</sup>F<sub>0</sub>",
      decay_mode: "Alpha",
      isotopes: [
        228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
        242, 243, 244, 245, 246, 247,
      ],
    },
    electromagnetic_properties: {
      electrical_conductivity: "6.7•10<sup>5</sup>",
      resistivity: "1.5•10<sup>-6</sup>",
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "6.282•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "3.17•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "7.735•10<sup>-9</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Plutonium",
      youtube: "https://youtu.be/87TpxxFdzQU",
    },
    atom_structure: {
      crystal_structure: "Simple Monoclinic",
      lattice_angle: [90, 1.776571, 90],
      lattice_constant: [618.3, 482.2, 1096.3],
      space_group_name: "P12<sub>1</sub>/m1",
      space_group_number: 11,
    },
  },
  {
    id: 95,
    neighbour: ["Plutonium", "Curium"],
    description:
      "Americium is the first synthetic element, from here onwards all elements have to be produced in laboratories. These are very radioactive. The most stable isotope of Americium <sup>243</sup>Am, has a half-life of just under 7400 years. Due to its strong Alpha radiation, Americium is very dangerous. In some countries Americium 241 (432 years half-life) is used in tiny amounts in smoke detectors for ionizing air. Americium emerges in small amounts in nuclear reactors from Plutonium and mostly decays to Neptunium.",
    general_properties: {
      name: "Americium",
      atomic_number: 94,
      period: 7,
      block: "F",
      cas_number: "7440-35-9",
      cid_number: "23966",
      symbol: "Am",
    },
    particles: {
      electrons: 95,
      protons: 95,
      neutrons: 148,
    },
    overview: {
      latin_name: "Americium",
      discovery: 1944,
      discoverer: [
        ["Ralph Arthur James", "Ralph_A._James"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Glenn Seaborg", "Glenn_Seaborg"],
        ["Leon O Morgan", "Leon_O._Morgan"],
      ],
    },
    atomic_properties: {
      atomic_weight: 243,
      oxidation_states: [3, 4, 5, 6],
      electron_shell_configuration: "K2 L8 M18 N32 O25 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>7</sup>",
      covalent_radius: 180,
    },
    thermodynamic_properties: {
      boiling_point: "2011℃",
      melting_point: "1176℃",
      phase: "Solid",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.78•10<sup>-5</sup>",
      density: 13670,
      thermal_conductivity: 10,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 578,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "2.33•10<sup>11</sup>",
      lifetime: "3.66•10<sup>11</sup>",
      neutron_cross_section: 74,
      quantum_numbers: "<sup>8</sup>S<sub>7/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
        245, 246, 247, 248, 249,
      ],
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "7.04•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "5.15•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "1.251•10<sup>-8</sup>",
      superconducting_point: 0.6,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Americium",
      youtube: "https://youtu.be/CC-L-CITg3k",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [346.81, 346.81, 1124.1],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 96,
    neighbour: ["Americium", "Berkelium"],
    description:
      "The synthetic element Curium is usually made from Plutonium and mostly decays to this again. The most stable isotope, <sup>247</sup>Cm, has a quite long half-life of 15.6 million years. However this is scarcely produced. Much more frequent are the significantly more unstable isotopes 242 and 244, which emit very intense radiation. Therefore, the enormously dangerous Curium is used only rarely and in safe environments, like in space missions.",
    general_properties: {
      name: "Curium",
      atomic_number: 96,
      period: 7,
      block: "F",
      cas_number: "7440-51-9",
      cid_number: "23979",
      symbol: "Cm",
    },
    particles: {
      electrons: 96,
      protons: 96,
      neutrons: 151,
    },
    overview: {
      latin_name: "Curium",
      discovery: 1944,
      discoverer: [
        ["Ralph Arthur James", "Ralph_A._James"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Glenn Seaborg", "Glenn_Seaborg"],
      ],
    },
    atomic_properties: {
      atomic_weight: 247,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N32 O25 P9 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>7</sup> 6d<sup>1</sup>",
      covalent_radius: 180,
    },
    thermodynamic_properties: {
      boiling_point: "3110℃",
      melting_point: "1345℃",
      phase: "Solid",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.83•10<sup>-5</sup>",
      density: 13510,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 581,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "4.92•10<sup>14</sup>",
      lifetime: "7.1•10<sup>14</sup>",
      neutron_cross_section: 60,
      quantum_numbers: "<sup>9</sup>D<sub>2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
        247, 248, 249, 250, 251, 252,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Curium",
      youtube: "https://youtu.be/sZobqPFNcwg",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [349.6, 349.6, 1133.1],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 97,
    neighbour: ["Curium", "Californium"],
    description:
      "Berkelium is made from americium or curium, mostly unintentional, because outside of basic research it hasn't any application. The most stable isotope, <sup>247</sup>Bk, has a half-life of 1380 years after all, but this is hardly produced. The most commonly accrued <sup>249</sup>Bk has a half-life of only 330 days. Of this, each year about 1 gram emerges worldwide as by-product in nuclear reactors, most of it decays to Californium. Berkelium is a strong Beta emitter.",
    general_properties: {
      name: "Berkelium",
      atomic_number: 97,
      period: 7,
      block: "F",
      cas_number: "7440-40-6",
      cid_number: "23971",
      symbol: "Bk",
    },
    particles: {
      electrons: 97,
      protons: 97,
      neutrons: 150,
    },
    overview: {
      latin_name: "Berkelium",
      discovery: 1949,
      discoverer: [
        ["Stanley Gerald Thompson", "Stanley_Gerald_Thompson"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Glenn Seaborg", "Glenn_Seaborg"],
      ],
    },
    atomic_properties: {
      atomic_weight: 247,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N32 O27 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>9</sup>",
    },
    thermodynamic_properties: {
      melting_point: "1050℃",
      phase: "Solid",
    },
    material_properties: {
      molar_volume: "1.67•10<sup>-5</sup>",
      density: 14780,
      thermal_conductivity: 10,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 601,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "4.35•10<sup>10</sup>",
      lifetime: "6.28•10<sup>10</sup>",
      neutron_cross_section: 710,
      quantum_numbers: "<sup>6</sup>H<sub>15/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248,
        249, 250, 251, 252, 253, 254,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Berkelium",
      youtube: "https://youtu.be/IgPkUbtnC4o",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [341.6, 341.6, 1106.9],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 98,
    neighbour: ["Berkelium", "Einsteinium"],
    description:
      "Californium emerges in tiny amounts rather randomly from plutonium via the elements because of this two. With Californium, It is bothered to laboriously extract it, because for <sup>252</sup>Cf, which has a half-life of 2.6 years, there are reasonable applications. About 3% of this isotope spontaneously fissions into large chunks and hot neutrons.",
    general_properties: {
      name: "Californium",
      atomic_number: 98,
      period: 7,
      block: "F",
      cas_number: "7440-71-3",
      cid_number: "23997",
      symbol: "Cf",
    },
    particles: {
      electrons: 98,
      protons: 98,
      neutrons: 153,
    },
    overview: {
      latin_name: "Californium",
      discovery: 1950,
      discoverer: [
        ["Stanley Gerald Thompson", "Stanley_Gerald_Thompson"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Kenneth_Street_Jr.", "Kenneth_Street_Jr."],
        ["Glenn Seaborg", "Glenn_Seaborg"],
      ],
    },
    atomic_properties: {
      atomic_weight: 251,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N32 O28 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>10</sup>",
    },
    thermodynamic_properties: {
      melting_point: "900℃",
      phase: "Solid",
    },
    material_properties: {
      molar_volume: "1.66•10<sup>-5</sup>",
      density: 15100,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 608,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "2.84•10<sup>10</sup>",
      lifetime: "4.1•10<sup>10</sup>",
      neutron_cross_section: 2900,
      quantum_numbers: "<sup>5</sup>I<sub>8</sub>",
      decay_mode: "Alpha",
      isotopes: [
        237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250,
        251, 252, 253, 254, 255, 256,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Californium",
      youtube: "https://youtu.be/ZhvRmbpkx9U",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [338, 338, 1102 / 5],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 99,
    neighbour: ["Californium", "Fermium"],
    description:
      "Einsteinium and Fermium are produced in small amounts in explosions of hydrogen bombs, from the igniter plutonium and neutrons that are flying around. Einsteinium also can be made in labs, however the highly radioactive metal has no use outside of basic research. The most stable isotope 252 has a half-life of 472 days. Einsteinium of course was named after Albert Einstein, who himself had no connection to the element. Einsteinium decays to Berkelium or Californium.",
    general_properties: {
      name: "Einsteinium",
      atomic_number: 99,
      period: 7,
      block: "F",
      cas_number: "7429-92-7",
      cid_number: "23913",
      symbol: "Es",
    },
    particles: {
      electrons: 99,
      protons: 99,
      neutrons: 153,
    },
    overview: {
      latin_name: "Einsteinium",
      discovery: 1952,
      discoverer: [
        ["Stanley Gerald Thompson", "Stanley_Gerald_Thompson"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Bernard G Harvey", "Bernard_G._Harvey"],
        ["Gregory R Choppin", "Gregory_R._Choppin"],
      ],
    },
    atomic_properties: {
      atomic_weight: 252,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N32 O29 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>11</sup>",
    },
    thermodynamic_properties: {
      melting_point: "860℃",
      phase: "Solid",
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.3,
      ionization_energy: 619,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "4.075•10<sup>7</sup>",
      lifetime: "5.88•10<sup>7</sup>",
      neutron_cross_section: 160,
      quantum_numbers: "<sup>5</sup>I<sub>15/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253,
        254, 255, 256, 257, 258,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Einsteinium",
      youtube: "https://youtu.be/UdJeLlwrVUI",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [565.75, 565.75, 565.75],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
  },
  {
    id: 100,
    neighbour: ["Einsteinium", "Mendelevium"],
    description:
      "Fermium and Einsteinium are produced in small amounts in explosions of hydrogen bombs, from the igniter Plutonium and Neutrons that are flying around. Fermium also can be made in labs, however the highly radioactive metal has no use outside of basic research. The most stable isotope has a half-life of 100 days. Fermium was named after Enrico Fermi, Who had nothing to do with the elements, but who was involved in the construction of first atomic bomb. Fermium decays to Californium.",
    general_properties: {
      name: "Fermium",
      atomic_number: 100,
      period: 7,
      block: "F",
      cas_number: "7429-92-7",
      cid_number: "167391",
      symbol: "Fm",
    },
    particles: {
      electrons: 100,
      protons: 100,
      neutrons: 157,
    },
    overview: {
      latin_name: "Fermium",
      discovery: 1952,
      discoverer: [
        ["Stanley Gerald Thompson", "Stanley_Gerald_Thompson"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Bernard G Harvey", "Bernard_G._Harvey"],
        ["Gregory R Choppin", "Gregory_R._Choppin"],
      ],
    },
    atomic_properties: {
      atomic_weight: 257,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N32 O30 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>12</sup>",
    },
    thermodynamic_properties: {
      melting_point: "1527℃",
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.3,
      ionization_energy: 627,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "8.683•10<sup>6</sup>",
      lifetime: "1.253•10<sup>7</sup>",
      neutron_cross_section: 5800,
      quantum_numbers: "<sup>3</sup>H<sub>6</sub>",
      decay_mode: "Alpha",
      isotopes: [
        242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
        256, 257, 258, 259, 260,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Fermium",
      youtube: "https://youtu.be/SQhI52sqanA",
    },
  },
  {
    id: 101,
    neighbour: ["Fermium", "Nobelium"],
    description:
      "Mendelevium is the first synthetic element, which can&apos;t be produced anymore by neutron capture. To make Mendelevium, Einsteinium is bombered with Helium nuclei. Most of it decays to Einsteinium again. The most stable mendelevium isotope has a half-life of 53 days. The element is named to honor Dmitri Mendeleev, the developer of the periodic table of elements.",
    general_properties: {
      name: "Mendelevium",
      atomic_number: 101,
      period: 7,
      block: "F",
      cas_number: "7440-11-1",
      symbol: "Md",
    },
    particles: {
      electrons: 101,
      protons: 101,
      neutrons: 157,
    },
    overview: {
      latin_name: "Mendelevium",
      discovery: 1955,
      discoverer: [
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Glenn Seaborg", "Glenn_Seaborg"],
      ],
    },
    atomic_properties: {
      atomic_weight: 258,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N32 O31 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>13</sup>",
    },
    thermodynamic_properties: {
      melting_point: "827℃",
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.3,
      ionization_energy: 635,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "4.45•10<sup>6</sup>",
      lifetime: "6.62•10<sup>6</sup>",
      quantum_numbers: "<sup>2</sup>F<sub>7/2</sub>",
      decay_mode: "Alpha",
      isotopes: [
        245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
        259, 260, 261, 262,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Mendelevium",
      youtube: "https://youtu.be/0JlshAo8DuE",
    },
  },
  {
    id: 102,
    neighbour: ["Mendelevium", "Lawrencium"],
    description:
      "Nobelium is produced for example by bombarding Californium with Carbon or Uranium with Neon. The most stable isotope has a half-life of 58 minutes. Most of it decays to Fermium by spontaneous fission. Of its physical properties not much is known, but they are probably similar to those of the other actinoids.",
    general_properties: {
      name: "Nobelium",
      atomic_number: 102,
      period: 7,
      block: "F",
      cas_number: "10028-14-5",
      cid_number: "24822",
      symbol: "No",
    },
    particles: {
      electrons: 102,
      protons: 102,
      neutrons: 157,
    },
    overview: {
      latin_name: "Nobelium",
      discovery: 1958,
      discoverer: [
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["John R Walton", "John_R._Walton"],
        ["TorbjØrn Sikkeland", "TorbjØrn_Sikkeland"],
        ["Glenn Seaborg", "Glenn_Seaborg"],
      ],
    },
    atomic_properties: {
      atomic_weight: 259,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N32 O32 P8 Q2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>14</sup>",
    },
    thermodynamic_properties: {
      melting_point: "827℃",
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.3,
      ionization_energy: 642,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "10<sup>4</sup>",
      lifetime: "2•10<sup>4</sup>",
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      decay_mode: "Alpha",
      isotopes: [
        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
        262, 263, 264,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Nobelium",
      youtube: "https://youtu.be/t_ZpauMxapY",
    },
  },
  {
    id: 103,
    neighbour: ["Nobelium", "Rutherfordium"],
    description:
      "Lawrencium is produced for example by bombarding Californium with Boron or Americium with Oxygen. The most stable isotope has a half-life of 11 hours. This decays to Nobelium, most other isotopes to Mendelevium. Of its physical properties not much is known, but they are probably similar to those of the other Actinoids. Lawrencium could be the hardest and heaviest of them",
    general_properties: {
      name: "Lawrencium",
      atomic_number: 103,
      period: 7,
      block: "F",
      cas_number: "22537-19-5",
      cid_number: "31192",
      symbol: "Lw",
    },
    particles: {
      electrons: 103,
      protons: 103,
      neutrons: 159,
    },
    overview: {
      latin_name: "Lawrencium",
      discovery: 1952,
      discoverer: [
        ["Stanley Gerald Thompson", "Stanley_Gerald_Thompson"],
        ["Albert Ghiorso", "Albert_Ghiorso"],
        ["Gregory R Choppin", "Gregory_R._Choppin"],
        ["Bernard G Harvey", "Bernard_G._Harvey"],
      ],
    },
    atomic_properties: {
      atomic_weight: 262,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N32 O32 P8 Q3",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>10</sup> 6p<sup>6</sup> 7s<sup>2</sup> 5f<sup>14</sup> 7p<sup>1</sup>",
    },
    thermodynamic_properties: {
      melting_point: "1627℃",
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.3,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "3.6•10<sup>4</sup>",
      lifetime: "5.2•10<sup>4</sup>",
      quantum_numbers: "<sup>2</sup>P<sub>1/2</sub>",
      decay_mode: "Beta",
      isotopes: [
        251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
        265, 266,
      ],
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Lawrencium",
      youtube: "https://youtu.be/_zBsnnJOkyA",
    },
  },
];
