import ElementDetailsProps from "@/types/ElementTypes";

export const LanthanideElem: ElementDetailsProps[] = [
  {
    id: 57,
    neighbour: ["Barium", "Cerium"],
    description:
      "Lanthanum is the prototype for the lanthanoids, elements 58-71. Like these, it is silvery in color and quite soft. If counted among them, it is the most reactive of those and the one with the highest atomic diameter. It is used in optical lenses, alloys for special applications and in some batteries. In nature, it always occurs in compounds.",
    general_properties: {
      name: "Lanthanum",
      atomic_number: 57,
      period: 6,
      block: "F",
      cas_number: "7439-91-0",
      cid_number: "23926",
      symbol: "La",
    },
    particles: {
      electrons: 57,
      protons: 57,
      neutrons: 82,
    },
    overview: {
      latin_name: "Lanthanum",
      discovery: 1839,
      discoverer: [["Carl Gustaf Mosander", "Carl_Gustaf_Mosander"]],
    },
    atomic_properties: {
      atomic_weight: 138.90547,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N18 O9 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 5d<sup>1</sup>",
      covalent_radius: 207,
    },
    thermodynamic_properties: {
      boiling_point: "3464℃",
      melting_point: "920℃",
      phase: "Solid",
      fusion_heat: 6.2,
      specific_heat: 195,
      vaporization_heat: 400,
      thermal_expansion: "1.21•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.26•10<sup>-2</sup>",
      density: 6146,
      liquid_density: 5940,
      thermal_conductivity: 13,
      sound_speed: 2475,
      shear_modulus: 14,
      poisson_ratio: 0.28,
      vickers_hardness: 491,
      young_modulus: 37,
      mohs_hardness: 2.5,
      bulk_modulus: 28,
      brinell_hardness: 363,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.1,
      ionization_energy: 538.1,
      electron_affinity: 48,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 8.98,
      neutron_mass_absorption: 0.0023,
      quantum_numbers: "<sup>2</sup>D<sub>3/2</sub>",
      isotopes: [
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
      ],
      stable: [139],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "2•10<sup>-7</sup>%",
      ocean: "3.4•10<sup>-10</sup>%",
      earth_crust: "0.0034%",
      meteorites: "0.00003%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Diamagnetic",
      volume_magnetic_suspectibility: "-1.65•10<sup>-8</sup>",
      mass_magnetic_suspectibility: "-4.4•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-3.69•10<sup>-10</sup>",
      electrical_conductivity: "1.6•10<sup>6</sup>",
      resistivity: "6.1•10<sup>-7</sup>",
      superconducting_point: 4.88,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Lanthanum",
      youtube: "https://youtu.be/0YhbvVhAudE",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [377.2, 377.2, 1214.4],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3178,
    },
  },
  {
    id: 58,
    neighbour: ["Lanthanum", "Praseodymium"],
    description:
      "Cerium is the most frequent of the lanthanoids, most of it occurs mixed with the others of them. Often it is used as mischmetal, which contains a natural lanthanoid mixture and is cheaper than the separated lanthanoids. This typically consists of 50% Cerium, 20% Lanthanum and Neodymium, 5% Praseodymium and the other Lanthanoids in fewer amounts as well as Iron and other elements. Iron and Cerium are the only elements, where by hard and fast friction sparks can be produced.",
    general_properties: {
      name: "Cerium",
      atomic_number: 58,
      period: 6,
      block: "F",
      cas_number: "7440-45-1",
      cid_number: "23974",
      symbol: "Ce",
    },
    particles: {
      electrons: 58,
      protons: 58,
      neutrons: 82,
    },
    overview: {
      latin_name: "Cerium",
      discovery: 1803,
      discoverer: [
        ["Wilhelm Hisinger", "Wilhelm_Hisinger"],
        ["William Francis Hillebrand", "William_Francis_Hillebrand"],
        ["Jöns Jacob Berzelius", "Jöns_Jacob_Berzelius"],
        ["Thomas H. Norton", "Thomas_Herbert_Norton"],
      ],
    },
    atomic_properties: {
      atomic_weight: 140.116,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N19 O9 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>1</sup> 5d<sup>1</sup>",
      covalent_radius: 204,
    },
    thermodynamic_properties: {
      boiling_point: "3360℃",
      melting_point: "798℃",
      phase: "Solid",
      fusion_heat: 5.5,
      specific_heat: 192,
      vaporization_heat: 350,
      thermal_expansion: "6.3•10<sup>-6</sup>",
      neel_point: 12.5,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.095•10<sup>-5</sup>",
      density: 6689,
      liquid_density: 6550,
      thermal_conductivity: 11,
      sound_speed: 2100,
      shear_modulus: 14,
      poisson_ratio: 0.24,
      vickers_hardness: 270,
      young_modulus: 34,
      mohs_hardness: 2.5,
      bulk_modulus: 22,
      brinell_hardness: 412,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.12,
      ionization_energy: 534.4,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.6,
      neutron_mass_absorption: 0.00021,
      quantum_numbers: "<sup>1</sup>G<sub>4</sub>",
      isotopes: [
        119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
        147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
      ],
      stable: [136, 138, 140, 142],
    },
    prevalence: {
      universe: "10<sup>-6</sup>%",
      sun: "4•10<sup>-7</sup>%",
      ocean: "1.2•10<sup>-10</sup>%",
      earth_crust: "0.006%",
      meteorites: "0.00008%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "1.4716•10<sup>-3</sup>",
      mass_magnetic_suspectibility: "2.2•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "3.0826•10<sup>-8</sup>",
      electrical_conductivity: "1.4•10<sup>6</sup>",
      resistivity: "7.4•10<sup>-7</sup>",
      superconducting_point: 0.022,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Cerium",
      youtube: "https://youtu.be/HSa9MvYc90E",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [362, 362, 599],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 1333,
      nfpa_label: "/Ce.png",
    },
  },
  {
    id: 59,
    neighbour: ["Cerium", "Neodymium"],
    description:
      "Praseodymium is a reactive, soft metal. In compounds, it shows a beautifull , lustrous green or yellow, which often is used to stain glass, ceramic and enamel. It also is used in sunglasses and safety goggles, because it can block ultraviolet light.",
    general_properties: {
      name: "Praseodymium",
      atomic_number: 59,
      period: 6,
      block: "F",
      cas_number: "7440-10-0",
      cid_number: "23942",
      symbol: "Pr",
    },
    particles: {
      electrons: 59,
      protons: 59,
      neutrons: 82,
    },
    overview: {
      latin_name: "Praseodymium",
      discovery: 1839,
      discoverer: [["Carl Gustaf Mosander", "Carl_Gustaf_Mosander"]],
    },
    atomic_properties: {
      atomic_weight: 138.90547,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N21 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>3</sup>",
      atomic_radius: 247,
      covalent_radius: 203,
    },
    thermodynamic_properties: {
      boiling_point: "3290℃",
      melting_point: "931℃",
      phase: "Solid",
      fusion_heat: 6.9,
      specific_heat: 193,
      vaporization_heat: 330,
      thermal_expansion: "6.7•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.122•10<sup>-5</sup>",
      density: 6640,
      liquid_density: 6500,
      thermal_conductivity: 13,
      sound_speed: 2280,
      shear_modulus: 15,
      poisson_ratio: 0.28,
      vickers_hardness: 400,
      young_modulus: 37,
      mohs_hardness: 1.4,
      bulk_modulus: 29,
      brinell_hardness: 481,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.13,
      ionization_energy: 527,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 11.4,
      neutron_mass_absorption: 0.00021,
      quantum_numbers: "<sup>4</sup>I<sub>9/2</sub>",
      isotopes: [
        121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
        135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
        149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
      ],
      stable: [141],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "6•10<sup>-11</sup>%",
      earth_crust: "0.00086%",
      meteorites: "9.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "2.8087•10<sup>-3</sup>",
      mass_magnetic_suspectibility: "4.23•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "5.9604•10<sup>-8</sup>",
      electrical_conductivity: "1.4•10<sup>6</sup>",
      resistivity: "7•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Praseodymium",
      youtube: "https://youtu.be/FHDb-VjDWeE",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 160],
      lattice_constant: [367.25, 367.25, 1183.54],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 60,
    neighbour: ["Praseodymium", "Promethium"],
    description:
      "Neodymium is one of the more abundant lanthanoids and has many different applications. It is often used as colorent for glass and ceramic, because its compounds, depending on concentration, can make a beautifull blue, green or red. Another important application is as active medium in Nd:YAG lasers. Nd<sub>2</sub>Fe<sub>14</sub>B, neodymium-iron-boron, known as Neodymium magnet, is the strongest permanent magnet.",
    general_properties: {
      name: "Neodymium",
      atomic_number: 60,
      period: 6,
      block: "F",
      cas_number: "7440-00-8",
      cid_number: "23934",
      symbol: "Nd",
    },
    particles: {
      electrons: 60,
      protons: 60,
      neutrons: 84,
    },
    overview: {
      latin_name: "Neodymium",
      discovery: 1885,
      discoverer: [["Baron Carl Auer von Welsbach", "Carl_Auer_von_Welsbach"]],
    },
    atomic_properties: {
      atomic_weight: 144.242,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N22 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>4</sup>",
      atomic_radius: 206,
      covalent_radius: 201,
    },
    thermodynamic_properties: {
      boiling_point: "3100℃",
      melting_point: "1021℃",
      phase: "Solid",
      fusion_heat: 7.1,
      specific_heat: 190,
      vaporization_heat: 285,
      thermal_expansion: "9.6•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.085•10<sup>-5</sup>",
      density: 7010,
      liquid_density: 6890,
      thermal_conductivity: 17,
      sound_speed: 2330,
      shear_modulus: 16,
      poisson_ratio: 0.28,
      vickers_hardness: 343,
      young_modulus: 41,
      mohs_hardness: 1.2,
      bulk_modulus: 32,
      brinell_hardness: 265,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.14,
      ionization_energy: 533.1,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 49,
      neutron_mass_absorption: 0.011,
      quantum_numbers: "<sup>5</sup>I<sub>4</sub>",
      isotopes: [
        124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
      ],
      stable: [142, 143, 145, 146, 148],
    },
    prevalence: {
      universe: "10<sup>-6</sup>%",
      sun: "3•10<sup>-7</sup>%",
      ocean: "2.8•10<sup>-10</sup>%",
      earth_crust: "0.00330%",
      meteorites: "0.00005%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "3.3648•10<sup>-3</sup>",
      mass_magnetic_suspectibility: "4.8•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "6.9235•10<sup>-8</sup>",
      electrical_conductivity: "1.6•10<sup>6</sup>",
      resistivity: "6.4•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Neodymium",
      youtube: "https://youtu.be/SoxHTCod9Fc",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [365.8, 365.8, 1179.9],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      rtecs_number: "QO8575000",
    },
  },
  {
    id: 61,
    neighbour: ["Neodymium", "Samarium"],
    description:
      "Promethium is the second element after technetium, of which no stable isotope exist. However, it is much more unstable than this, the most long-lived isotope, <sup>145</sup>Pm, has a half-life of only about two and a half years. This on Earth occurs only in traces, most of it is from neuclear waste. There are some few, very special application of Promethium, e.g. in radioisotope thermoelectric generators. Very few starts contain promethium, which they seem to produce themselves, however they may do that.",
    general_properties: {
      name: "Promethium",
      atomic_number: 61,
      period: 6,
      block: "F",
      cas_number: "7440-12-2",
      cid_number: "23944",
      symbol: "Pm",
    },
    particles: {
      electrons: 61,
      protons: 61,
      neutrons: 84,
    },
    overview: {
      latin_name: "Promethium",
      discovery: 1945,
      discoverer: [
        ["Jacob A Marinsky", "Jacob_A._Marinsky"],
        ["Lawrence Glendenin", "Lawrence_Glendenin"],
        ["Charles D Coryell", "Charles_D._Coryell"],
      ],
    },
    atomic_properties: {
      atomic_weight: 145,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N23 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>5</sup>",
      atomic_radius: 205,
      covalent_radius: 199,
    },
    thermodynamic_properties: {
      boiling_point: "3000℃",
      melting_point: "1100℃",
      phase: "Solid",
      fusion_heat: 7.7,
      vaporization_heat: 290,
      thermal_expansion: "1.1•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2•10<sup>-5</sup>",
      density: 7264,
      thermal_conductivity: 15,
      shear_modulus: 18,
      poisson_ratio: 0.28,
      young_modulus: 46,
      bulk_modulus: 33,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 540,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "5.59•10<sup>8</sup>",
      lifetime: "8.06•10<sup>8</sup>",
      neutron_cross_section: 8400,
      quantum_numbers: "<sup>6</sup>H<sub>5/2</sub>",
      decay_mode: "Beta",
      isotopes: [
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
      ],
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      electrical_conductivity: "1.3•10<sup>6</sup>",
      resistivity: "7.5•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Promethium",
      youtube: "https://youtu.be/HplP_MY78NQ",
    },
  },
  {
    id: 62,
    neighbour: ["Promethium", "Europium"],
    description:
      "It is a moderately hard silvery metal that slowly oxidizes in air. Being a typical memebr of the lanthanide series, Samarium usually assumes the oxidation state +3. Compounds of Samarium(II) are also known, most notably the monooxide SmO, monochalcogenides SmS, SmSe and SmTe, as well as Samarium(II) iodide. The last compound is a common reducing agent in chemical synthesis. Samarium has no significant biological role but is only slightly toxic.",
    general_properties: {
      name: "Samarium",
      atomic_number: 62,
      period: 6,
      block: "F",
      cas_number: "7440-19-9",
      cid_number: "23951",
      symbol: "Sm",
    },
    particles: {
      electrons: 62,
      protons: 63,
      neutrons: 88,
    },
    overview: {
      latin_name: "Samarium",
      discovery: 1879,
      discoverer: [
        ["Paul-Émile Lecoq de Boisbaudran", "Paul-Émile_Lecoq_de_Boisbaudran"],
      ],
    },
    atomic_properties: {
      atomic_weight: 150.36,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N24 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>6</sup>",
      atomic_radius: 238,
      covalent_radius: 198,
    },
    thermodynamic_properties: {
      boiling_point: "1803℃",
      melting_point: "1072℃",
      phase: "Solid",
      fusion_heat: 8.6,
      specific_heat: 196,
      vaporization_heat: 175,
      thermal_expansion: "1.27•10<sup>-5</sup>",
      neel_point: 175,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.045•10<sup>-5</sup>",
      density: 7353,
      liquid_density: 7160,
      thermal_conductivity: 13,
      sound_speed: 2130,
      shear_modulus: 20,
      poisson_ratio: 0.27,
      vickers_hardness: 412,
      young_modulus: 50,
      mohs_hardness: 1.4,
      bulk_modulus: 38,
      brinell_hardness: 441,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.17,
      ionization_energy: 544.5,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 5900,
      neutron_mass_absorption: 4.7,
      quantum_numbers: "<sup>7</sup>F<sub>0</sub>",
      isotopes: [
        128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
      ],
      stable: [144, 149, 150, 152, 154],
    },
    prevalence: {
      universe: "5•10<sup>-7</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "4.5•10<sup>-11</sup>%",
      earth_crust: "0.0006%",
      meteorites: "0.00002%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "8.1618•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "1.11•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "1.669•10<sup>-8</sup>",
      electrical_conductivity: "1.1•10<sup>6</sup>",
      resistivity: "9.4•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Samarium",
      youtube: "https://youtu.be/d-RbpEIHJRI",
    },
    atom_structure: {
      crystal_structure: "Simple Trigonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [362.1, 362.1, 2625],
      space_group_name: "R_ 3m",
      space_group_number: 166,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 1325,
    },
  },
  {
    id: 63,
    neighbour: ["Samarium", "Gadolinium"],
    description:
      "Europium is a very reactive metal, which actually has a silvery color, but oxidizes quickly in air. It is toxic and is the most ignoable of the lanthanoids after lanthanum. It has its most important application as red and blue luminescent substance, e.g. in CRT television sets. The phenomenon fluorescence was named after fluorites with Eu<sup>2+</sup> inclusores.",
    general_properties: {
      name: "Europium",
      atomic_number: 63,
      period: 6,
      block: "F",
      cas_number: "7440-53-1",
      cid_number: "23981",
      symbol: "Eu",
    },
    particles: {
      electrons: 63,
      protons: 63,
      neutrons: 89,
    },
    overview: {
      latin_name: "Europium",
      discovery: 1901,
      discoverer: [["Eugéne Anatole Demarcay", "Eugène-Anatole_Demarçay"]],
    },
    atomic_properties: {
      atomic_weight: 151.964,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N25 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>7</sup>",
      atomic_radius: 231,
      covalent_radius: 198,
    },
    thermodynamic_properties: {
      boiling_point: "1587℃",
      melting_point: "822℃",
      phase: "Solid",
      fusion_heat: 9.2,
      specific_heat: 182,
      vaporization_heat: 175,
      thermal_expansion: "3.5•10<sup>-5</sup>",
      neel_point: 90.5,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.898•10<sup>-5</sup>",
      density: 5244,
      liquid_density: 5130,
      thermal_conductivity: 14,
      shear_modulus: 7.9,
      poisson_ratio: 0.15,
      vickers_hardness: 167,
      young_modulus: 18,
      mohs_hardness: 3.1,
      bulk_modulus: 8.3,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 547.1,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 4570,
      neutron_mass_absorption: 0.6,
      quantum_numbers: "<sup>8</sup>S<sub>7/2</sub>",
      isotopes: [
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
        158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
      ],
      stable: [151, 153],
    },
    prevalence: {
      universe: "5•10<sup>-8</sup>%",
      sun: "5•10<sup>-8</sup>%",
      ocean: "1.3•10<sup>-11</sup>%",
      earth_crust: "0.00018%",
      meteorites: "5.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "1.4473•10<sup>-3</sup>",
      mass_magnetic_suspectibility: "2.76•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "4.1942•10<sup>-8</sup>",
      electrical_conductivity: "1.1•10<sup>6</sup>",
      resistivity: "9•10<sup>-7</sup>",
      superconducting_point: 1.8,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Europium",
      youtube: "https://youtu.be/uC4nn2Ku63c",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [458.1, 458.1, 458.1],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
  },
  {
    id: 64,
    neighbour: ["Europium", "Terbium"],
    description:
      "Gadolinium has some special applications in high tech and medicine. It is rather toxic and is the first element that was named after a person, Finnish Chemist and Geologist Johan Gadolin. Gadolinium is a silvery-white metal when oxidation is removed. It is only slightly malleable and is a ductile rare-earth element Gadolinium reacts with atmospheric oxygen or moist slowly to form a black coating.",
    general_properties: {
      name: "Gadolinium",
      atomic_number: 64,
      period: 6,
      block: "F",
      cas_number: "7440-54-2",
      cid_number: "23982",
      symbol: "Gd",
    },
    particles: {
      electrons: 64,
      protons: 64,
      neutrons: 93,
    },
    overview: {
      latin_name: "Gadolinium",
      discovery: 1880,
      discoverer: [
        [
          "Jean-Charles-Galissard de Marignac",
          "Jean_Charles_Galissard_de_Marignac",
        ],
      ],
    },
    atomic_properties: {
      atomic_weight: 157.25,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N25 O9 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>7</sup> 5d<sup>1</sup>",
      atomic_radius: 233,
      covalent_radius: 196,
    },
    thermodynamic_properties: {
      boiling_point: "3250℃",
      melting_point: "1313℃",
      phase: "Solid",
      fusion_heat: 10,
      specific_heat: 240,
      vaporization_heat: 305,
      thermal_expansion: "9.4•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.99•10<sup>-5</sup>",
      density: 7901,
      liquid_density: 7400,
      thermal_conductivity: 11,
      shear_modulus: 22,
      poisson_ratio: 0.26,
      vickers_hardness: 570,
      young_modulus: 55,
      mohs_hardness: 5.1,
      bulk_modulus: 38,
      sound_speed: 2680,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.2,
      ionization_energy: 593.4,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 49000,
      neutron_mass_absorption: 7.3,
      quantum_numbers: "<sup>9</sup>D<sub>2</sub>",
      isotopes: [
        134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
        162, 163, 164, 165, 166, 167, 168, 169,
      ],
      stable: [154, 155, 156, 157, 158, 160],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "2•10<sup>-7</sup>%",
      ocean: "7•10<sup>-11</sup>%",
      earth_crust: "0.00052%",
      meteorites: "0.0002%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Ferromagnetic",
      electrical_conductivity: "7.7•10<sup>5</sup>",
      resistivity: "1.3•10<sup>-6</sup>",
      curie_point: 292,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Gadolinium",
      youtube: "https://youtu.be/jDZU5urVQTY",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [363.6, 363.6, 578.26],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      rtecs_number: "LW3850000",
    },
  },
  {
    id: 65,
    neighbour: ["Gadolinium", "Dysprosium"],
    description:
      "It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. The ninth member of the lanthanide series, terbium is a fairly electropositive metal reacts withs water, evolving hydrogen gas.",
    general_properties: {
      name: "Terbium",
      atomic_number: 65,
      period: 6,
      block: "F",
      cas_number: "7440-27-9",
      cid_number: "23958",
      symbol: "Tb",
    },
    particles: {
      electrons: 65,
      protons: 65,
      neutrons: 94,
    },
    overview: {
      latin_name: "Terbium",
      discovery: 1843,
      discoverer: [["Carl Gustaf Mosander", "Carl_Gustaf_Mosander"]],
    },
    atomic_properties: {
      atomic_weight: 158.92535,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N27 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>9</sup>",
      atomic_radius: 225,
      covalent_radius: 194,
    },
    thermodynamic_properties: {
      boiling_point: "3230℃",
      melting_point: "1356℃",
      phase: "Solid",
      fusion_heat: 10.8,
      specific_heat: 182,
      vaporization_heat: 295,
      thermal_expansion: "1.03•10<sup>-5</sup>",
      neel_point: 230,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.934•10<sup>-5</sup>",
      density: 8219,
      liquid_density: 7650,
      thermal_conductivity: 11,
      shear_modulus: 22,
      poisson_ratio: 0.26,
      vickers_hardness: 863,
      young_modulus: 56,
      mohs_hardness: 2.3,
      bulk_modulus: 38.7,
      sound_speed: 2620,
      brinell_hardness: 677,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 565.8,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 23,
      neutron_mass_absorption: 0.009,
      quantum_numbers: "<sup>6</sup>H<sub>15/2</sub>",
      isotopes: [
        136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171,
      ],
      stable: [159],
    },
    prevalence: {
      universe: "5•10<sup>-8</sup>%",
      sun: "10<sup>-8</sup>%",
      ocean: "1.4•10<sup>-11</sup>%",
      earth_crust: "0.00009%",
      meteorites: "3.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "8.3•10<sup>5</sup>",
      resistivity: "1.2•10<sup>-6</sup>",
      curie_point: 222,
      volume_magnetic_suspectibility: "1.1177•10<sup>-1</sup>",
      mass_magnetic_suspectibility: "1.36•10<sup>-5</sup>",
      molar_magnetic_suspectibility: "2.1614•10<sup>-6</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Terbium",
      youtube: "https://youtu.be/On5LjH9TQxY",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [360.1, 360.1, 569.36],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 66,
    neighbour: ["Terbium", "Holmium"],
    description:
      "It is a rare earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in nature as a free element, though it is found in various minerals, such as xenotime. Naturally occurring Dysprosium is composed of seven isotopes, the most abundant of which is <sup>164</sup>Dy.",
    general_properties: {
      name: "Dysprosium",
      atomic_number: 66,
      period: 6,
      block: "F",
      cas_number: "7429-91-6",
      cid_number: "23912",
      symbol: "Dy",
    },
    particles: {
      electrons: 66,
      protons: 66,
      neutrons: 97,
    },
    overview: {
      latin_name: "Dysprosium",
      discovery: 1886,
      discoverer: [
        ["Paul-Émile Lecoq de Boisbaudran", "Paul-Émile_Lecoq_de_Boisbaudran"],
      ],
    },
    atomic_properties: {
      atomic_weight: 162.5,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N28 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>10</sup>",
      atomic_radius: 228,
      covalent_radius: 192,
    },
    thermodynamic_properties: {
      boiling_point: "2567℃",
      melting_point: "1412℃",
      phase: "Solid",
      fusion_heat: 11.1,
      specific_heat: 167,
      vaporization_heat: 280,
      thermal_expansion: "9.9•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.9•10<sup>-5</sup>",
      density: 8551,
      liquid_density: 8370,
      thermal_conductivity: 11,
      shear_modulus: 25,
      poisson_ratio: 0.25,
      vickers_hardness: 540,
      young_modulus: 61,
      mohs_hardness: 1.8,
      bulk_modulus: 41,
      sound_speed: 2710,
      brinell_hardness: 500,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.22,
      ionization_energy: 573,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 950,
      neutron_mass_absorption: 0.2,
      quantum_numbers: "<sup>5</sup>I<sub>8</sub>",
      isotopes: [
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
        166, 167, 168, 169, 170, 171, 172, 173,
      ],
      stable: [156, 158, 160, 161, 162, 163, 164],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "2•10<sup>-7</sup>%",
      ocean: "9.1•10<sup>-11</sup>%",
      earth_crust: "0.00062%",
      meteorites: "0.00003%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "1.1•10<sup>6</sup>",
      resistivity: "9.1•10<sup>-7</sup>",
      curie_point: 87,
      volume_magnetic_suspectibility: "4.6603•10<sup>-2</sup>",
      mass_magnetic_suspectibility: "5.45•10<sup>-6</sup>",
      molar_magnetic_suspectibility: "8.85625•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Dysprosium",
      youtube: "https://youtu.be/uc4EVhl-EuY",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [359.3, 359.3, 565.37],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 67,
    neighbour: ["Dysprosium", "Erbium"],
    description:
      "Part of the lanthanide series, holmium is a rare-earth element. Holmium was discovered by swedish chemist Per Theodor Cleve. Its oxides was first isolated from rare-earth ores in 1978. The elements name comes from Holmia, the latin name for the city of Stockholm.",
    general_properties: {
      name: "Holmium",
      atomic_number: 67,
      period: 6,
      block: "F",
      cas_number: "7440-60-0",
      cid_number: "23988",
      symbol: "Ho",
    },
    particles: {
      electrons: 67,
      protons: 67,
      neutrons: 98,
    },
    overview: {
      latin_name: "Holmium",
      discovery: 1878,
      discoverer: [
        ["Marc Delafontaine", "Marc_Delafontaine"],
        ["Per Teodor Cleve", "Per_Teodor_Cleve"],
        ["Jacques-Louis Soret", "Jacques-Louis_Soret"],
      ],
    },
    atomic_properties: {
      atomic_weight: 164.93033,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N29 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>11</sup>",
      atomic_radius: 226,
      covalent_radius: 192,
    },
    thermodynamic_properties: {
      boiling_point: "2700℃",
      melting_point: "1474℃",
      phase: "Solid",
      fusion_heat: 17,
      specific_heat: 165,
      vaporization_heat: 265,
      thermal_expansion: "1.12•10<sup>-5</sup>",
      neel_point: 132,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.875•10<sup>-5</sup>",
      density: 8795,
      liquid_density: 8340,
      thermal_conductivity: 16,
      shear_modulus: 26,
      poisson_ratio: 0.23,
      vickers_hardness: 481,
      young_modulus: 65,
      mohs_hardness: 1.6,
      bulk_modulus: 40,
      sound_speed: 2760,
      brinell_hardness: 746,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.23,
      ionization_energy: 581,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 65,
      neutron_mass_absorption: 0.015,
      quantum_numbers: "<sup>4</sup>I<sub>15/2</sub>",
      isotopes: [
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175,
      ],
      stable: [165],
    },
    prevalence: {
      universe: "5•10<sup>-8</sup>%",
      ocean: "2.2•10<sup>-11</sup>%",
      earth_crust: "0.00012%",
      meteorites: "5.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "1.1•10<sup>6</sup>",
      resistivity: "9.4•10<sup>-7</sup>",
      curie_point: 20,
      volume_magnetic_suspectibility: "4.82845•10<sup>-2</sup>",
      mass_magnetic_suspectibility: "5.49•10<sup>-6</sup>",
      molar_magnetic_suspectibility: "9.05467•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Holmium",
      youtube: "https://youtu.be/v5CNMTfWVJ8",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [357.73, 357.73, 561.58],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 68,
    neighbour: ["Holmium", "Thulium"],
    description:
      "Erbium is used for amplifiers in optical fibres and therefore is very important for the internet and the transcontinental data transfer. Erbium oxide can double the intensity of optical light under certain conditions and so allows the signal to travel long distances without fading. This is a good example of how a neglectable and mostly unknown element can certainly become very popular for a single special qualification.",
    general_properties: {
      name: "Erbium",
      atomic_number: 68,
      period: 6,
      block: "F",
      cas_number: "7440-52-0",
      cid_number: "23980",
      symbol: "Ho",
    },
    particles: {
      electrons: 68,
      protons: 68,
      neutrons: 99,
    },
    overview: {
      latin_name: "Erbium",
      discovery: 1842,
      discoverer: [["Carl Gustaf Mosander", "Carl_Gustaf_Mosander"]],
    },
    atomic_properties: {
      atomic_weight: 167.259,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N30 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>12</sup>",
      atomic_radius: 226,
      covalent_radius: 189,
    },
    thermodynamic_properties: {
      boiling_point: "2868℃",
      melting_point: "1497℃",
      phase: "Solid",
      fusion_heat: 19.9,
      specific_heat: 168,
      vaporization_heat: 285,
      thermal_expansion: "1.22•10<sup>-5</sup>",
      neel_point: 82,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.845•10<sup>-5</sup>",
      density: 9066,
      liquid_density: 8860,
      thermal_conductivity: 15,
      shear_modulus: 28,
      poisson_ratio: 0.24,
      vickers_hardness: 589,
      young_modulus: 70,
      mohs_hardness: 2,
      bulk_modulus: 44,
      sound_speed: 2830,
      brinell_hardness: 814,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.24,
      ionization_energy: 589.3,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 165,
      neutron_mass_absorption: 0.036,
      quantum_numbers: "<sup>3</sup>H<sub>6</sub>",
      isotopes: [
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
        171, 172, 173, 174, 175, 176, 177,
      ],
      stable: [162, 164, 166, 167, 168, 170],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "10<sup>-7</sup>%",
      earth_crust: "0.0003%",
      ocean: "9•10<sup>-11</sup>%",
      meteorites: "0.00002%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "1.2•10<sup>6</sup>",
      resistivity: "8.6•10<sup>-7</sup>",
      curie_point: 32,
      volume_magnetic_suspectibility: "3.41788•10<sup>-2</sup>",
      mass_magnetic_suspectibility: "3.77•10<sup>-6</sup>",
      molar_magnetic_suspectibility: "6.30566•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Erbium",
      youtube: "https://youtu.be/zJ7SfFTUqgQ",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [355.88, 355.88, 558.74],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 69,
    neighbour: ["Erbium", "Ytterbium"],
    description:
      "It is the thirteenth and third last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds; because it occurs so late in the series, however, the +2 oxidation state is also stabilized by the nearly full 4f shell that results.",
    general_properties: {
      name: "Thulium",
      atomic_number: 69,
      period: 6,
      block: "F",
      cas_number: "7440-30-4",
      cid_number: "23961",
      symbol: "Tm",
    },
    particles: {
      electrons: 69,
      protons: 69,
      neutrons: 100,
    },
    overview: {
      latin_name: "Thulium",
      discovery: 1879,
      discoverer: [["Per Teodor Cleve", "Per_Teodor_Cleve"]],
    },
    atomic_properties: {
      atomic_weight: 168.93422,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N31 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>13</sup>",
      atomic_radius: 222,
      covalent_radius: 190,
    },
    thermodynamic_properties: {
      boiling_point: "1950℃",
      melting_point: "1545℃",
      phase: "Solid",
      fusion_heat: 16.8,
      specific_heat: 160,
      vaporization_heat: 250,
      thermal_expansion: "1.33•10<sup>-5</sup>",
      neel_point: 56,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.812•10<sup>-5</sup>",
      density: 9321,
      liquid_density: 8560,
      thermal_conductivity: 17,
      shear_modulus: 31,
      poisson_ratio: 0.21,
      vickers_hardness: 520,
      young_modulus: 74,
      mohs_hardness: 1.8,
      bulk_modulus: 45,
      brinell_hardness: 471,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.25,
      ionization_energy: 596.7,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 105,
      neutron_mass_absorption: 0.025,
      quantum_numbers: "<sup>2</sup>F<sub>7/2</sub>",
      isotopes: [
        145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
        159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175, 176, 177, 178, 179,
      ],
      stable: [169],
    },
    prevalence: {
      universe: "10<sup>-8</sup>%",
      sun: "2•10<sup>-8</sup>%",
      ocean: "2•10<sup>-11</sup>%",
      earth_crust: "0.00005%",
      meteorites: "2.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "1.4•10<sup>6</sup>",
      resistivity: "7•10<sup>-7</sup>",
      curie_point: 25,
      volume_magnetic_suspectibility: "1.85488•10<sup>-2</sup>",
      mass_magnetic_suspectibility: "1.99•10<sup>-6</sup>",
      molar_magnetic_suspectibility: "3.36179•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Thulium",
      youtube: "https://youtu.be/DyStjcP-ppw",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [353.75, 353.75, 555.46],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 70,
    neighbour: ["Thulium", "Lutetium"],
    description:
      "Ytterbium forms a protective oxide layer in air, which makes it quite resistant. It is not particularly rare for a lanthanoid, but difficult to seperate from the others, so it is not used much. Its main application is as additive in special steels and for special permanent magnets. Ytterbium is bout 25%-30% lighter (less dense) than its neighbors Thulium and Lutetium.",
    general_properties: {
      name: "Ytterbium",
      atomic_number: 70,
      period: 6,
      block: "F",
      cas_number: "7440-64-4",
      cid_number: "23992",
      symbol: "Yb",
    },
    particles: {
      electrons: 70,
      protons: 70,
      neutrons: 103,
    },
    overview: {
      latin_name: "Ytterbium",
      discovery: 1878,
      discoverer: [
        [
          "Jean-Charles-Galinard de Marignac",
          "Jean_Charles_Galissard_de_Marignac",
        ],
      ],
    },
    atomic_properties: {
      atomic_weight: 173.045,
      oxidation_states: [2, 3],
      electron_shell_configuration: "K2 L8 M18 N32 O8 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup>",
      atomic_radius: 222,
      covalent_radius: 187,
    },
    thermodynamic_properties: {
      boiling_point: "1196℃",
      melting_point: "819℃",
      phase: "Solid",
      fusion_heat: 7.7,
      specific_heat: 154,
      vaporization_heat: 160,
      thermal_expansion: "2.63•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.634•10<sup>-5</sup>",
      density: 6570,
      liquid_density: 6210,
      thermal_conductivity: 39,
      shear_modulus: 9.9,
      poisson_ratio: 0.21,
      vickers_hardness: 206,
      young_modulus: 24,
      bulk_modulus: 31,
      sound_speed: 1590,
      brinell_hardness: 343,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 603.4,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 35,
      neutron_mass_absorption: 0.0076,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
        162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
        176, 177, 178, 179, 180, 181, 182,
      ],
      stable: [168, 170, 171, 172, 173, 174, 176],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "8•10<sup>-11</sup>%",
      earth_crust: "0.00028%",
      meteorites: "0.00002%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "3.6•10<sup>6</sup>",
      resistivity: "2.8•10<sup>-7</sup>",
      volume_magnetic_suspectibility: "3.88•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "5.9•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "1.02•10<sup>-9</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Ytterbium",
      youtube: "https://youtu.be/ivC-dBZvAkU",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [548.47, 548.47, 548.47],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      rtecs_number: "ZG1925000",
    },
  },
  {
    id: 71,
    neighbour: ["Ytterbium", "Hafnium"],
    description:
      "Lutetium is the last of the lanthanoids, the hardest of them, the one with the smallest atomic diameter, the rarest stable after thulium and the one which is most difficult to extract. Therefore it is rather expensive and is scarcely used. The natural occuring, radioactive <sup>176</sup>Lu, which has a half-life of 38 billion years, is used to determine the age of meteorites.",
    general_properties: {
      name: "Lutetium",
      atomic_number: 71,
      period: 6,
      block: "F",
      cas_number: "7439-94-3",
      cid_number: "23929",
      symbol: "Lu",
    },
    particles: {
      electrons: 71,
      protons: 71,
      neutrons: 104,
    },
    overview: {
      latin_name: "Lutetium",
      discovery: 1907,
      discoverer: [
        ["Georges Urbain", "Georges_Urbain"],
        ["Charles James", "Charles_James"],
      ],
    },
    atomic_properties: {
      atomic_weight: 174.9668,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N32 O9 P2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup> 6s<sup>2</sup> 4f<sup>14</sup> 5d<sup>1</sup>",
      atomic_radius: 217,
      covalent_radius: 187,
    },
    thermodynamic_properties: {
      boiling_point: "3402℃",
      melting_point: "1663℃",
      phase: "Solid",
      fusion_heat: 22,
      specific_heat: 154,
      vaporization_heat: 415,
      thermal_expansion: "9.9•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.778•10<sup>-5</sup>",
      density: 9841,
      liquid_density: 9300,
      thermal_conductivity: 16,
      shear_modulus: 27,
      poisson_ratio: 0.26,
      vickers_hardness: 1160,
      young_modulus: 69,
      mohs_hardness: 2.6,
      bulk_modulus: 48,
      brinell_hardness: 893,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.27,
      ionization_energy: 523.5,
      electron_affinity: 50,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 84,
      neutron_mass_absorption: 0.022,
      quantum_numbers: "<sup>2</sup>D<sub>3/2</sub>",
      isotopes: [
        150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
        164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
        178, 179, 180, 181, 182, 183, 184,
      ],
      stable: [175],
    },
    prevalence: {
      universe: "10<sup>-8</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "1.5•10<sup>-11</sup>%",
      earth_crust: "0.00006%",
      meteorites: "2.9•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      electrical_conductivity: "1.8•10<sup>6</sup>",
      resistivity: "5.6•10<sup>-7</sup>",
      superconducting_point: 0.1,
      volume_magnetic_suspectibility: "1.18•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "1.2•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "2.1•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Lutetium",
      youtube: "https://youtu.be/Z6HYAlSdR2g",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [350.31, 350.31, 555.09],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
];
