import ElementDetailsProps from "@/types/ElementTypes";

export const RowFourElem: ElementDetailsProps[] = [
  {
    id: 19,
    neighbour: ["Argon", "Calcium"],
    description:
      "Potassium is as abundant element, which in its pure form is a silvery white, light metal and is very reactive. It explosively reacts with water. What dealing with elemental potassium,painstaking precaution is inevitable. in compounds, potassium is essential to animal and plants,several natural minerals contain it. The rare natural isotope potassium 40, a beta emitter, has a half life of 1.25 billion years.",
    general_properties: {
      name: "Potassium",
      atomic_number: 19,
      group: 1,
      period: 4,
      block: "S",
      cas_number: "7440-09-7",
      cid_number: "5462222",
      symbol: "K",
    },
    particles: {
      electrons: 19,
      protons: 19,
      neutrons: 20,
    },
    overview: {
      latin_name: "Kalium",
      discovery: 1807,
      discoverer: [["Humphry Davy", "Humphry_Davy"]],
    },
    atomic_properties: {
      atomic_weight: 39.0983,
      oxidation_states: [1],
      electron_shell_configuration: "K2 L8 M8 N1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>1</sup>",
      atomic_radius: 243,
      covalent_radius: 203,
      van_der_walls_radius: 275,
    },
    thermodynamic_properties: {
      boiling_point: "759℃",
      melting_point: "63.38℃",
      phase: "Solid",
      fusion_heat: 2.33,
      specific_heat: 757,
      vaporization_heat: 76.9,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "4.57•10<sup>-5</sup>",
      brinell_hardness: 0.363,
      bulk_modulus: 3.1,
      density: 856,
      liquid_density: 828,
      mohs_hardness: 0.4,
      thermal_conductivity: 100,
      sound_speed: 2000,
      shear_modulus: 1.3,
    },
    reactivity: {
      valence: 1,
      electronegativity: 0.82,
      electron_affinity: 48.4,
      ionization_energy: 418.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.1,
      neutron_mass_absorption: 0.0018,
      quantum_numbers: "<sup>2</sup>S<sub>1/2</sub>",
      isotopes: [
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
        50, 51, 52, 53, 54, 55,
      ],
      stable: [39, 41],
    },
    prevalence: {
      earth_crust: "1.50%",
      ocean: "0.04%",
      human: "0.20%",
      meteorites: "0.07%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "5.74•10<sup>-6</sup>",
      mass_magnetic_suspectibility: "6.7•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "2.62•10<sup>-10</sup>",
      electrical_conductivity: "1.4•10<sup>7</sup>",
      resistivity: "7•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Potassium",
      youtube: "https://youtu.be/ANH-v-jd9PQ",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [532.8, 532.8, 532.8],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.3,
      dot_number: 2257,
      rtecs_number: "TS6460000",
      nfpa_label: "/K.png",
    },
  },
  {
    id: 20,
    neighbour: ["Potassium", "Scandium"],
    description:
      "Calcium is a very abundant element, which in nature above all occurs as calcium carbonates (CaCO<sub>3</sub>,lime) and calcium sulphate (CaSO<sub>4</sub>,gypsum). Elemental calcium is a grey metal, that slowly reacts with air and fiercely reacts with water. For humans and animals it is the first of all important,because boneas,teeth and exoskeletons to a large part consist of calcium compounds like tricalcium phosphate.",
    general_properties: {
      name: "Calcium",
      atomic_number: 20,
      group: 2,
      period: 4,
      block: "S",
      cas_number: "7440-70-2",
      cid_number: "5460341",
      symbol: "Ca",
    },
    particles: {
      electrons: 20,
      protons: 20,
      neutrons: 20,
    },
    overview: {
      latin_name: "Calcium",
      discovery: 1807,
      discoverer: [["Humphry Davy", "Humphry_Davy"]],
    },
    atomic_properties: {
      atomic_weight: 40.078,
      oxidation_states: [2],
      electron_shell_configuration: "K2 L8 M8 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup>",
      atomic_radius: 194,
      covalent_radius: 176,
    },
    thermodynamic_properties: {
      boiling_point: "1484℃",
      melting_point: "842℃",
      phase: "Solid",
      fusion_heat: 8.54,
      specific_heat: 631,
      vaporization_heat: 155,
      thermal_expansion: "2.23•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "4.57•10<sup>-5</sup>",
      brinell_hardness: 167,
      bulk_modulus: 17,
      density: 1550,
      liquid_density: 1378,
      mohs_hardness: 1.75,
      thermal_conductivity: 200,
      sound_speed: 3810,
      shear_modulus: 7.4,
      poisson_ratio: 0.31,
      young_modulus: 20,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1,
      electron_affinity: 2.37,
      ionization_energy: 589.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.43,
      neutron_mass_absorption: 0.00037,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57,
      ],
      stable: [40, 42, 43, 44, 46],
    },
    prevalence: {
      universe: "0.01%",
      sun: "0.01%",
      earth_crust: "5.00%",
      ocean: "0.000420%",
      human: "1.40%",
      meteorites: "1.10%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "2.139•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "1.38•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "5.531•10<sup>-10</sup>",
      electrical_conductivity: "2.9•10<sup>7</sup>",
      resistivity: "3.4•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Calcium",
      youtube: "https://youtu.be/V9fuY8_ffFg",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [558.84, 558.84, 558.84],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.2,
      dot_number: 1855,
    },
  },
  {
    id: 21,
    neighbour: ["Calcium", "Titanium"],
    description:
      "Scandium is the first transition metal and the first rare earth elements, the latter also includes yttrium and the lanthanoids. The ignoble light metal has only a few applications, because it chemistry is not complex it also is rather expensive. It is used in high quality, light alloy, e.g. for frames of racing cycle",
    general_properties: {
      name: "Scandium",
      atomic_number: 21,
      group: 3,
      period: 4,
      block: "D",
      cas_number: "7440-20-2",
      cid_number: "23952",
      symbol: "Sc",
    },
    particles: {
      electrons: 21,
      protons: 21,
      neutrons: 24,
    },
    overview: {
      latin_name: "Calcium",
      discovery: 1879,
      discoverer: [["Lars Fredrik Nilson", "Lars_Fredrik_Nilson"]],
    },
    atomic_properties: {
      atomic_weight: 44.955908,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M9 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>1</sup>",
      atomic_radius: 184,
      covalent_radius: 170,
    },
    thermodynamic_properties: {
      boiling_point: "2830℃",
      melting_point: "1541℃",
      phase: "Solid",
      fusion_heat: 16,
      specific_heat: 567,
      vaporization_heat: 318,
      thermal_expansion: "1.02•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.506•10<sup>-5</sup>",
      brinell_hardness: 750,
      bulk_modulus: 57,
      density: 2985,
      liquid_density: 2800,
      thermal_conductivity: 16,
      shear_modulus: 29,
      poisson_ratio: 0.28,
      young_modulus: 74,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.36,
      electron_affinity: 18.1,
      ionization_energy: 633.1,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 27.2,
      neutron_mass_absorption: 0.025,
      quantum_numbers: "<sup>2</sup>D<sub>3/2</sub>",
      isotopes: [
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60,
      ],
      stable: [45],
    },
    prevalence: {
      universe: "3•10<sup>-6</sup>%",
      sun: "4•10<sup>-6</sup>%",
      earth_crust: "0.0026%",
      ocean: "1.5•10<sup>-10</sup>%",
      human: "1.40%",
      meteorites: "0.00064%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "2.627•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "8.8•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "3.956•10<sup>-9</sup>",
      electrical_conductivity: "1.8•10<sup>6</sup>",
      resistivity: "5.5•10<sup>-7</sup>",
      superconducting_point: 0.05,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Scandium",
      youtube: "https://youtu.be/Dh9QcKKObQE",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [330.9, 330.9, 527.33],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 22,
    neighbour: ["Scandium", "Vanadium"],
    description:
      "Titanium is a grey, light, but very strong metal. Is is quite frequent, but hard to extract, which makes the pure metal fairly expenxive. It is used a lot for technical components and steels. Much better available than the metal itself is titanium dioxide,TiO<sub>2</sub>, the most widely use white pigment, which you can see on nearly every white painted wall. Titanium Dioxide is one of the thermic most enduring molecules and one of only a few that can be found in some stars.",
    general_properties: {
      name: "Titanium",
      atomic_number: 22,
      group: 4,
      period: 4,
      block: "D",
      cas_number: "7440-32-6",
      cid_number: "23963",
      symbol: "Ti",
    },
    particles: {
      electrons: 22,
      protons: 22,
      neutrons: 26,
    },
    overview: {
      latin_name: "Titanium",
      discovery: 1791,
      discoverer: [
        ["William Gregor", "William_Gregor"],
        ["Lars Fredrik Nilson", "Lars_Fredrik_Nilson"],
      ],
    },
    atomic_properties: {
      atomic_weight: 47.867,
      oxidation_states: [2, 3, 4],
      electron_shell_configuration: "K2 L8 M10 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>2</sup>",
      atomic_radius: 176,
      covalent_radius: 160,
    },
    thermodynamic_properties: {
      boiling_point: "3287℃",
      melting_point: "1668℃",
      phase: "Solid",
      fusion_heat: 18.7,
      specific_heat: 520,
      vaporization_heat: 425,
      thermal_expansion: "8.6•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.602•10<sup>-5</sup>",
      brinell_hardness: 716,
      bulk_modulus: 110,
      density: 4507,
      liquid_density: 4110,
      thermal_conductivity: 22,
      shear_modulus: 44,
      poisson_ratio: 0.32,
      young_modulus: 116,
      vickers_hardness: 970,
      sound_speed: 4140,
      mohs_hardness: 6,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.54,
      electron_affinity: 7.6,
      ionization_energy: 658.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 6.1,
      neutron_mass_absorption: 0.0044,
      quantum_numbers: "<sup>3</sup>F<sub>2</sub>",
      isotopes: [
        38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59, 60, 61, 62, 63,
      ],
      stable: [46, 47, 48, 49, 50],
    },
    prevalence: {
      universe: "0.0003%",
      sun: "0.0004%",
      earth_crust: "0.66%",
      ocean: "10<sup>-7</sup>%",
      meteorites: "0.05%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "1.807•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "4.01•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "1.919•10<sup>-9</sup>",
      electrical_conductivity: "2.5•10<sup>6</sup>",
      resistivity: "4•10<sup>-7</sup>",
      superconducting_point: 0.4,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Titanium",
      youtube: "https://youtu.be/ptAR3allc7U",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [295.08, 295.08, 468.55],
      space_group_name: "F6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.2,
      dot_number: 1456,
    },
  },
  {
    id: 23,
    neighbour: ["Titanium", "Chromium"],
    description:
      "Vanadium is a soft, malleable metal, which, when exposed to air, forms a hard, protective oxide layer. It is mainly used in steel alloys. A common product, whcih man people have at home, is a chrome vanadium steel screwdriver. In nature, vanadium appears in differnent, often colorful minerals, but only rarely in high concentration.",
    general_properties: {
      name: "Vanadium",
      atomic_number: 23,
      group: 5,
      period: 4,
      block: "D",
      cas_number: "7440-62-2",
      cid_number: "23990",
      symbol: "V",
    },
    particles: {
      electrons: 23,
      protons: 23,
      neutrons: 28,
    },
    overview: {
      latin_name: "Vanadium",
      discovery: 1801,
      discoverer: [
        ["Andres Manuel Del Rio", "Andres_Manuel_Del_Rio"],
        ["Nils Gabriel Sefström", "Nils_Gabriel_Sefström"],
      ],
    },
    atomic_properties: {
      atomic_weight: 50.9415,
      oxidation_states: [2, 3, 4, 5],
      electron_shell_configuration: "K2 L8 M11 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>3</sup>",
      atomic_radius: 171,
      covalent_radius: 153,
    },
    thermodynamic_properties: {
      boiling_point: "3407℃",
      melting_point: "1910℃",
      phase: "Solid",
      fusion_heat: 22.8,
      specific_heat: 489,
      vaporization_heat: 453,
      thermal_expansion: "8.4•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "8.337•10<sup>-6</sup>",
      brinell_hardness: 628,
      bulk_modulus: 160,
      density: 6110,
      liquid_density: 5500,
      thermal_conductivity: 31,
      shear_modulus: 47,
      poisson_ratio: 0.37,
      young_modulus: 128,
      mohs_hardness: 7,
      sound_speed: 4560,
      vickers_hardness: 628,
    },
    reactivity: {
      valence: 5,
      electronegativity: 1.63,
      electron_affinity: 50.6,
      ionization_energy: 650.9,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 5.06,
      neutron_mass_absorption: 0.0033,
      quantum_numbers: "<sup>4</sup>F<sub>3/2</sub>",
      isotopes: [
        40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
        58, 59, 60, 61, 62, 63, 64, 65,
      ],
      stable: [51],
    },
    prevalence: {
      universe: "0.0001%",
      sun: "0.00004%",
      earth_crust: "0.02%",
      ocean: "1.5•10<sup>-7</sup>%",
      human: "3•10<sup>-6</sup>%",
      meteorites: "0.01%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "3.837•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "6.28•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "3.199•10<sup>-9</sup>",
      electrical_conductivity: "5•10<sup>6</sup>",
      resistivity: "2•10<sup>-7</sup>",
      superconducting_point: 5.4,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Vanadium",
      youtube: "https://youtu.be/eySYRB4OUZ4",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [303, 303, 303],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 24,
    neighbour: ["Vanadium", "Manganese"],
    description:
      "Chromium is a very hard and shiny silvery metal and has many colourful compounds. A lot of these are quite toxic. Chromium(VI), e.g. as CrO<sub>2</sub>, is a very dangerous environmental toxin. Elemental chromium is widely used for planting for optical reasons and corrosion protection. Chromium is added to steel to make it stainless.",
    general_properties: {
      name: "Chromium",
      atomic_number: 24,
      group: 6,
      period: 4,
      block: "D",
      cas_number: "7440-47-3",
      cid_number: "23976",
      symbol: "Cr",
    },
    particles: {
      electrons: 24,
      protons: 24,
      neutrons: 28,
    },
    overview: {
      latin_name: "Chromium",
      discovery: 1780,
      discoverer: [["Nicolas-Louis Vauquelin", "Louis_Nicolas_Vauquelin"]],
    },
    atomic_properties: {
      atomic_weight: 51.9961,
      oxidation_states: [-2, 2, 3, 4, 6],
      electron_shell_configuration: "K2 L8 M13 N1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>1</sup> 3d<sup>5</sup>",
      atomic_radius: 166,
      covalent_radius: 139,
    },
    thermodynamic_properties: {
      boiling_point: "2671℃",
      melting_point: "1907℃",
      phase: "Solid",
      fusion_heat: 20.5,
      specific_heat: 448,
      vaporization_heat: 339,
      thermal_expansion: "4.9•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "7.232•10<sup>-6</sup>",
      brinell_hardness: 1120,
      bulk_modulus: 160,
      density: 7190,
      liquid_density: 6300,
      thermal_conductivity: 94,
      shear_modulus: 115,
      poisson_ratio: 0.21,
      young_modulus: 279,
      mohs_hardness: 8.5,
      sound_speed: 5940,
      vickers_hardness: 1060,
    },
    reactivity: {
      valence: 6,
      electronegativity: 1.66,
      electron_affinity: 64.3,
      ionization_energy: 652.9,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 3.1,
      neutron_mass_absorption: 0.0021,
      quantum_numbers: "<sup>7</sup>S<sub>3</sub>",
      isotopes: [
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
        60, 61, 62, 63, 64, 65, 66, 67,
      ],
      stable: [50, 52, 53, 54],
    },
    prevalence: {
      universe: "0.0015%",
      sun: "0.0020%",
      earth_crust: "0.01%",
      ocean: "6•10<sup>-8</sup>%",
      human: "3•10<sup>-6</sup>%",
      meteorites: "0.30%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Antiferromagnetic",
      volume_magnetic_suspectibility: "3.177•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "4.45•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "2.314•10<sup>-9</sup>",
      electrical_conductivity: "7.9•10<sup>6</sup>",
      resistivity: "1.3•10<sup>-7</sup>",
      superconducting_point: 5.4,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Chromium",
      youtube: "https://youtu.be/JHs150cSTVc",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [291, 291, 291],
      space_group_name: "Fm_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "GB4200000",
      nfpa_label: "/Cr.png",
    },
  },
  {
    id: 25,
    neighbour: ["Chromium", "Iron"],
    description:
      "Manganese is a very common metal and often used in alloys. It is an important ingridient in many steels. It can be found in large quantities in many minerals. its probably most famous compound is the strong oxidizing agent potassium paramanganate. Every life from needs small amount of managnese.",
    general_properties: {
      name: "Manganese",
      atomic_number: 25,
      group: 7,
      period: 4,
      block: "D",
      cas_number: "7439-96-5",
      cid_number: "23930",
      symbol: "Mn",
    },
    particles: {
      electrons: 25,
      protons: 25,
      neutrons: 30,
    },
    overview: {
      latin_name: "Manganum",
      discovery: 1774,
      discoverer: [["Johan Gottilieb Gahn", "Johan_Gottilieb_Gahn"]],
    },
    atomic_properties: {
      atomic_weight: 53.938044,
      oxidation_states: [-1, 2, 3, 4, 5, 6, 7],
      electron_shell_configuration: "K2 L8 M13 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>5</sup>",
      atomic_radius: 161,
      covalent_radius: 139,
    },
    thermodynamic_properties: {
      boiling_point: "2061℃",
      melting_point: "1246℃",
      phase: "Solid",
      fusion_heat: 13.2,
      specific_heat: 479,
      vaporization_heat: 220,
      thermal_expansion: "2.17•10<sup>-5</sup>",
      neel_point: 100,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "7.354•10<sup>-6</sup>",
      brinell_hardness: 196,
      bulk_modulus: 120,
      density: 7470,
      liquid_density: 5950,
      thermal_conductivity: 7.8,
      young_modulus: 198,
      mohs_hardness: 6,
      sound_speed: 5150,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.55,
      ionization_energy: 717.3,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 13.3,
      neutron_mass_absorption: 0.0083,
      quantum_numbers: "<sup>6</sup>S<sub>5/2</sub>",
      isotopes: [
        44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68, 69,
      ],
      stable: [55],
    },
    prevalence: {
      universe: "0.0008%",
      sun: "0.0010%",
      earth_crust: "0.11%",
      ocean: "2•10<sup>-7</sup>%",
      human: "0.00002%",
      meteorites: "0.27%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Paramagnetic",
      volume_magnetic_suspectibility: "9.0387•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "1.21•10<sup>-7</sup>",
      molar_magnetic_suspectibility: "6.6475•10<sup>-9</sup>",
      electrical_conductivity: "6.2•10<sup>5</sup>",
      resistivity: "1.6•10<sup>-6</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Manganese",
      youtube: "https://youtu.be/9ZLcpb0FmFE",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [891.25, 891.25, 891.25],
      space_group_name: "l_ 43m",
      space_group_number: 217,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 26,
    neighbour: ["Manganese", "Cobalt"],
    description:
      "Iron is a very silvery metal, which is very abundant and is used for multiple purpose. Commonly it is alloyed together with carbon and other elements, to become steel. the number of different steels is very high, their characters vary over wide span. Sometimes pure iron occurs in nature. But most is found in ores. Meteorites,that hit Earth's ground and don't evaporate before, often are iron Meteorites.",
    general_properties: {
      name: "Iron",
      atomic_number: 26,
      group: 8,
      period: 4,
      block: "D",
      cas_number: "7439-89-6",
      cid_number: "23925",
      symbol: "Fe",
      allotropes: [
        ["Ferrite", "https://en.wikipedia.org/wiki/Ferrite_(magnet)"],
        ["Austenite", "https://en.wikipedia.org/wiki/Austenite"],
        ["Delta Iron", "https://www.britannica.com/science/delta-iron"],
        ["Hexaferrum", "https://en.wikipedia.org/wiki/Hexaferrum"],
      ],
    },
    particles: {
      electrons: 26,
      protons: 26,
      neutrons: 30,
    },
    overview: {
      latin_name: "Ferrum",
      discovery: -2000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 55.845,
      oxidation_states: [-2, 2, 3],
      electron_shell_configuration: "K2 L8 M14 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>6</sup>",
      atomic_radius: 156,
      covalent_radius: 132,
    },
    thermodynamic_properties: {
      boiling_point: "2861℃",
      melting_point: "1538℃",
      phase: "Solid",
      fusion_heat: 13.8,
      specific_heat: 449,
      vaporization_heat: 347,
      thermal_expansion: "1.18•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "7.092•10<sup>-6</sup>",
      brinell_hardness: 490,
      bulk_modulus: 170,
      density: 7874,
      liquid_density: 6980,
      thermal_conductivity: 80,
      shear_modulus: 82,
      poisson_ratio: 0.29,
      young_modulus: 211,
      mohs_hardness: 4,
      sound_speed: 5940,
      vickers_hardness: 608,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.83,
      electron_affinity: 15.7,
      ionization_energy: 762.5,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.56,
      neutron_mass_absorption: 0.0015,
      quantum_numbers: "<sup>5</sup>D<sub>4</sub>",
      isotopes: [
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
        63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
      ],
      stable: [54, 56, 57, 58],
    },
    prevalence: {
      universe: "0.0015%",
      sun: "0.0020%",
      earth_crust: "0.01%",
      ocean: "6•10<sup>-8</sup>%",
      human: "3•10<sup>-6</sup>%",
      meteorites: "0.30%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Ferromagnetic",
      electrical_conductivity: "10<sup>7</sup>",
      resistivity: "9.7•10<sup>-8</sup>",
      curie_point: 1043,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Iron",
      youtube: "https://youtu.be/uAMMQv0rKFI",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [286.65, 286.65, 286.65],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "NO4565500",
      nfpa_label: "/Fe.png",
    },
  },
  {
    id: 27,
    neighbour: ["Iron", "Nickel"],
    description:
      "Cobaly is a ferromagnetic, ductile metal, which is very similar to iron, but is much rarer than this. It is used for magnets and for many different alloys. Cobalt blue(CoAl<sub>2</sub>O<sub>4</sub>), is one of the most important blue colorants for gas and ceramics. Also cobalt is a part of the vitamin B12 and therefore is needed in small amounts in our food.",
    general_properties: {
      name: "Cobalt",
      atomic_number: 27,
      group: 9,
      period: 4,
      block: "D",
      cas_number: "7440-48-4",
      cid_number: "104730",
      symbol: "Co",
      allotropes: [
        ["Alpha Cobalt", "https://pubs.acs.org/doi/10.1021/ja0523338"],
        ["Beta Cobalt", "https://pubs.acs.org/doi/10.1021/ja0523338"],
      ],
    },
    particles: {
      electrons: 27,
      protons: 27,
      neutrons: 32,
    },
    overview: {
      latin_name: "Cobaltum",
      discovery: 1735,
      discoverer: [["Georg Brandt", "Georg Brandt"]],
    },
    atomic_properties: {
      atomic_weight: 58.933194,
      oxidation_states: [-1, 2, 3],
      electron_shell_configuration: "K2 L8 M15 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>7</sup>",
      atomic_radius: 152,
      covalent_radius: 126,
    },
    thermodynamic_properties: {
      boiling_point: "2927℃",
      melting_point: "1495℃",
      phase: "Solid",
      fusion_heat: 16.2,
      specific_heat: 421,
      vaporization_heat: 375,
      thermal_expansion: "1.3•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "6.6•10<sup>-6</sup>",
      brinell_hardness: 700,
      bulk_modulus: 180,
      density: 8900,
      liquid_density: 7750,
      thermal_conductivity: 100,
      shear_modulus: 75,
      poisson_ratio: 0.31,
      young_modulus: 209,
      mohs_hardness: 5,
      sound_speed: 4720,
      vickers_hardness: 1043,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.88,
      electron_affinity: 63.7,
      ionization_energy: 760.4,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 37.2,
      neutron_mass_absorption: 0.021,
      quantum_numbers: "<sup>4</sup>F<sub>9/2</sub>",
      isotopes: [
        47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60.61, 62, 63, 64,
        65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
      ],
      stable: [59],
    },
    prevalence: {
      universe: "0.0003%",
      sun: "0.0004%",
      earth_crust: "0.003%",
      ocean: "8•10<sup>-9</sup>%",
      human: "2•10<sup>-6</sup>%",
      meteorites: "0.06%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Ferromagnetic",
      electrical_conductivity: "1.7•10<sup>7</sup>",
      resistivity: "6•10<sup>-8</sup>",
      curie_point: 1394,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Cobalt",
      youtube: "https://youtu.be/yvWKeYOdWbo",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [250.71, 250.71, 406.95],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "GF8750000",
    },
  },
  {
    id: 28,
    neighbour: ["Cobalt", "Copper"],
    description:
      "Nickel is a quite inert metal, which often used for plating, but frequently causes allergic reactions on the skins of many people. Its main use is in alloys, especially in steel. Nickel is ferromagnetic and together with iron, forms the innercore of the earth, which is a big magnet. The rather rare nickel 62 is the most stable isotope, the one with the highest binding energy.",
    general_properties: {
      name: "Nickel",
      atomic_number: 28,
      group: 10,
      period: 4,
      block: "D",
      cas_number: "7440-02-0",
      cid_number: "935",
      symbol: "Ni",
    },
    particles: {
      electrons: 28,
      protons: 28,
      neutrons: 31,
    },
    overview: {
      latin_name: "Niccolum",
      discovery: 1751,
      discoverer: [["Axel Fredrik Cronstedt", "Axel_Fredrik_Cronstedt"]],
    },
    atomic_properties: {
      atomic_weight: 58.6934,
      oxidation_states: [-1, 2, 3],
      electron_shell_configuration: "K2 L8 M16 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>8</sup>",
      atomic_radius: 149,
      covalent_radius: 124,
      van_der_walls_radius: 163,
    },
    thermodynamic_properties: {
      boiling_point: "2913℃",
      melting_point: "1455℃",
      phase: "Solid",
      fusion_heat: 17.2,
      specific_heat: 445,
      vaporization_heat: 378,
      thermal_expansion: "1.34•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "6.589•10<sup>-6</sup>",
      brinell_hardness: 700,
      bulk_modulus: 180,
      density: 8908,
      liquid_density: 7810,
      thermal_conductivity: 91,
      shear_modulus: 76,
      poisson_ratio: 0.31,
      young_modulus: 200,
      mohs_hardness: 4,
      sound_speed: 4970,
      vickers_hardness: 638,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1.91,
      electron_affinity: 112,
      ionization_energy: 737.1,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 4.5,
      neutron_mass_absorption: 0.0026,
      quantum_numbers: "<sup>3</sup>F<sub>4</sub>",
      isotopes: [
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
      ],
      stable: [58, 60, 61, 62, 64],
    },
    prevalence: {
      universe: "0.01%",
      sun: "0.01%",
      earth_crust: "0.01%",
      ocean: "2•10<sup>-7</sup>%",
      human: "0.00001%",
      meteorites: "1.30%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Ferromagnetic",
      electrical_conductivity: "1.4•10<sup>7</sup>",
      resistivity: "7•10<sup>-8</sup>",
      curie_point: 631,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Nickel",
      youtube: "https://youtu.be/AUmoaZn9bek",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [352.4, 352.4, 352.4],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "QR5950000",
    },
  },
  {
    id: 29,
    neighbour: ["Nickel", "Zinc"],
    description:
      "Copper is an abundant and quite inert metal with a golden-red color, which is useful for a lot of different things. It is known since ancient times and was the first metal used by humans. Together with tin, it is main ingridient of bronze. In an alloy together with zinc, it forms brass. Copper has a very high electrical Conductivity, so it is used for most electrical lines(copper wire).",
    general_properties: {
      name: "Copper",
      atomic_number: 29,
      group: 11,
      period: 4,
      block: "D",
      cas_number: "7440-50-8",
      cid_number: "23978",
      symbol: "Cu",
    },
    particles: {
      electrons: 29,
      protons: 29,
      neutrons: 35,
    },
    overview: {
      latin_name: "Cuprum",
      discovery: -8000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 63.546,
      oxidation_states: [1, 2],
      electron_shell_configuration: "K2 L8 M18 N1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>1</sup> 3d<sup>10</sup>",
      atomic_radius: 145,
      covalent_radius: 132,
      van_der_walls_radius: 140,
    },
    thermodynamic_properties: {
      boiling_point: "2562℃",
      melting_point: "1084.62℃",
      phase: "Solid",
      fusion_heat: 13.1,
      specific_heat: 384.4,
      vaporization_heat: 300,
      thermal_expansion: "1.65•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Copper",
      molar_volume: "7.092•10<sup>-6</sup>",
      brinell_hardness: 874,
      bulk_modulus: 140,
      density: 8960,
      liquid_density: 8020,
      thermal_conductivity: 80,
      shear_modulus: 48,
      poisson_ratio: 0.34,
      young_modulus: 130,
      mohs_hardness: 3,
      sound_speed: 3570,
      vickers_hardness: 369,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1.9,
      electron_affinity: 118.4,
      ionization_energy: 745.5,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 3.78,
      neutron_mass_absorption: 0.0021,
      quantum_numbers: "<sup>2</sup>S<sub>1/2</sub>",
      isotopes: [
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
        70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
      ],
      stable: [63, 65],
    },
    prevalence: {
      universe: "6•10<sup>-6</sup>%",
      sun: "0.0001%",
      ocean: "3•10<sup>-7</sup>%",
      earth_crust: "0.01%",
      human: "0.00010%",
      meteorites: "0.01%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "5.9•10<sup>7</sup>",
      resistivity: "1.7•10<sup>-8</sup>",
      volume_magnetic_suspectibility: "-9.63•10<sup>-6</sup>",
      mass_magnetic_suspectibility: "-1.08•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-6.86•10<sup>-11</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Copper",
      youtube: "https://youtu.be/fyUWYpWkwIw",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [361.49, 361.49, 361.49],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "GL5325000",
      nfpa_label: "/Cu.png",
    },
  },
  {
    id: 30,
    neighbour: ["Copper", "Galium"],
    description:
      "Zinc is a bluish silvery, brittle and hard metal, with which one often comes across. It is rather ignoble but in air quickly forms an enduring protective layer. Therefore it is used a lot as corrosion prevention. Many objects made of iron, which shallbe weatherproof, are zinc-plated. This is also, because zinc is a quite cheap material. Brass, one of the common alloys, is made of copper and zinc.",
    general_properties: {
      name: "Zinc",
      atomic_number: 30,
      group: 12,
      period: 4,
      block: "D",
      cas_number: "7440-66-6",
      cid_number: "23994",
      symbol: "Zn",
    },
    particles: {
      electrons: 30,
      protons: 30,
      neutrons: 35,
    },
    overview: {
      latin_name: "Zincum",
      discovery: 1500,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 65.38,
      oxidation_states: [2],
      electron_shell_configuration: "K2 L8 M18 N2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup>",
      atomic_radius: 142,
      covalent_radius: 122,
      van_der_walls_radius: 139,
    },
    thermodynamic_properties: {
      boiling_point: "907℃",
      melting_point: "419.53℃",
      phase: "Solid",
      fusion_heat: 7.35,
      specific_heat: 388,
      vaporization_heat: 119,
      thermal_expansion: "3.02•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Slate Gray",
      molar_volume: "9.16•10<sup>-6</sup>",
      brinell_hardness: 412,
      bulk_modulus: 70,
      density: 7140,
      liquid_density: 6570,
      thermal_conductivity: 120,
      shear_modulus: 43,
      poisson_ratio: 0.25,
      young_modulus: 108,
      mohs_hardness: 2.5,
      sound_speed: 3700,
      refrective_index: 1.00205,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1.65,
      ionization_energy: 906.4,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 1.1,
      neutron_mass_absorption: 0.00055,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70.71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
      ],
      stable: [64, 66, 67, 68, 70],
    },
    prevalence: {
      universe: "6•10<sup>-6</sup>%",
      sun: "0.0001%",
      ocean: "3•10<sup>-7</sup>%",
      earth_crust: "0.01%",
      human: "0.00010%",
      meteorites: "0.01%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "1.7•10<sup>7</sup>",
      resistivity: "5.9•10<sup>-8</sup>",
      volume_magnetic_suspectibility: "-1.58•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-2.21•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-1.45•10<sup>-10</sup>",
      superconducting_point: 0.85,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Zinc",
      youtube: "https://youtu.be/ju6gGLxq99k",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [266.49, 266.49, 494.68],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.3,
      dot_number: 1436,
      rtecs_number: "ZG8600000",
    },
  },
  {
    id: 31,
    neighbour: ["Zinc", "Germanium"],
    description:
      "Galium is a soft, silvery metal, which is increasingly used in high tech industry. Notable here is gallium arsenide, an important semiconductor for special applications. Pure Gallium already melts at 30℃(86℉). It is relatively safe to handle, but eye contact and longer skin contact should be avoided. Solid gallium, fresh and after some time(2 months) at room temperature. The galium spiral melted a bit and merged with another piece, which was stored in the same box.",
    general_properties: {
      name: "Galium",
      atomic_number: 31,
      group: 13,
      period: 4,
      block: "P",
      cas_number: "7440-55-3",
      cid_number: "5360835",
      symbol: "Ga",
    },
    particles: {
      electrons: 29,
      protons: 29,
      neutrons: 35,
    },
    overview: {
      latin_name: "Gallium",
      discovery: 1875,
      discoverer: [
        ["Paul-Émile Lecoq de Boisbaudran", "Paul-Émile_Lecoq_de_Boisbaudran"],
      ],
    },
    atomic_properties: {
      atomic_weight: 69.723,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N3",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>1</sup>",
      atomic_radius: 136,
      covalent_radius: 122,
      van_der_walls_radius: 187,
    },
    thermodynamic_properties: {
      boiling_point: "2204℃",
      melting_point: "29.76℃",
      phase: "Liquid",
      fusion_heat: 5.59,
      specific_heat: 371,
      vaporization_heat: 256,
      thermal_expansion: "2•10<sup>-4</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.181•10<sup>-5</sup>",
      brinell_hardness: 60,
      density: 5904,
      liquid_density: 6095,
      thermal_conductivity: 29,
      mohs_hardness: 1.5,
      sound_speed: 2740,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.81,
      electron_affinity: 28.9,
      ionization_energy: 578.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.9,
      neutron_mass_absorption: 0.0015,
      quantum_numbers: "<sup>2</sup>P<sub>1/2</sub>",
      isotopes: [
        56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
      ],
      stable: [69, 71],
    },
    prevalence: {
      universe: "10<sup>-6</sup>%",
      sun: "4•10<sup>-6</sup>%",
      ocean: "3•10<sup>-9</sup>%",
      earth_crust: "0.0019%",
      meteorites: "0.00076%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "7.1•10<sup>6</sup>",
      resistivity: "1.4•10<sup>-7</sup>",
      volume_magnetic_suspectibility: "-1.77•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-3•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-2.09•10<sup>-10</sup>",
      superconducting_point: 1.083,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Galium",
      youtube: "https://youtu.be/N6ccRvKKwZQ",
    },
    atom_structure: {
      crystal_structure: "Base Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [451.97, 766.33, 452.6],
      space_group_name: "Cmca",
      space_group_number: 64,
    },
    health_safety: {
      Hazard_class: 8,
      dot_number: 1803,
      rtecs_number: "LW8600000",
      nfpa_label: "/Ga.png",
    },
  },
  {
    id: 32,
    neighbour: ["Galium", "Arsenic"],
    description:
      "Germanium is a shiny metalloid and a semiconductor. The latter makes it an important material in electronics and solar technology. Germanium is corrosion-resistant, very brittle and slightly toxic, it doesn't have biological functions. Sometimes organic germanium compounds are sold as obscure miracle cures. These have no medical benefit at all and rather noxious.",
    general_properties: {
      name: "Germanium",
      atomic_number: 32,
      group: 14,
      period: 4,
      block: "P",
      cas_number: "7440-56-4",
      cid_number: "6326954",
      symbol: "Ge",
      allotropes: [
        [
          "Alpha Germanium",
          "https://onlinelibrary.wiley.com/doi/10.1002/adma.202006826",
        ],
        ["Beta Germanium", "https://en.wikipedia.org/wiki/Germanium"],
        ["Germanene", "https://en.wikipedia.org/wiki/Germanene"],
      ],
    },
    particles: {
      electrons: 32,
      protons: 32,
      neutrons: 41,
    },
    overview: {
      latin_name: "Germanium",
      discovery: 1886,
      discoverer: [["Clemens Alexander Winkler", "Clemens_Winkler"]],
    },
    atomic_properties: {
      atomic_weight: 72.63,
      oxidation_states: [2, 4],
      electron_shell_configuration: "K2 L8 M18 N4",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>2</sup>",
      atomic_radius: 125,
      covalent_radius: 120,
    },
    thermodynamic_properties: {
      boiling_point: "2820℃",
      melting_point: "938.3℃",
      phase: "Solid",
      fusion_heat: 31.8,
      specific_heat: 321.4,
      vaporization_heat: 334,
      thermal_expansion: "6•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "1.364•10<sup>-5</sup>",
      brinell_hardness: 7270,
      density: 5323,
      liquid_density: 5600,
      thermal_conductivity: 60,
      mohs_hardness: 6,
      sound_speed: 5400,
      vickers_hardness: 8010,
    },
    reactivity: {
      valence: 4,
      electronegativity: 2.01,
      electron_affinity: 119,
      ionization_energy: 762,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.2,
      neutron_mass_absorption: 0.0011,
      quantum_numbers: "<sup>3</sup>P<sub>0</sub>",
      isotopes: [
        58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
      ],
      stable: [70, 72, 73, 74],
    },
    prevalence: {
      sun: "2•10<sup>-5</sup>%",
      ocean: "6•10<sup>-9</sup>%",
      earth_crust: "0.00014%",
      meteorites: "0.00210%",
    },
    electromagnetic_properties: {
      electrical_type: "Semiconductor",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "2•10<sup>3</sup>",
      resistivity: "5•10<sup>-4</sup>",
      volume_magnetic_suspectibility: "-7.98•10<sup>-6</sup>",
      mass_magnetic_suspectibility: "-1.5•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-1.09•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Germanium",
      youtube: "https://youtu.be/2xylv_hijXw",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [565.75, 565.75, 565.75],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "LY5200000",
      nfpa_label: "/Ge.png",
    },
  },
  {
    id: 33,
    neighbour: ["Germanium", "Selenium"],
    description:
      "Arsenic, which is known since ancient times, sometimes natively occurs in nature as a grey metal. In its compounds it is one of the most toxic elements. Arsenic trioxide,As<sub>2</sub>O<sub>3</sub>, was for many centuries the most poison for assassination. But arsenic also was and is still used as a pharmaceutical and was the main ingredient in the first chemotherapy.",
    general_properties: {
      name: "Arsenic",
      atomic_number: 33,
      group: 15,
      period: 4,
      block: "P",
      cas_number: "7440-38-2",
      cid_number: "5359596",
      symbol: "As",
      allotropes: [
        [
          "Yellow Arsenic",
          "https://pubs.acs.org/doi/10.1021/acs.chemrev.8b00713",
        ],
        ["Gray Arsenic", "https://www.britannica.com/science/gray-arsenic"],
        [
          "Black Arsenic",
          "https://pubs.rsc.org/en/content/articlelanding/2020/nr/c9nr09627b",
        ],
      ],
    },
    particles: {
      electrons: 33,
      protons: 33,
      neutrons: 42,
    },
    overview: {
      latin_name: "Arsenicum",
      discovery: 1250,
      discoverer: [["Saint Albertus Magnus", "Saint_Albertus_Magnus"]],
    },
    atomic_properties: {
      atomic_weight: 74.921595,
      oxidation_states: [-3, 3, 5],
      electron_shell_configuration: "K2 L8 M18 N5",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>3</sup>",
      atomic_radius: 114,
      covalent_radius: 119,
      van_der_walls_radius: 185,
    },
    thermodynamic_properties: {
      boiling_point: "614℃",
      melting_point: "817℃",
      phase: "Solid",
      fusion_heat: 27.7,
      specific_heat: 328,
      vaporization_heat: 32.4,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.308•10<sup>-5</sup>",
      brinell_hardness: 1440,
      density: 5727,
      liquid_density: 5220,
      thermal_conductivity: 50,
      mohs_hardness: 3.5,
      bulk_modulus: 22,
      refrective_index: 1.001552,
      vickers_hardness: 1510,
      young_modulus: 8,
    },
    reactivity: {
      valence: 5,
      electronegativity: 2.18,
      electron_affinity: 78,
      ionization_energy: 947,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 4.3,
      neutron_mass_absorption: 0.002,
      quantum_numbers: "<sup>4</sup>S<sub>3/2</sub>",
      isotopes: [
        60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
        78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
      ],
      stable: [75],
    },
    prevalence: {
      universe: "8•10<sup>-7</sup>%",
      ocean: "2.3•10<sup>-7</sup>%",
      earth_crust: "0.00021%",
      meteorites: "0.00018%",
      human: "5•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      electrical_type: "Conductor",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "3.3•10<sup>6</sup>",
      resistivity: "3•10<sup>-7</sup>",
      volume_magnetic_suspectibility: "-2.23•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-3.9•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-2.92•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Arsenic",
      youtube: "https://youtu.be/yD8Vz-mFHgI",
    },
    atom_structure: {
      crystal_structure: "Simple Trigonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [375.98, 375.98, 1054.75],
      space_group_name: "R_ 3m",
      space_group_number: 166,
    },
    health_safety: {
      Hazard_class: 61,
      dot_number: 1558,
      rtecs_number: "CG0525000",
      nfpa_label: "/As.png",
    },
  },
  {
    id: 34,
    neighbour: ["Arsenic", "Bromine"],
    description:
      "Selenium is a metalloid, which has more nonmetallic than metallic properties. Chemically it resembles sulfur, but is less reactive than this. Nonetheless it very rarely occurs in nature in its purest form. Every life form on earth needs selenium in small amounts for different proteins and amino acids. However, if the dose is too high, it quickly becomes poisonous. Hydrogen Selenide and many other selenium compounds smell terrible, worsethan the accordant sulfur compounds.",
    general_properties: {
      name: "Selenium",
      atomic_number: 34,
      group: 16,
      period: 4,
      block: "P",
      cas_number: "74782-49-2",
      cid_number: "6326970",
      symbol: "Se",
      allotropes: [
        ["Red Selenium", "https://pubs.acs.org/doi/10.1021/jacs.3c05981"],
        [
          "Gray Selenium",
          "https://pubs.acs.org/doi/10.1021/acs.inorgchem.2c04094",
        ],
        ["Black Selenium", "https://en.wikipedia.org/wiki/Selenium"],
        [
          "Monoclinic Selenium",
          "https://pubs.rsc.org/en/content/articlelanding/1980/dt/dt9800000624",
        ],
      ],
    },
    particles: {
      electrons: 34,
      protons: 34,
      neutrons: 45,
    },
    overview: {
      latin_name: "Selenium",
      discovery: 1250,
      discoverer: [["Jöns Jacob Berzelius", "Jöns_Jacob_Berzelius"]],
    },
    atomic_properties: {
      atomic_weight: 78.971,
      oxidation_states: [-2, 2, 4, 6],
      electron_shell_configuration: "K2 L8 M18 N6",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>4</sup>",
      atomic_radius: 103,
      covalent_radius: 120,
      van_der_walls_radius: 190,
    },
    thermodynamic_properties: {
      boiling_point: "685℃",
      melting_point: "221℃",
      phase: "Solid",
      fusion_heat: 5.4,
      specific_heat: 321.2,
      vaporization_heat: 26,
    },
    material_properties: {
      color: "Gray",
      molar_volume: "1.639•10<sup>-5</sup>",
      brinell_hardness: 736,
      density: 4819,
      liquid_density: 3990,
      thermal_conductivity: 0.52,
      mohs_hardness: 2,
      bulk_modulus: 8.3,
      refrective_index: 1.000895,
      sound_speed: 3350,
      young_modulus: 10,
      poisson_ratio: 0.33,
      shear_modulus: 3.7,
    },
    reactivity: {
      valence: 6,
      electronegativity: 2.55,
      electron_affinity: 195,
      ionization_energy: 941,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 11.7,
      neutron_mass_absorption: 0.0056,
      quantum_numbers: "<sup>3</sup>P<sub>2</sub>",
      isotopes: [
        65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
      ],
      stable: [74, 76, 77, 78, 80],
    },
    prevalence: {
      universe: "3•10<sup>-6</sup>%",
      ocean: "4.5•10<sup>-8</sup>%",
      earth_crust: "5•10<sup>-6</sup>%",
      meteorites: "0.00130%",
      human: "5•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      volume_magnetic_suspectibility: "-1.93•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-4•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-3.16•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Selenium",
      youtube: "https://youtu.be/IHrUtKjcAFE",
    },
    atom_structure: {
      crystal_structure: "Simple Monoclinic",
      lattice_angle: [90, 1.58493, 90],
      lattice_constant: [905.4, 908.3, 1160.1],
      space_group_name: "P12<sub>1</sub>/c1",
      space_group_number: 14,
    },
    health_safety: {
      Hazard_class: 6.1,
      dot_number: 2658,
      rtecs_number: "VS7700000",
    },
  },
  {
    id: 35,
    neighbour: ["Selenium", "Krypton"],
    description:
      "Elementl bromine is very reactive and thus does not occur free in nature, but in colourless soluble crystalline mineral halide salts, analogous to table salt. While it is rather rare in the Earth's crust, the high solubility of the bromide ion(Br<sup>-</sup>) has caused its accumulation in the oceans.",
    general_properties: {
      name: "Bromine",
      atomic_number: 35,
      group: 17,
      period: 4,
      block: "P",
      cas_number: "7726-95-6",
      cid_number: "24408",
      symbol: "Br",
    },
    particles: {
      electrons: 35,
      protons: 35,
      neutrons: 45,
    },
    overview: {
      latin_name: "Bromum",
      discovery: 1826,
      discoverer: [
        ["Carl Jacob Löwig", "Carl_Jacob_Löwig"],
        ["Antonie Jérôme Balard", "Antonie_Jérôme_Balard"],
      ],
    },
    atomic_properties: {
      atomic_weight: 79.904,
      oxidation_states: [-1, 1, 3, 5, 7],
      electron_shell_configuration: "K2 L8 M18 N7",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>5</sup>",
      atomic_radius: 94,
      covalent_radius: 120,
      van_der_walls_radius: 185,
    },
    thermodynamic_properties: {
      boiling_point: "59℃",
      melting_point: "-7.3℃",
      phase: "Liquid",
      fusion_heat: 5.8,
      specific_heat: 947.3,
      vaporization_heat: 14.8,
    },
    material_properties: {
      color: "Red",
      molar_volume: "2.561•10<sup>-5</sup>",
      density: 3120,
      liquid_density: 3120,
      thermal_conductivity: 0.12,
      bulk_modulus: 1.9,
      refrective_index: 1.001132,
    },
    reactivity: {
      valence: 1,
      electronegativity: 2.96,
      electron_affinity: 324.6,
      ionization_energy: 1139.9,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 6.8,
      neutron_mass_absorption: 0.002,
      quantum_numbers: "<sup>2</sup>P<sub>3/2</sub>",
      isotopes: [
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
      ],
      stable: [79, 81],
    },
    prevalence: {
      universe: "7•10<sup>-7</sup>%",
      ocean: "0.01%",
      earth_crust: "0.0003%",
      meteorites: "0.00012%",
    },
    electromagnetic_properties: {
      electrical_type: "Insulator",
      magnetic_type: "Diamagnetic",
      electrical_conductivity: "10<sup>-10</sup>",
      resistivity: "10<sup>10</sup>",
      volume_magnetic_suspectibility: "-1.53•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-4.9•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-7.83•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Bromine",
      youtube: "https://youtu.be/1CtnJtYcm_M",
    },
    atom_structure: {
      crystal_structure: "Base Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [672.65, 464.51, 870.23],
      space_group_name: "Cmca",
      space_group_number: 64,
    },
    health_safety: {
      Hazard_class: 8,
      dot_number: 1744,
      rtecs_number: "EF9100000",
      nfpa_label: "/Br.png",
    },
  },
  {
    id: 36,
    neighbour: ["Bromine", "Rubidium"],
    description:
      "It is arelatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays. Within the cores of stars,beryllium is depleted as it is fused into heavier elements. It is a divalent element which occurs naturally only in combination with other elements in minerals.",
    general_properties: {
      name: "Krypton",
      atomic_number: 36,
      group: 18,
      period: 4,
      block: "P",
      cas_number: "7439-90-9",
      cid_number: "5416",
      symbol: "Kr",
    },
    particles: {
      electrons: 36,
      protons: 36,
      neutrons: 48,
    },
    overview: {
      latin_name: "Krypton",
      discovery: 1898,
      discoverer: [
        ["Sir William Ramsay", "William_Ramsay"],
        ["Morris William Travers", "Morris_Travers"],
      ],
    },
    atomic_properties: {
      atomic_weight: 83.798,
      oxidation_states: [0, 2, 4],
      electron_shell_configuration: "K2 L8 M18 N8",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup>",
      gas_atom_multiplicities: 1,
      atomic_radius: 88,
      covalent_radius: 116,
      van_der_walls_radius: 202,
    },
    thermodynamic_properties: {
      boiling_point: "-153.22℃",
      melting_point: "-157.36℃",
      phase: "Gas",
      fusion_heat: 1.64,
      specific_heat: 248.05,
      vaporization_heat: 9.02,
      adiabatic_index: 1.67,
    },
    material_properties: {
      color: "Colorless",
      molar_volume: "2.23•10<sup>-2</sup>",
      density: 3.75,
      thermal_conductivity: 0.00943,
      refrective_index: 1.000427,
      sound_speed: 1120,
    },
    reactivity: {
      valence: 2,
      electronegativity: 3,
      ionization_energy: 1350.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 25,
      neutron_mass_absorption: 0.013,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
        87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
      ],
      stable: [78, 80, 82, 83, 84, 86],
    },
    prevalence: {
      universe: "4•10<sup>-6</sup>%",
      ocean: "2.1•10<sup>-8</sup>%",
      earth_crust: "1.5•10<sup>-8</sup>%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      volume_magnetic_suspectibility: "-1.65•10<sup>-8</sup>",
      mass_magnetic_suspectibility: "-4.4•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-3.69•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Krypton",
      youtube: "https://youtu.be/il4OOY7Zseg",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [570.6, 570.6, 570.6],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 2.2,
      dot_number: 1970,
      rtecs_number: "OC6772500",
    },
  },
];
