import ElementDetailsProps from "@/types/ElementTypes";

export const RowFiveElem: ElementDetailsProps[] = [
  {
    id: 37,
    neighbour: ["Krypton", "Strontium"],
    description:
      "Rubidium is silvery in color and slightly less reactive than cesium, but chemically very similar to this. In nature, it only occurs in compounds. It can be found everywhere, but only in low concentrations. Rubidium is rarely used in chemistry, but has a certain role for physical research. With rubidium, extremely low temperature below millikelvin can be reached and the first Bose-Einstein condensate was made using rubidium.",
    general_properties: {
      name: "Rubidium",
      atomic_number: 37,
      group: 1,
      period: 5,
      block: "S",
      cas_number: "7440-17-7",
      cid_number: "5357696",
      symbol: "Rb",
    },
    particles: {
      electrons: 37,
      protons: 37,
      neutrons: 48,
    },
    overview: {
      latin_name: "Rubidium",
      discovery: 1861,
      discoverer: [
        ["Gustav Kirchhoff", "Gustav_Kirchhoff"],
        ["Robert Wilhelm Bunsen", "Robert_Bunsen"],
      ],
    },
    atomic_properties: {
      atomic_weight: 85.4678,
      oxidation_states: [1],
      electron_shell_configuration: "K2 L8 M18 N8 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup>",
      atomic_radius: 265,
      covalent_radius: 220,
    },
    thermodynamic_properties: {
      boiling_point: "688℃",
      melting_point: "39.31℃",
      phase: "Solid",
      fusion_heat: 2.19,
      specific_heat: 364,
      vaporization_heat: 72,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "5.579•10<sup>-5</sup>",
      density: 1532,
      liquid_density: 1460,
      thermal_conductivity: 58,
      sound_speed: 1300,
      young_modulus: 2.4,
      mohs_hardness: 0.3,
      bulk_modulus: 2.5,
      brinell_hardness: 0.216,
    },
    reactivity: {
      valence: 1,
      electronegativity: 0.82,
      ionization_energy: 403,
      electron_affinity: 46.9,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.38,
      neutron_mass_absorption: 0.0003,
      quantum_numbers: "<sup>2</sup>S<sub>1/2</sub>",
      isotopes: [
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
        89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102,
      ],
      stable: [85],
    },
    prevalence: {
      universe: "10<sup>-6</sup>%",
      sun: "3•10<sup>-6</sup>%",
      ocean: "0.000012%",
      human: "0.00046%",
      meteorites: "0.00032%",
      earth_crust: "0.01%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-1.65•10<sup>-8</sup>",
      mass_magnetic_suspectibility: "-4.4•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-3.69•10<sup>-10</sup>",
      electrical_conductivity: "8.3•10<sup>6</sup>",
      resistivity: "1.2•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Rubidium",
      youtube: "https://youtu.be/g0P-A23m3lE",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [558.5, 558.5, 558.5],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.3,
      dot_number: 1423,
      rtecs_number: "VL8500000",
    },
  },
  {
    id: 38,
    neighbour: ["Rubidium", "Yttrium"],
    description:
      "Strontium is very similar to calcium, but it is more heavy and reactive. For this metal and its compounds,only few and special applications exist. Strontium salts are used to make red fireworks. Strontium is notorious for the radioactive <sup>90</sup>Sr, which is produced in neuclear power plants as well as in atomic explosions like that in Chernobyl and from atomic bombs. This has a half life of 29 years. It is build into bones like calcium and there causes cancer.",
    general_properties: {
      name: "Strontium",
      atomic_number: 38,
      group: 2,
      period: 5,
      block: "S",
      cas_number: "7440-24-6",
      cid_number: "5359327",
      symbol: "Sr",
    },
    particles: {
      electrons: 38,
      protons: 38,
      neutrons: 50,
    },
    overview: {
      latin_name: "Strontium",
      discovery: 1790,
      discoverer: [
        ["Adair Crawford", "Adair_Crawford"],
        ["Humphry Davy", "Humpry_Davy"],
      ],
    },
    atomic_properties: {
      atomic_weight: 87.62,
      oxidation_states: [2],
      electron_shell_configuration: "K2 L8 M18 N8 O2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup>",
      atomic_radius: 219,
      covalent_radius: 195,
    },
    thermodynamic_properties: {
      boiling_point: "1382℃",
      melting_point: "777℃",
      phase: "Solid",
      fusion_heat: 8,
      specific_heat: 300,
      vaporization_heat: 137,
      thermal_expansion: "2.25•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "3.332•10<sup>-5</sup>",
      density: 2630,
      liquid_density: 2375,
      thermal_conductivity: 35,
      mohs_hardness: 1.5,
      poisson_ratio: 0.28,
      shear_modulus: 6.1,
    },
    reactivity: {
      valence: 2,
      electronegativity: 0.95,
      ionization_energy: 549.5,
      electron_affinity: 5.03,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 1.2,
      neutron_mass_absorption: 0.0005,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105,
      ],
      stable: [84, 86, 87, 88],
    },
    prevalence: {
      universe: "4•10<sup>-6</sup>%",
      sun: "5•10<sup>-6</sup>%",
      ocean: "0.000800%",
      human: "0.00046%",
      meteorites: "0.00086%",
      earth_crust: "0.04%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "3.47•10<sup>-6</sup>",
      mass_magnetic_suspectibility: "1.32•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "1.16•10<sup>-10</sup>",
      electrical_conductivity: "7.7•10<sup>6</sup>",
      resistivity: "1.3•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Strontium",
      youtube: "https://youtu.be/28guL5UQfOQ",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [608.49, 608.49, 608.49],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.2,
      dot_number: 1383,
    },
  },
  {
    id: 39,
    neighbour: ["Strontium", "Zirconium"],
    description:
      "Yttrium is a soft and reactive metal, which has many applications in high-tech industry. YAG, Yttrium Aluminium Garnet, is widely used as a host material in lasers. Pure Yttrium easily forms crystals, like those you can see here. The most important uses of Yttrium are LEDs and phosphors, particularly the red phosphors in television set catgode ray tude displays. Yttrium is also used in the production of electrodes, electrolytes, electronic filters, lasers, superconductors, various medical applications, and tracing various materials to enhance their properties.",
    general_properties: {
      name: "Yttrium",
      atomic_number: 39,
      group: 3,
      period: 5,
      block: "D",
      cas_number: "7440-65-5",
      cid_number: "23993",
      symbol: "Y",
    },
    particles: {
      electrons: 39,
      protons: 39,
      neutrons: 50,
    },
    overview: {
      latin_name: "Strontium",
      discovery: 1790,
      discoverer: [
        ["Adair Crawford", "Adair_Crawford"],
        ["Humphry Davy", "Humpry_Davy"],
      ],
    },
    atomic_properties: {
      atomic_weight: 88.90584,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N9 O2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>1</sup>",
      atomic_radius: 212,
      covalent_radius: 190,
    },
    thermodynamic_properties: {
      boiling_point: "3345℃",
      melting_point: "1526℃",
      phase: "Solid",
      fusion_heat: 11.4,
      specific_heat: 298,
      vaporization_heat: 380,
      thermal_expansion: "1.06•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.988•10<sup>-5</sup>",
      density: 4472,
      liquid_density: 4240,
      thermal_conductivity: 17,
      poisson_ratio: 0.24,
      shear_modulus: 26,
      sound_speed: 3300,
      brinell_hardness: 589,
      bulk_modulus: 41,
      young_modulus: 64,
    },
    reactivity: {
      valence: 3,
      electronegativity: 1.22,
      ionization_energy: 600,
      electron_affinity: 29.6,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 1.28,
      neutron_mass_absorption: 0.00059,
      quantum_numbers: "<sup>2</sup>D<sub>3/2</sub>",
      isotopes: [
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
        94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
      ],
      stable: [89],
    },
    prevalence: {
      universe: "7•10<sup>-7</sup>%",
      sun: "9.9•10<sup>-7</sup>%",
      ocean: "1.3•10<sup>-9</sup>%",
      meteorites: "0.0029%",
      earth_crust: "0.00019%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "2.978•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "6.66•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "5.921•10<sup>-9</sup>",
      electrical_conductivity: "1.8•10<sup>6</sup>",
      resistivity: "5.6•10<sup>-7</sup>",
      superconducting_point: 1.3,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Yttrium",
      youtube: "https://youtu.be/LGAmrFTr5e4",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [364.74, 364.74, 573.06],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "ZG2980000",
    },
  },
  {
    id: 40,
    neighbour: ["Yttrium", "Niobium"],
    description:
      "Zirconium is a hard, silvery Grey metal. It is quite reactive, but forms a protective oxide layer in air, which makes it corrosion-resistant. Above all, it is used for special alloys. From cubic zirconia, ZrO<sub>2</sub>, artificial gemstones can be made, which look very similar to diamonds.",
    general_properties: {
      name: "Zirconium",
      atomic_number: 40,
      group: 4,
      period: 5,
      block: "D",
      cas_number: "7440-67-7",
      cid_number: "23995",
      symbol: "Zr",
    },
    particles: {
      electrons: 40,
      protons: 40,
      neutrons: 51,
    },
    overview: {
      latin_name: "Zirconium",
      discovery: 1789,
      discoverer: [
        ["Martin Heinrich Klaproth", "Martin_Heinrich_Klaproth"],
        ["Humphry Davy", "Humpry_Davy"],
      ],
    },
    atomic_properties: {
      atomic_weight: 91.224,
      oxidation_states: [3, 4],
      electron_shell_configuration: "K2 L8 M18 N10 O2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>2</sup>",
      atomic_radius: 206,
      covalent_radius: 175,
    },
    thermodynamic_properties: {
      boiling_point: "4409℃",
      melting_point: "1855℃",
      phase: "Solid",
      fusion_heat: 21,
      specific_heat: 278,
      vaporization_heat: 580,
      thermal_expansion: "5.7•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.401•10<sup>-5</sup>",
      density: 6511,
      liquid_density: 5800,
      thermal_conductivity: 23,
      poisson_ratio: 0.34,
      shear_modulus: 33,
      sound_speed: 3800,
      brinell_hardness: 650,
      young_modulus: 68,
      vickers_hardness: 903,
      mohs_hardness: 5,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.33,
      ionization_energy: 604.1,
      electron_affinity: 41.1,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.184,
      neutron_mass_absorption: 0.00066,
      quantum_numbers: "<sup>3</sup>F<sub>2</sub>",
      isotopes: [
        78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
      ],
      stable: [90, 91, 92, 94],
    },
    prevalence: {
      universe: "5•10<sup>-6</sup>%",
      sun: "4•10<sup>-6</sup>%",
      ocean: "2.6•10<sup>-9</sup>%",
      human: "5•10<sup>-6</sup>%",
      meteorites: "0.01%",
      earth_crust: "0.00066%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "1.09•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "1.68•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "1.53•10<sup>-9</sup>",
      electrical_conductivity: "2.4•10<sup>6</sup>",
      resistivity: "4.2•10<sup>-7</sup>",
      superconducting_point: 0.61,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Zirconium",
      youtube: "https://youtu.be/yIBbrk56KwQ",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [323.2, 323.2, 514.7],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.2,
      dot_number: 2008,
    },
  },
  {
    id: 41,
    neighbour: ["Zirconium", "Molybdenum"],
    description:
      "Niobium is a rare, soft, grey metal, which, when exposed to air, quickly forms a protective oxide layer. It is not used widely, one application is as additive to superalloys, which have to withstand very high temperature. Furthermore, it is sometimes used as mint metal for special coinages, because it can be anodized to form a colored oxide layer. The thickness of the oxide layer determines its color.",
    general_properties: {
      name: "Niobium",
      atomic_number: 41,
      group: 5,
      period: 5,
      block: "D",
      cas_number: "7440-03-1",
      cid_number: "23936",
      symbol: "Nb",
    },
    particles: {
      electrons: 41,
      protons: 41,
      neutrons: 52,
    },
    overview: {
      latin_name: "Niobium",
      discovery: 1801,
      discoverer: [["Charles Hatchett", "Charles_Hatchett"]],
    },
    atomic_properties: {
      atomic_weight: 92.90637,
      oxidation_states: [-1, 3, 5],
      electron_shell_configuration: "K2 L8 M18 N12 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup> 4d<sup>4</sup>",
      atomic_radius: 198,
      covalent_radius: 164,
    },
    thermodynamic_properties: {
      boiling_point: "4744℃",
      melting_point: "2477℃",
      phase: "Solid",
      fusion_heat: 26.8,
      specific_heat: 265,
      vaporization_heat: 690,
      thermal_expansion: "7.3•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "1.084•10<sup>-5</sup>",
      density: 8570,
      thermal_conductivity: 54,
      poisson_ratio: 0.4,
      shear_modulus: 38,
      sound_speed: 3480,
      brinell_hardness: 736,
      bulk_modulus: 170,
      young_modulus: 105,
      mohs_hardness: 6,
      vickers_hardness: 1320,
    },
    reactivity: {
      valence: 5,
      electronegativity: 1.6,
      ionization_energy: 652.1,
      electron_affinity: 86.1,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 1.15,
      neutron_mass_absorption: 0.0004,
      quantum_numbers: "<sup>6</sup>D<sub>1/2</sub>",
      isotopes: [
        81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
        99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113,
      ],
      stable: [93],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "4•10<sup>-7</sup>%",
      ocean: "10<sup>-10</sup>%",
      meteorites: "0.0017%",
      earth_crust: "0.00002%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "2.37•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "2.76•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "2.56•10<sup>-9</sup>",
      electrical_conductivity: "6.7•10<sup>6</sup>",
      resistivity: "1.5•10<sup>-7</sup>",
      superconducting_point: 9.25,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Niobium",
      youtube: "https://youtu.be/K90HPbVZOQ4",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [330.04, 330.04, 330.04],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      rtecs_number: "QT9900000",
    },
  },
  {
    id: 42,
    neighbour: ["Niobium", "Technetium"],
    description:
      "Molybdenum is one of the most heavy elements of those essential to life. Most remarkable is the enzyme nitrogenase with molybdenum in its active center, which allows some bacteria to process nitrogen from the air. In elemental form, the hard, heavy and ductile metal is used for many special technical applications, like for the tempering of steel.",
    general_properties: {
      name: "Molybdenum",
      atomic_number: 42,
      group: 6,
      period: 5,
      block: "D",
      cas_number: "7439-98-7",
      cid_number: "23932",
      symbol: "Mo",
    },
    particles: {
      electrons: 42,
      protons: 42,
      neutrons: 54,
    },
    overview: {
      latin_name: "Molybdenum",
      discovery: 1781,
      discoverer: [["Peter Jacob Hjelm", "Peter_Jacob_Hjelm"]],
    },
    atomic_properties: {
      atomic_weight: 95.95,
      oxidation_states: [-2, 2, 3, 4, 5, 6],
      electron_shell_configuration: "K2 L8 M18 N13 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup> 4d<sup>5</sup>",
      atomic_radius: 190,
      covalent_radius: 154,
    },
    thermodynamic_properties: {
      boiling_point: "4639℃",
      melting_point: "2623℃",
      phase: "Solid",
      fusion_heat: 36,
      specific_heat: 251,
      vaporization_heat: 600,
      thermal_expansion: "4.8•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "9.33•10<sup>-6</sup>",
      density: 10280,
      liquid_density: 9330,
      thermal_conductivity: 139,
      poisson_ratio: 0.31,
      shear_modulus: 20,
      sound_speed: 6190,
      brinell_hardness: 1500,
      bulk_modulus: 230,
      young_modulus: 329,
      vickers_hardness: 1530,
      mohs_hardness: 5.5,
    },
    reactivity: {
      valence: 6,
      electronegativity: 2.16,
      ionization_energy: 684.3,
      electron_affinity: 71.9,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.6,
      neutron_mass_absorption: 0.0009,
      quantum_numbers: "<sup>7</sup>S<sub>3</sub>",
      isotopes: [
        83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115,
      ],
      stable: [92, 94, 95, 96, 97, 98],
    },
    prevalence: {
      universe: "5•10<sup>-7</sup>%",
      sun: "9•10<sup>-7</sup>%",
      ocean: "9.9•10<sup>-7</sup>%",
      human: "0.00001%",
      meteorites: "0.00011%",
      earth_crust: "0.00012%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "1.203•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "1.17•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "1.122•10<sup>-9</sup>",
      electrical_conductivity: "2•10<sup>7</sup>",
      resistivity: "5•10<sup>-8</sup>",
      superconducting_point: 0.915,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Molybdenum",
      youtube: "https://youtu.be/fuhZF0Dtevw",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [314.7, 314.7, 314.7],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "QA4680000",
    },
  },
  {
    id: 43,
    neighbour: ["Molybdenum", "Ruthenium"],
    description:
      "Technetium is the first element without stable isotopes. In earth's crust it exists due to natural uranium decay, on Earth's surface as consequence of neuclear explosions. The long-lived isotope <sup>98</sup>Tc has a half life of 4.3 million years, which makes technetium moderately good researchable. It is a silvery, hard, relatively noble metal with attributes similar to Rhenium.",
    general_properties: {
      name: "Technetium",
      atomic_number: 43,
      group: 7,
      period: 5,
      block: "D",
      cas_number: "7440-26-8",
      cid_number: "23957",
      symbol: "Tc",
    },
    particles: {
      electrons: 43,
      protons: 43,
      neutrons: 55,
    },
    overview: {
      latin_name: "Technetium",
      discovery: 1937,
      discoverer: [
        ["Carlo Perrier", "Carlo_Perrier"],
        ["Emilio Segrè", "Emilio_Segrè"],
      ],
    },
    atomic_properties: {
      atomic_weight: 98,
      oxidation_states: [-1, 4, 7],
      electron_shell_configuration: "K2 L8 M18 N13 O2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>5</sup>",
      atomic_radius: 183,
      covalent_radius: 147,
    },
    thermodynamic_properties: {
      boiling_point: "4265℃",
      melting_point: "2157℃",
      phase: "Solid",
      fusion_heat: 23,
      specific_heat: 63,
      vaporization_heat: 550,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.988•10<sup>-5</sup>",
      density: 4472,
      liquid_density: 4240,
      thermal_conductivity: 17,
      poisson_ratio: 0.24,
      shear_modulus: 26,
      sound_speed: 3300,
      brinell_hardness: 589,
      bulk_modulus: 41,
      young_modulus: 64,
    },
    reactivity: {
      valence: 7,
      electronegativity: 1.9,
      ionization_energy: 702,
      electron_affinity: 53,
    },
    neuclear_properties: {
      radioactive: "Yes",
      half_life: "6.7•10<sup>12</sup>",
      lifetime: "1.9•10<sup>14</sup>",
      neutron_cross_section: 22,
      quantum_numbers: "<sup>6</sup>S<sub>5/2</sub>",
      decay_mode: "Beta",
      isotopes: [
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
        102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118,
      ],
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "3.933•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "3.42•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "3.352•10<sup>-9</sup>",
      electrical_conductivity: "5•10<sup>6</sup>",
      resistivity: "2•10<sup>-7</sup>",
      superconducting_point: 7.8,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Technetium",
      youtube: "https://youtu.be/Hu42SH5iAps",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [273.5, 273.5, 438.8],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
  },
  {
    id: 44,
    neighbour: ["Technetium", "Rhodium"],
    description:
      "Ruthenium is the first of the platinum group metals. It is very hard and is commonly brittle and is commonly used in alloys and as a catalyst. like the osmium, its tetroxide is very toxic, but ruthenium is less reactive than osmium. Most ruthenium produced is used in wear-resistant electrical contacts and thick-film resistors. A minor application for ruthenium is in platinum alloys and as a chemistry catalyst.",
    general_properties: {
      name: "Ruthenium",
      atomic_number: 44,
      group: 8,
      period: 5,
      block: "D",
      cas_number: "7440-18-8",
      cid_number: "23950",
      symbol: "Ru",
    },
    particles: {
      electrons: 44,
      protons: 44,
      neutrons: 57,
    },
    overview: {
      latin_name: "Ruthenium",
      discovery: 1808,
      discoverer: [
        ["Gottfried Osann", "Gottfried_Osann"],
        ["Jędrzej Śniadecki", "Jędrzej_Śniadecki"],
        ["Karl Karlovich Klaus", "Karl_Karlovich_Klaus"],
      ],
    },
    atomic_properties: {
      atomic_weight: 101.07,
      oxidation_states: [-2, 2, 3, 4, 6, 8],
      electron_shell_configuration: "K2 L8 M18 N15 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup> 4d<sup>7</sup>",
      atomic_radius: 178,
      covalent_radius: 146,
    },
    thermodynamic_properties: {
      boiling_point: "4150℃",
      melting_point: "2334℃",
      phase: "Solid",
      fusion_heat: 25.7,
      specific_heat: 238,
      vaporization_heat: 580,
      thermal_expansion: "6.4•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "8.171•10<sup>-6</sup>",
      density: 12370,
      liquid_density: 10650,
      thermal_conductivity: 120,
      poisson_ratio: 0.3,
      shear_modulus: 173,
      sound_speed: 5970,
      brinell_hardness: 2160,
      bulk_modulus: 220,
      young_modulus: 447,
      vickers_hardness: 2300,
      mohs_hardness: 6.5,
    },
    reactivity: {
      valence: 6,
      electronegativity: 2.2,
      ionization_energy: 710.2,
      electron_affinity: 101.3,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2.6,
      neutron_mass_absorption: 0.0009,
      quantum_numbers: "<sup>5</sup>F<sub>5</sub>",
      isotopes: [
        87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120,
      ],
      stable: [96, 98, 99, 100, 101, 102, 104],
    },
    prevalence: {
      universe: "4•10<sup>-7</sup>%",
      sun: "5•10<sup>-7</sup>%",
      ocean: "7•10<sup>-11</sup>%",
      earth_crust: "10<sup>-7</sup>%",
      meteorites: "0.00008%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "6.7•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "5.42•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "5.48•10<sup>-10</sup>",
      electrical_conductivity: "1.4•10<sup>7</sup>",
      resistivity: "7.1•10<sup>-8</sup>",
      superconducting_point: 0.49,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Ruthenium",
      youtube: "https://youtu.be/xtY6BpT4DTY",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [270.59, 270.59, 428.15],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
    },
  },
  {
    id: 45,
    neighbour: ["Ruthenium", "Palladium"],
    description:
      "The platinum group metal rhodium is the rarest and most valueable stable metal on earth. it is needed in many chemical applications as a catalyst, like for example in the industrial production of acetic acid. Therefore rhodium is very expensive and its price fluctuates strongly. In catalytic converters, it reduces the amount of toxic metals that arises from the combustion. Rhodium is furthermore used for planting high grade mirror or jewellery. Rhodium is very hard ductile and noble.",
    general_properties: {
      name: "Rhodium",
      atomic_number: 45,
      group: 9,
      period: 5,
      block: "D",
      cas_number: "7440-16-6",
      cid_number: "23948",
      symbol: "Rh",
    },
    particles: {
      electrons: 45,
      protons: 45,
      neutrons: 58,
    },
    overview: {
      latin_name: "Rhodium",
      discovery: 1803,
      discoverer: [["William Hyde Wollaston", "William_Hyde_Wollaston"]],
    },
    atomic_properties: {
      atomic_weight: 102.9055,
      oxidation_states: [-2, 2, 3, 4],
      electron_shell_configuration: "K2 L8 M18 N16 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup> 4d<sup>8</sup>",
      atomic_radius: 173,
      covalent_radius: 142,
    },
    thermodynamic_properties: {
      boiling_point: "3695℃",
      melting_point: "1964℃",
      phase: "Solid",
      fusion_heat: 21.7,
      specific_heat: 240,
      vaporization_heat: 495,
      thermal_expansion: "8.2•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "8.2655•10<sup>-6</sup>",
      density: 12450,
      liquid_density: 10700,
      thermal_conductivity: 150,
      poisson_ratio: 0.26,
      shear_modulus: 150,
      sound_speed: 4700,
      brinell_hardness: 1100,
      bulk_modulus: 380,
      young_modulus: 275,
      vickers_hardness: 1246,
      mohs_hardness: 6,
    },
    reactivity: {
      valence: 6,
      electronegativity: 2.28,
      ionization_energy: 719.7,
      electron_affinity: 109.7,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 145,
      neutron_mass_absorption: 0.063,
      quantum_numbers: "<sup>4</sup>F<sub>9/2</sub>",
      isotopes: [
        89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120, 121, 122,
      ],
      stable: [103],
    },
    prevalence: {
      universe: "6•10<sup>-8</sup>%",
      sun: "2•10<sup>-7</sup>%",
      earth_crust: "7•10<sup>-8</sup>%",
      meteorites: "0.00002%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "1.693•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "1.36•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "1.4•10<sup>-9</sup>",
      electrical_conductivity: "2.3•10<sup>7</sup>",
      resistivity: "4.3•10<sup>-8</sup>",
      superconducting_point: 0.49,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Rhodium",
      youtube: "https://youtu.be/RcQVJ4lb8r0",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [380.34, 380.34, 380.34],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "VI9069000",
    },
  },
  {
    id: 46,
    neighbour: ["Rhodium", "Silver"],
    description:
      "He named it after the asteroid Pallas, which was itself named after epithet of the greek goddess Athena, acquired by her when she slew Pallas. Palladium, Platinum, Rhodium, Ruthenium, Iridium and Osmium form a group of elements referred to as the platinum group metal(PGMs). These have similar chemical properties, but palladium has the lowest melting point and is the least dense of them.",
    general_properties: {
      name: "Palladium",
      atomic_number: 46,
      group: 10,
      period: 5,
      block: "D",
      cas_number: "7440-05-3",
      cid_number: "23938",
      symbol: "Pd",
    },
    particles: {
      electrons: 46,
      protons: 46,
      neutrons: 60,
    },
    overview: {
      latin_name: "Palladium",
      discovery: 1803,
      discoverer: [["William Hyde Wollaston", "William_Hyde_Wollaston"]],
    },
    atomic_properties: {
      atomic_weight: 106.42,
      oxidation_states: [2, 4],
      electron_shell_configuration: "K2 L8 M18 N18",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 4d<sup>10</sup>",
      atomic_radius: 169,
      covalent_radius: 139,
      van_der_walls_radius: 163,
    },
    thermodynamic_properties: {
      boiling_point: "2963℃",
      melting_point: "1554.9℃",
      phase: "Solid",
      fusion_heat: 16.7,
      specific_heat: 240,
      vaporization_heat: 380,
      thermal_expansion: "1.18•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "8.851•10<sup>-6</sup>",
      density: 12023,
      liquid_density: 10380,
      thermal_conductivity: 72,
      poisson_ratio: 0.39,
      shear_modulus: 44,
      sound_speed: 3070,
      brinell_hardness: 37.3,
      bulk_modulus: 180,
      young_modulus: 121,
      vickers_hardness: 461,
      mohs_hardness: 4.75,
    },
    reactivity: {
      valence: 4,
      electronegativity: 2.2,
      ionization_energy: 804.4,
      electron_affinity: 53.7,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 6.9,
      neutron_mass_absorption: 0.0023,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106,
        107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124,
      ],
      stable: [102, 104, 105, 106, 108, 110],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "3•10<sup>-7</sup>%",
      earth_crust: "6.3•10<sup>-7</sup>%",
      meteorites: "0.00007%",
    },
    electromagnetic_properties: {
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "7.899•10<sup>-4</sup>",
      mass_magnetic_suspectibility: "6.57•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "6.992•10<sup>-9</sup>",
      electrical_conductivity: "10<sup>7</sup>",
      resistivity: "10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Palladium",
      youtube: "https://youtu.be/FC-OBl9Eiiw",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [389.07, 389.07, 389.07],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 4.2,
      dot_number: 3200,
      rtecs_number: "RT3480500",
    },
  },
  {
    id: 47,
    neighbour: ["Palladium", "Cadmium"],
    description:
      "Silver is the most abundent noble metal and is widely used for jewellwey, coins and for technical applications. It has the highest electric and thermic conductivity and the whitest color of all metals. Silver compounds, like silver bromide used for photographic films, as some of them are very photosensitive. It occurs in its purest form in nature, but rarely as nugget, like this shown here.",
    general_properties: {
      name: "Silver",
      atomic_number: 47,
      group: 11,
      period: 5,
      block: "D",
      cas_number: "7440-22-4",
      cid_number: "23954",
      symbol: "Ag",
    },
    particles: {
      electrons: 47,
      protons: 47,
      neutrons: 61,
    },
    overview: {
      latin_name: "Argentum",
      discovery: -3000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 107.8682,
      oxidation_states: [1, 2],
      electron_shell_configuration: "K2 L8 M18 N18 O1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>1</sup> 4d<sup>10</sup>",
      atomic_radius: 165,
      covalent_radius: 145,
      van_der_walls_radius: 172,
    },
    thermodynamic_properties: {
      boiling_point: "2162℃",
      melting_point: "961.78℃",
      phase: "Solid",
      fusion_heat: 11.3,
      specific_heat: 235,
      vaporization_heat: 255,
      thermal_expansion: "1.89•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "8.851•10<sup>-6</sup>",
      density: 10490,
      liquid_density: 9320,
      thermal_conductivity: 430,
      poisson_ratio: 0.37,
      shear_modulus: 30,
      sound_speed: 2600,
      brinell_hardness: 24.5,
      bulk_modulus: 100,
      young_modulus: 83,
      vickers_hardness: 251,
      mohs_hardness: 2.5,
    },
    reactivity: {
      valence: 1,
      electronegativity: 1.93,
      ionization_energy: 731,
      electron_affinity: 125.6,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 63.6,
      neutron_mass_absorption: 0.02,
      quantum_numbers: "<sup>2</sup>S<sub>1/2</sub>",
      isotopes: [
        93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
        109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122,
        123, 124, 125, 126, 127, 128, 129, 130,
      ],
      stable: [107, 109],
    },
    prevalence: {
      universe: "6•10<sup>-8</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "10<sup>-8</sup>%",
      earth_crust: "7.9•10<sup>-6</sup>%",
      meteorites: "0.00001%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-2.38•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-2.27•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-2.45•10<sup>-10</sup>",
      electrical_conductivity: "6.2•10<sup>7</sup>",
      resistivity: "1.6•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Silver",
      youtube: "https://youtu.be/v-L4lUrEUlI",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [408.53, 408.53, 408.53],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      rtecs_number: "VW3500000",
      nfpa_label: "/Ag.png",
    },
  },
  {
    id: 48,
    neighbour: ["Silver", "Indium"],
    description:
      "Cadmium is a bluish silvery, soft, ductile metal, which is a by-product in the production of zinc and other metals. It has a bad reputation, because it is in virtually every form of very toxic and harmfull to the environment. An important application are nickel-cadmium batteries, which, when defect, have to be disposed properly. Another one was cadmium sulfide, known as the pigment cadmium yellow.",
    general_properties: {
      name: "Cadmium",
      atomic_number: 48,
      group: 12,
      period: 5,
      block: "D",
      cas_number: "7440-43-9",
      cid_number: "23973",
      symbol: "Cd",
    },
    particles: {
      electrons: 48,
      protons: 48,
      neutrons: 64,
    },
    overview: {
      latin_name: "Cadmium",
      discovery: 1817,
      discoverer: [["Friedrich Stromeyer", "Friedrich_Stromeyer"]],
    },
    atomic_properties: {
      atomic_weight: 112.414,
      oxidation_states: [2],
      electron_shell_configuration: "K2 L8 M18 N18 O2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup>",
      atomic_radius: 161,
      covalent_radius: 144,
      van_der_walls_radius: 158,
    },
    thermodynamic_properties: {
      boiling_point: "767℃",
      melting_point: "321.07℃",
      phase: "Solid",
      fusion_heat: 6.3,
      specific_heat: 230,
      vaporization_heat: 100,
      thermal_expansion: "3.08•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.3•10<sup>-5</sup>",
      density: 8650,
      liquid_density: 7996,
      thermal_conductivity: 97,
      poisson_ratio: 0.3,
      shear_modulus: 19,
      sound_speed: 2310,
      brinell_hardness: 203,
      bulk_modulus: 42,
      young_modulus: 50,
      mohs_hardness: 2,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1.69,
      ionization_energy: 867.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2450,
      neutron_mass_absorption: 1.4,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
        110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
        124, 125, 126, 127, 128, 129, 130, 131, 132,
      ],
      stable: [106, 108, 110, 111, 112, 114],
    },
    prevalence: {
      universe: "2•10<sup>-7</sup>%",
      sun: "3•10<sup>-7</sup>%",
      earth_crust: "6.3•10<sup>-7</sup>%",
      meteorites: "0.00007%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-1.99•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-2.3•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-2.59•10<sup>-10</sup>",
      electrical_conductivity: "1.4•10<sup>7</sup>",
      resistivity: "7•10<sup>-8</sup>",
      superconducting_point: 0.517,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Cadmium",
      youtube: "https://youtu.be/yvWKeYOdWbo",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [297.94, 297.94, 561.86],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 6.1,
      dot_number: 2570,
      rtecs_number: "EU9800000",
      nfpa_label: "/Cd.png",
    },
  },
  {
    id: 49,
    neighbour: ["Cadmium", "Tin"],
    description:
      "Indium is a rare metal with a low melting point. It is very soft and can be cut with a lnife.Indium is much used in the industry. Indium tin oxide is transparent, but has a good electrical conductivity. Therefore it is used in nearly Every modern display device, which made indium a scarce material, that is in danger of running out.",
    general_properties: {
      name: "Indium",
      atomic_number: 49,
      group: 13,
      period: 5,
      block: "P",
      cas_number: "7440-74-6",
      cid_number: "5359967",
      symbol: "In",
    },
    particles: {
      electrons: 49,
      protons: 49,
      neutrons: 66,
    },
    overview: {
      latin_name: "Indium",
      discovery: 1863,
      discoverer: [
        ["Ferdinand Reich", "Ferdinand_Reich"],
        ["Hieronymus Theodor Richter", "Hieronymus_Theodor_Richter"],
      ],
    },
    atomic_properties: {
      atomic_weight: 114.818,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M18 N18 O3",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>1</sup>",
      atomic_radius: 156,
      covalent_radius: 142,
      van_der_walls_radius: 193,
    },
    thermodynamic_properties: {
      boiling_point: "2072℃",
      melting_point: "156.6℃",
      phase: "Solid",
      fusion_heat: 3.26,
      specific_heat: 233,
      vaporization_heat: 230,
      thermal_expansion: "3.21•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.571•10<sup>-5</sup>",
      density: 7310,
      liquid_density: 7020,
      thermal_conductivity: 82,
      sound_speed: 1215,
      brinell_hardness: 8.83,
      young_modulus: 11,
      mohs_hardness: 1.2,
    },
    reactivity: {
      valence: 2,
      electronegativity: 1.69,
      ionization_energy: 867.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 2450,
      neutron_mass_absorption: 0.06,
      quantum_numbers: "<sup>2</sup>P<sub>1/2</sub>",
      isotopes: [
        97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
      ],
      stable: [113],
    },
    prevalence: {
      universe: "3•10<sup>-8</sup>%",
      sun: "4•10<sup>-7</sup>%",
      ocean: "10<sup>-11</sup>%",
      earth_crust: "0.00002%",
      meteorites: "4.4•10<sup>-6</sup>%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-1.02•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-1.4•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-1.61•10<sup>-10</sup>",
      electrical_conductivity: "1.2•10<sup>7</sup>",
      resistivity: "8•10<sup>-8</sup>",
      superconducting_point: 3.41,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Indium",
      youtube: "https://youtu.be/mjiP5Q6g_aM",
    },
    atom_structure: {
      crystal_structure: "Centered Tetragonal",
      lattice_angle: [90, 90, 90],
      lattice_constant: [325.23, 325.23, 494.61],
      space_group_name: "I4/mmm",
      space_group_number: 139,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 3089,
      rtecs_number: "NL1050000",
    },
  },
  {
    id: 50,
    neighbour: ["Indium", "Antimony"],
    description:
      "Tin is a very common metal. It is soft and has low melting point, which makes it a very good workable material, that is used since ancient times. Bronze is usually an alloy of copper and tin. the common beta-tin can transform into powdery alpha-tin at low temperatures(below 13℃,57℉). This is known as tin pset, which destroys the affected item.",
    general_properties: {
      name: "Tin",
      atomic_number: 50,
      group: 14,
      period: 5,
      block: "P",
      cas_number: "7440-31-5",
      cid_number: "5352426",
      symbol: "Sn",
    },
    particles: {
      electrons: 50,
      protons: 50,
      neutrons: 69,
    },
    overview: {
      latin_name: "Stannum",
      discovery: -3000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 118.71,
      oxidation_states: [2, 4],
      electron_shell_configuration: "K2 L8 M18 N18 O4",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>2</sup>",
      atomic_radius: 145,
      covalent_radius: 139,
      van_der_walls_radius: 217,
    },
    thermodynamic_properties: {
      boiling_point: "2602℃",
      melting_point: "231.93℃",
      phase: "Solid",
      fusion_heat: 7,
      specific_heat: 217,
      vaporization_heat: 290,
      thermal_expansion: "2.2•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.624•10<sup>-5</sup>",
      density: 7310,
      liquid_density: 6990,
      thermal_conductivity: 67,
      sound_speed: 2500,
      brinell_hardness: 51,
      young_modulus: 50,
      mohs_hardness: 1.5,
      bulk_modulus: 58,
      poisson_ratio: 0.36,
      shear_modulus: 18,
    },
    reactivity: {
      valence: 4,
      electronegativity: 1.96,
      ionization_energy: 708.6,
      electron_affinity: 107.3,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.63,
      neutron_mass_absorption: 0.0002,
      quantum_numbers: "<sup>3</sup>P<sub>0</sub>",
      isotopes: [
        99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
      ],
      stable: [112, 114, 115, 116, 117, 118, 119, 120, 122, 124],
    },
    prevalence: {
      universe: "4•10<sup>-7</sup>%",
      sun: "9•10<sup>-7</sup>%",
      ocean: "9.9•10<sup>-10</sup>%",
      human: "0.00002%",
      earth_crust: "0.00022%",
      meteorites: "0.00012%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-2.27•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-3.1•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-3.68•10<sup>-10</sup>",
      electrical_conductivity: "9.1•10<sup>6</sup>",
      resistivity: "1.1•10<sup>-7</sup>",
      superconducting_point: 3.72,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Tin",
      youtube: "https://youtu.be/Q9zdt-rOB0Y",
    },
    atom_structure: {
      crystal_structure: "Centered Tetragonal",
      lattice_angle: [90, 90, 90],
      lattice_constant: [583.18, 583.18, 318.19],
      space_group_name: "I4<sub>1</sub>/amd",
      space_group_number: 141,
    },
    health_safety: {
      rtecs_number: "XP7320000",
    },
  },
  {
    id: 51,
    neighbour: ["Tin", "Tellurium"],
    description:
      "Antimony is a metalloid (or semi metal), which is rather metal than non-metal. Here its stable metallic modification is shown. In its nonmetallic form it is unstable. Antimony is important for semiconductors, but has been used for a long times as additive in alloys like bronze and in cosmetics. Nonetheless it is quite toxic and has effect similar to arsenic.",
    general_properties: {
      name: "Antimony",
      atomic_number: 51,
      group: 15,
      period: 5,
      block: "P",
      cas_number: "7440-36-0",
      cid_number: "5354495",
      symbol: "Sb",
      allotropes: [
        ["Blue-White Antimony", "https://www.britannica.com/science/antimony"],
        ["Yellow Antimony", "https://en.wikipedia.org/wiki/Naples_yellow"],
        ["Black Antimony", "https://simple.wikipedia.org/wiki/Antimony"],
        [
          "Explosive Antimony",
          "https://en.wikipedia.org/wiki/Explosive_antimony",
        ],
      ],
    },
    particles: {
      electrons: 51,
      protons: 51,
      neutrons: 71,
    },
    overview: {
      latin_name: "Stibium",
      discovery: -3000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 121.76,
      oxidation_states: [-3, 3, 5],
      electron_shell_configuration: "K2 L8 M18 N18 O5",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>3</sup>",
      atomic_radius: 133,
      covalent_radius: 139,
    },
    thermodynamic_properties: {
      boiling_point: "1587℃",
      melting_point: "630.63℃",
      phase: "Solid",
      fusion_heat: 19.7,
      specific_heat: 207,
      vaporization_heat: 68,
      thermal_expansion: "1.1•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.818•10<sup>-5</sup>",
      density: 6697,
      liquid_density: 6530,
      thermal_conductivity: 24,
      sound_speed: 3420,
      brinell_hardness: 294,
      young_modulus: 55,
      mohs_hardness: 3,
      bulk_modulus: 42,
      shear_modulus: 20,
    },
    reactivity: {
      valence: 5,
      electronegativity: 2.05,
      ionization_energy: 834,
      electron_affinity: 103.2,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 5.4,
      neutron_mass_absorption: 0.0016,
      quantum_numbers: "<sup>4</sup>S<sub>3/2</sub>",
      isotopes: [
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139,
      ],
      stable: [121, 123],
    },
    prevalence: {
      universe: "4•10<sup>-8</sup>%",
      sun: "10<sup>-7</sup>%",
      ocean: "2•10<sup>-8</sup>%",
      earth_crust: "0.00002%",
      meteorites: "0.00001%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      volume_magnetic_suspectibility: "-7.3•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-1.09•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "-1.327•10<sup>-9</sup>",
      electrical_conductivity: "2.5•10<sup>6</sup>",
      resistivity: "4•10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Antimony",
      youtube: "https://youtu.be/BBzUYptG1_o",
    },
    atom_structure: {
      crystal_structure: "Simple Trigonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [430.7, 430.7, 1127.3],
      space_group_name: "R_ 3m",
      space_group_number: 166,
    },
    health_safety: {
      rtecs_number: "CC4025000",
    },
  },
  {
    id: 52,
    neighbour: ["Antimony", "Iodine"],
    description:
      "The semimetal tellurium is chemically similar to selenium. It is more metallic and somewhat less toxic than this, but its compounds smell even worse. Tellurium probably has no biological role and has only very few, special applications. It can form nice crystalls and somehow natively occurs in nature, however it is very rare. Tellurium is the element that most easily forms compound with gold, therefore it sometimes accures as waste at the extraction of gold.",
    general_properties: {
      name: "Tellurium",
      atomic_number: 52,
      group: 16,
      period: 5,
      block: "P",
      cas_number: "13494-80-9",
      cid_number: "6327182",
      symbol: "Te",
      allotropes: [
        [
          "Amorohous Tellurium",
          "https://link.springer.com/article/10.1007/BF02354800",
        ],
        [
          "Crystalline Tellurium",
          "https://pubs.rsc.org/en/content/articlelanding/2004/jm/b4050",
        ],
      ],
    },
    particles: {
      electrons: 52,
      protons: 52,
      neutrons: 76,
    },
    overview: {
      latin_name: "Stannum",
      discovery: -3000,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 127.6,
      oxidation_states: [-2, 2, 4, 6],
      electron_shell_configuration: "K2 L8 M18 N18 O6",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>4</sup>",
      atomic_radius: 123,
      covalent_radius: 138,
      van_der_walls_radius: 206,
    },
    thermodynamic_properties: {
      boiling_point: "988℃",
      melting_point: "449.51℃",
      phase: "Solid",
      fusion_heat: 17.5,
      specific_heat: 201,
      vaporization_heat: 48,
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.045•10<sup>-5</sup>",
      density: 6240,
      liquid_density: 5700,
      thermal_conductivity: 3,
      sound_speed: 2610,
      brinell_hardness: 180,
      young_modulus: 43,
      mohs_hardness: 2.25,
      bulk_modulus: 65,
      shear_modulus: 16,
      refrective_index: 1.000991,
    },
    reactivity: {
      valence: 4,
      electronegativity: 2.1,
      ionization_energy: 869.3,
      electron_affinity: 190.2,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 5.4,
      neutron_mass_absorption: 0.0013,
      quantum_numbers: "<sup>3</sup>P<sub>2</sub>",
      isotopes: [
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
      ],
      stable: [120, 122, 124, 125, 126],
    },
    prevalence: {
      universe: "9•10<sup>-7</sup>%",
      earth_crust: "10<sup>-7</sup>%",
      meteorites: "0.00021%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Semiconductor",
      volume_magnetic_suspectibility: "-2.43•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-3.9•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-4.98•10<sup>-10</sup>",
      electrical_conductivity: "10<sup>4</sup>",
      resistivity: "10<sup>-4</sup>",
      superconducting_point: 3.72,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Tellurium",
      youtube: "https://youtu.be/HGsFcbXd1hA",
    },
    atom_structure: {
      crystal_structure: "Simple Trigonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [445.72, 445.72, 592.9],
      space_group_name: "P3<sub>1</sub>21",
      space_group_number: 152,
    },
    health_safety: {
      Hazard_class: 6.1,
      dot_number: 2811,
      rtecs_number: "WY2625000",
    },
  },
  {
    id: 53,
    neighbour: ["Tellurium", "Xenon"],
    description:
      "Although it is a halogen, iodine has a metallic look and sometimes is seen as a metalloid. It is less reactive than the other halogrns. Iodine is quite volatile and easily evaporates to purple gas. It is the element with highest number that is essential to multicellular organisms, human process it in their thyroid gland. Iodide is added to table salt, to prevent iodine deficiench. Tincture of iodine is used to disinfect wounds.",
    general_properties: {
      name: "Iodine",
      atomic_number: 53,
      group: 17,
      period: 5,
      block: "P",
      cas_number: "7553-56-2",
      cid_number: "807",
      symbol: "I",
    },
    particles: {
      electrons: 53,
      protons: 53,
      neutrons: 74,
    },
    overview: {
      latin_name: "Iodum",
      discovery: 1811,
      discoverer: [["Bernard Courtois", "Bernard_Courtois"]],
    },
    atomic_properties: {
      atomic_weight: 126.90447,
      oxidation_states: [-1, 1, 5, 7],
      electron_shell_configuration: "K2 L8 M18 N18 O7",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>5</sup>",
      atomic_radius: 115,
      covalent_radius: 139,
      van_der_walls_radius: 198,
    },
    thermodynamic_properties: {
      boiling_point: "184.3℃",
      melting_point: "113.7℃",
      phase: "Solid",
      fusion_heat: 7.76,
      specific_heat: 429,
      vaporization_heat: 20.9,
    },
    material_properties: {
      color: "Slate Gray",
      molar_volume: "2.569•10<sup>-5</sup>",
      density: 4940,
      thermal_conductivity: 0.449,
      bulk_modulus: 7.7,
    },
    reactivity: {
      valence: 7,
      electronegativity: 2.66,
      ionization_energy: 1008.4,
      electron_affinity: 295.2,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 6.2,
      neutron_mass_absorption: 0.0018,
      quantum_numbers: "<sup>2</sup>P<sub>3/2</sub>",
      isotopes: [
        108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
        122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
        136, 137, 139, 140, 141, 142, 143, 144,
      ],
      stable: [127],
    },
    prevalence: {
      universe: "10<sup>-7</sup>%",
      ocean: "6•10<sup>-6</sup>%",
      human: "0.00002%",
      earth_crust: "0.00005%",
      meteorites: "0.00003%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      electrical_type: "Insulator",
      volume_magnetic_suspectibility: "-2.2•10<sup>-5</sup>",
      mass_magnetic_suspectibility: "-4.5•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-1.14•10<sup>-9</sup>",
      electrical_conductivity: "10<sup>-7</sup>",
      resistivity: "10<sup>7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Iodine",
      youtube: "https://youtu.be/_e194ZAxwko",
    },
    atom_structure: {
      crystal_structure: "Base Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [718.02, 471.02, 981.03],
      space_group_name: "Cmca",
      space_group_number: 64,
    },
    health_safety: {
      Hazard_class: 8,
      dot_number: 1759,
      rtecs_number: "NN1575000",
      nfpa_label: "/I.png",
    },
  },
  {
    id: 54,
    neighbour: ["Iodine", "Cesium"],
    description:
      "Xenon is the most heavy and reactive noble gas(except for the radioactive radon) and is the rarest non-radioactive element on earth. Therefore it is very expensive. It is primarly used in lamps, like in automobile headlights. several xenon compounds are known, some of them are even quite stable. The compound first to be discovered was xenon tetrafluoride, XeF<sub>2</sub>, in 1962.",
    general_properties: {
      name: "Xenon",
      atomic_number: 54,
      group: 18,
      period: 5,
      block: "P",
      cas_number: "7440-63-3",
      cid_number: "23991",
      symbol: "Xe",
    },
    particles: {
      electrons: 54,
      protons: 54,
      neutrons: 77,
    },
    overview: {
      latin_name: "Xenon",
      discovery: 1898,
      discoverer: [
        ["Sir William Ramsay", "William_Ramsay"],
        ["Morris William Travers", "Morris_Travers"],
      ],
    },
    atomic_properties: {
      atomic_weight: 131.293,
      oxidation_states: [0, 2, 4, 6, 8],
      electron_shell_configuration: "K2 L8 M18 N18 O8",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup> 4s<sup>2</sup> 3d<sup>10</sup> 4p<sup>6</sup> 5s<sup>2</sup> 4d<sup>10</sup> 5p<sup>6</sup>",
      gas_atom_multiplicities: 1,
      atomic_radius: 108,
      covalent_radius: 140,
      van_der_walls_radius: 216,
    },
    thermodynamic_properties: {
      boiling_point: "-108℃",
      melting_point: "-111.8℃",
      phase: "Gas",
      fusion_heat: 2.3,
      specific_heat: 158.32,
      vaporization_heat: 12.64,
      adiabatic_index: 1.67,
    },
    material_properties: {
      color: "Colorless",
      molar_volume: "2.2•10<sup>-2</sup>",
      density: 5.9,
      sound_speed: 1090,
      refrective_index: 1.000702,
      thermal_conductivity: 0.00565,
    },
    reactivity: {
      valence: 6,
      electronegativity: 2.6,
      ionization_energy: 1170.4,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 25,
      neutron_mass_absorption: 0.0083,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
        124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        139, 140, 141, 142, 143, 144, 145, 146, 147,
      ],
      stable: [124, 126, 128, 129, 130, 131, 132, 134, 136],
    },
    prevalence: {
      universe: "10<sup>-6</sup>%",
      ocean: "5•10<sup>-10</sup>%",
      earth_crust: "2•10<sup>-9</sup>%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      volume_magnetic_suspectibility: "-2.54•10<sup>-8</sup>",
      mass_magnetic_suspectibility: "-4.3•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-5.65•10<sup>-10</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Xenon",
      youtube: "https://youtu.be/p9CBg8OaTLg",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [620.23, 620.23, 620.23],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 2.2,
      dot_number: 2591,
      rtecs_number: "ZE1280000",
    },
  },
];
