import ElementDetailsProps from "@/types/ElementTypes";

export const RowThreeElem: ElementDetailsProps[] = [
  {
    id: 11,
    neighbour: ["Neon", "Magnesium"],
    description:
      "Sodium is a very abundant element, that can be found in compounds everywhere on earth, most notably in sea water.Sodium Chloride, NaCl, is table salt. Sodium is essential to all animals, but only to a few plants. Elemental sodium is a silvery white,very soft and light metal, which reacts fast and fiercely with many substances (e.g. water), but not with dry air.",
    general_properties: {
      name: "Sodium",
      atomic_number: 11,
      group: 1,
      period: 3,
      block: "S",
      cas_number: "7440-23-5",
      cid_number: "5360545",
      symbol: "Na",
    },
    particles: {
      electrons: 11,
      protons: 11,
      neutrons: 12,
    },
    overview: {
      latin_name: "Natrium",
      discovery: 1807,
      discoverer: [["Humphry Davy", "Humphry_Davy"]],
    },
    atomic_properties: {
      atomic_weight: 22.98976928,
      oxidation_states: [1],
      electron_shell_configuration: "K2 L8 M1",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>1</sup>",
      atomic_radius: 190,
      covalent_radius: 166,
      van_der_walls_radius: 227,
    },
    thermodynamic_properties: {
      boiling_point: "883℃",
      melting_point: "97.72℃",
      phase: "Solid",
      fusion_heat: 2.6,
      specific_heat: 1230,
      vaporization_heat: 97.7,
      thermal_expansion: "7.1•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "2.37•10<sup>-5</sup>",
      density: 968,
      thermal_conductivity: 140,
      sound_speed: 3200,
      young_modulus: 10,
      mohs_hardness: 0.5,
      shear_modulus: 3.3,
      liquid_density: 927,
      brinell_hardness: 0.69,
      bulk_modulus: 6.3,
    },
    reactivity: {
      valence: 1,
      ionization_energy: 495.8,
      electronegativity: 0.93,
      electron_affinity: 52.8,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.53,
      neutron_mass_absorption: 0.0007,
      quantum_numbers: "<sup>2</sup>S<sub>1/2</sub>",
      isotopes: [
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37,
      ],
      stable: [23],
    },
    prevalence: {
      sun: "0.0040%",
      meteorites: "0.55%",
      earth_crust: "2.30%",
      ocean: "1.10%",
      human: "0.14%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "2.1•10<sup>7</sup>",
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      mass_magnetic_suspectibility: "8.5•10<sup>-6</sup>",
      molar_magnetic_suspectibility: "2•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "8.8•10<sup>-9</sup>",
      resistivity: "4.7•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Sodium",
      youtube: "https://youtu.be/WsrdE5g4z1I",
    },
    atom_structure: {
      crystal_structure: "Body-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [429.06, 429.06, 429.06],
      space_group_name: "Im_ 3m",
      space_group_number: 229,
    },
    health_safety: {
      Hazard_class: 4.3,
      dot_number: 1428,
      rtecs_number: "VY0686000",
    },
  },
  {
    id: 12,
    neighbour: ["Sodium", "Aluminium"],
    description:
      "Magnesium is a very abundant, light and reactive element, which is essetial to life. In nature, it is found in many minerals, like in talc. Elemental magnesium burns with a bright, White flame and a temperature of more than 3000 K. This once was used as flashlight for photography and is still used in underwater torches.",
    general_properties: {
      name: "Magnesium",
      atomic_number: 12,
      group: 2,
      period: 3,
      block: "S",
      cas_number: "7439-95-4",
      cid_number: "5462224",
      symbol: "Mg",
    },
    particles: {
      electrons: 12,
      protons: 12,
      neutrons: 12,
    },
    overview: {
      latin_name: "Magnesium",
      discovery: 1755,
      discoverer: [["Joseph Black", "Joseph_Black"]],
    },
    atomic_properties: {
      atomic_weight: 24.305,
      oxidation_states: [2],
      electron_shell_configuration: "K2 L8 M2",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup>",
      atomic_radius: 145,
      covalent_radius: 141,
      van_der_walls_radius: 173,
    },
    thermodynamic_properties: {
      boiling_point: "1090℃",
      melting_point: "650℃",
      phase: "Solid",
      fusion_heat: 8.7,
      specific_heat: 1020,
      vaporization_heat: 128,
      thermal_expansion: "2.5•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "1.398•10<sup>-5</sup>",
      density: 1738,
      thermal_conductivity: 160,
      sound_speed: 4602,
      young_modulus: 45,
      mohs_hardness: 2.5,
      shear_modulus: 17,
      liquid_density: 1584,
      brinell_hardness: 260,
      bulk_modulus: 45,
      poisson_ratio: 0.29,
    },
    reactivity: {
      valence: 2,
      ionization_energy: 737.7,
      electronegativity: 1.31,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.063,
      neutron_mass_absorption: 0.0001,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40,
      ],
      stable: [24, 25, 26],
    },
    prevalence: {
      universe: "0.06%",
      sun: "0.07%",
      meteorites: "12.00%",
      earth_crust: "2.90%",
      ocean: "0.13%",
      human: "0.03%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "2.3•10<sup>7</sup>",
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      mass_magnetic_suspectibility: "6.9•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "1.68•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "1.2•10<sup>-5</sup>",
      resistivity: "4.4•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Magnesium",
      youtube: "https://youtu.be/FKkWdizutxI",
    },
    atom_structure: {
      crystal_structure: "Simple Hexagonal",
      lattice_angle: [90, 90, 120],
      lattice_constant: [320.94, 320.94, 521.08],
      space_group_name: "P6<sub>3</sub>/mmc",
      space_group_number: 194,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 2950,
    },
  },
  {
    id: 13,
    neighbour: ["Magnesium", "Silicon"],
    description:
      "Aluminium is very abundant and is used in pure form for a lot of different components. It is light,soft and malleable,which makes it a material ideal to work with. At very high temparature it can burn and emit a lot of energy. So the production of aluminium from its compounds in earth's minerals like bauxite takes a lot of energy, much more than recycling used aluminium. The latter is more environmentally friendly and also cheaper.",
    general_properties: {
      name: "Aluminium",
      atomic_number: 13,
      group: 13,
      period: 3,
      block: "P",
      cas_number: "7429-90-5",
      cid_number: "5359268",
      symbol: "Al",
    },
    particles: {
      electrons: 13,
      protons: 13,
      neutrons: 14,
    },
    overview: {
      latin_name: "Aluminium",
      discovery: 1825,
      discoverer: [["Hans Christian Ørsted", "Hans_Christian_Ørsted"]],
    },
    atomic_properties: {
      atomic_weight: 26.9815385,
      oxidation_states: [3],
      electron_shell_configuration: "K2 L8 M3",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>1</sup>",
      atomic_radius: 118,
      covalent_radius: 121,
    },
    thermodynamic_properties: {
      boiling_point: "2519℃",
      melting_point: "660.32℃",
      phase: "Solid",
      fusion_heat: 10.7,
      specific_heat: 904,
      vaporization_heat: 293,
      thermal_expansion: "2.31•10<sup>-5</sup>",
    },
    material_properties: {
      color: "Silver",
      molar_volume: "10<sup>-5</sup>",
      density: 2700,
      thermal_conductivity: 235,
      sound_speed: 5100,
      young_modulus: 70,
      mohs_hardness: 2.75,
      shear_modulus: 26,
      liquid_density: 2375,
      brinell_hardness: 245,
      bulk_modulus: 76,
      poisson_ratio: 0.35,
      vickers_hardness: 167,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 577.5,
      electronegativity: 1.61,
      electron_affinity: 42.5,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.233,
      neutron_mass_absorption: 0.03,
      quantum_numbers: "<sup>2</sup>P<sub>1/2</sub>",
      isotopes: [
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42,
      ],
      stable: [27],
    },
    prevalence: {
      universe: "0.01%",
      sun: "0.01%",
      meteorites: "0.90%",
      earth_crust: "8.10%",
      ocean: "5•10<sup>-7</sup>%",
      human: "0.00009%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "3.8•10<sup>7</sup>",
      magnetic_type: "Paramagnetic",
      electrical_type: "Conductor",
      mass_magnetic_suspectibility: "7.8•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "2.1•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "2.11•10<sup>-5</sup>",
      resistivity: "2.6•10<sup>-8</sup>",
      superconducting_point: 1.175,
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Aluminium",
      youtube: "https://youtu.be/nqicpx0adY4",
    },
    health_safety: {
      Hazard_class: 4.3,
      dot_number: 1396,
      rtecs_number: "BD0330000",
      nfpa_label: "/Al.png",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Hexagonal",
      lattice_angle: [90, 90, 90],
      lattice_constant: [404.95, 404.95, 404.95],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
  },
  {
    id: 14,
    neighbour: ["Aluminium", "Phosphorus"],
    description:
      "The metalloid silicon is a very abundant element Much of the earth crust made out of silicates and silica(SiO<sub>2</sub>). The latter is a chief ingredient of quartz and sand is used as raw material for glass since ages. Elemental silicon is an important industrial material,where it is used in huge amounts for semiconductors,computer chips,in electronics, for solar energy and photovoltaics.",
    general_properties: {
      name: "Silicon",
      atomic_number: 14,
      group: 14,
      period: 3,
      block: "P",
      cas_number: "7440-21-3",
      cid_number: "5461123",
      symbol: "Si",
      allotropes: [
        [
          "Amorphous Silicon",
          "https://en.wikipedia.org/wiki/Amorphous_silicon",
        ],
        [
          "Crystalline Silicon",
          "https://en.wikipedia.org/wiki/Crystalline_silicon",
        ],
        ["Silicene", "https://en.wikipedia.org/wiki/Silicene"],
      ],
    },
    particles: {
      electrons: 14,
      protons: 14,
      neutrons: 14,
    },
    overview: {
      latin_name: "Silicum",
      discovery: 1824,
      discoverer: [["Jöns Jacob Berzelius", "Jöns_Jacob_Berzelius"]],
    },
    atomic_properties: {
      atomic_weight: 28.085,
      oxidation_states: [-4, 2, 4],
      electron_shell_configuration: "K2 L8 M4",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>2</sup>",
      atomic_radius: 111,
      covalent_radius: 111,
      van_der_walls_radius: 210,
    },
    thermodynamic_properties: {
      boiling_point: "2900℃",
      melting_point: "1414℃",
      phase: "Solid",
      fusion_heat: 50.2,
      specific_heat: 710,
      vaporization_heat: 359,
      thermal_expansion: "2.6•10<sup>-6</sup>",
    },
    material_properties: {
      color: "Gray",
      molar_volume: "1.205•10<sup>-5</sup>",
      density: 2330,
      thermal_conductivity: 150,
      sound_speed: 2200,
      young_modulus: 47,
      mohs_hardness: 6.5,
      liquid_density: 2570,
      bulk_modulus: 100,
      vickers_hardness: 9630,
    },
    reactivity: {
      valence: 4,
      ionization_energy: 786.5,
      electronegativity: 1.9,
      electron_affinity: 133.6,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.166,
      neutron_mass_absorption: 0.0002,
      quantum_numbers: "<sup>3</sup>P<sub>0</sub>",
      isotopes: [
        22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44,
      ],
      stable: [28, 29, 30],
    },
    prevalence: {
      universe: "0.07%",
      sun: "0.09%",
      meteorites: "14.00%",
      earth_crust: "27.00%",
      ocean: "0.000100%",
      human: "0.03%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "10<sup>3</sup>",
      magnetic_type: "Diamagnetic",
      electrical_type: "Semiconductor",
      mass_magnetic_suspectibility: "-1.6•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-4.49•10<sup>-11</sup>",
      volume_magnetic_suspectibility: "-3.73•10<sup>-6</sup>",
      resistivity: "10<sup>-3</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Silicon",
      youtube: "https://youtu.be/akvr9utNCVs",
    },
    atom_structure: {
      crystal_structure: "Tetrahedral Packing",
      lattice_angle: [90, 90, 90],
      lattice_constant: [543.09, 543.09, 543.09],
      space_group_name: "Fd_ 3m",
      space_group_number: 227,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 1346,
      rtecs_number: "VW0400000",
    },
  },
  {
    id: 15,
    neighbour: ["Silicon", "Sulphur"],
    description:
      "Phosphorus is a very common element, which is found in every life form, notably as the complex molecule adenosine Triphosphate(ATP), which supplies the cells with energy. As an element it has four different allotropes, white,red,black and purple. The white phosphorus is infamous for its extreme toxicity and dangerousness, it sponteneously burns in air. The other allotropes are more or less harmless. Phosphates are main ingredients of fertilizers and as such are ofter a big ecological problem for waterbodies.",
    general_properties: {
      name: "Phosphorus",
      atomic_number: 15,
      group: 15,
      period: 3,
      block: "P",
      cas_number: "7423-14-0",
      cid_number: "5462309",
      symbol: "P",
      allotropes: [
        [
          "White Phosphorus",
          "https://www.who.int/news-room/fact-sheets/detail/white-phosphorus",
        ],
        ["Red Phosphorus", "https://en.wikipedia.org/wiki/Phosphorus"],
        [
          "Scarlet Phosphorus",
          "https://en.wikipedia.org/wiki/Allotropes_of_phosphorus",
        ],
        ["Violet Phosphorus", "https://en.wikipedia.org/wiki/Phosphorus"],
        [
          "Diphosphorus",
          "https://en.wikipedia.org/wiki/Allotropes_of_phosphorus",
        ],
        [
          "Black Phosphorus",
          "https://en.wikipedia.org/wiki/Allotropes_of_phosphorus",
        ],
      ],
    },
    particles: {
      electrons: 15,
      protons: 15,
      neutrons: 16,
    },
    overview: {
      latin_name: "Phosphorus",
      discovery: 1669,
      discoverer: [["Hennig Brandt", "Hennig_Brandt"]],
    },
    atomic_properties: {
      atomic_weight: 30.973761998,
      oxidation_states: [-3, 3, 4, 5],
      electron_shell_configuration: "K2 L8 M5",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>3</sup>",
      atomic_radius: 98,
      covalent_radius: 107,
      van_der_walls_radius: 180,
    },
    thermodynamic_properties: {
      boiling_point: "280.5℃",
      melting_point: "44.2℃",
      phase: "Solid",
      fusion_heat: 0.64,
      specific_heat: 769.7,
      vaporization_heat: 12.4,
    },
    material_properties: {
      color: "Colorless",
      molar_volume: "10<sup>-5</sup>",
      density: 1823,
      thermal_conductivity: 0.236,
      bulk_modulus: 11,
      refrective_index: 1.001212,
    },
    reactivity: {
      valence: 5,
      ionization_energy: 1011.8,
      electronegativity: 2.19,
      electron_affinity: 72,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.18,
      neutron_mass_absorption: 0.0002,
      quantum_numbers: "<sup>4</sup>S<sub>3/2</sub>",
      isotopes: [
        24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46,
      ],
      stable: [31],
    },
    prevalence: {
      universe: "0.01%",
      sun: "0.01%",
      meteorites: "0.90%",
      earth_crust: "8.10%",
      ocean: "5•10<sup>-7</sup>%",
      human: "0.00009%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "10<sup>7</sup>",
      magnetic_type: "Diamagnetic",
      electrical_type: "Conductor",
      mass_magnetic_suspectibility: "-1.3•10<sup>-8</sup>",
      molar_magnetic_suspectibility: "-3.5•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "-2.06•10<sup>-5</sup>",
      resistivity: "10<sup>-7</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Phosphorus",
      youtube: "https://youtu.be/NdOyFPv7TkY",
    },
    atom_structure: {
      crystal_structure: "Simple Triclinic",
      lattice_angle: [1.25384, 1.57725, 1.24896],
      lattice_constant: [1145, 550.3, 1126.1],
      space_group_name: "P-1",
      space_group_number: 2,
    },
    health_safety: {
      Hazard_class: 4.1,
      dot_number: 1338,
      rtecs_number: "TH3495000",
    },
  },
  {
    id: 16,
    neighbour: ["Phosphorus", "Chlorine"],
    description:
      "Sulfur is an element which is known since ancient times. It sometimes naturally occurs in its elemental form and such often is emitted in volcanic eruptions. Sulphur has a complex chemistry and is essential to life. On the other hand, it has some very toxic and environmetally hazardous compounds. Notable here are hydrogen sulfide, which gives rotten eggs smell and sulphur dioxide and trioxide, which when dissolved in water, gives sulfurous acid and sulfuric acid.",
    general_properties: {
      name: "Sulphur",
      atomic_number: 16,
      group: 16,
      period: 3,
      block: "P",
      cas_number: "7704-34-9",
      cid_number: "5362487",
      symbol: "S",
      allotropes: [
        [
          "Cyclo-Pentasulfur",
          "https://en.wikipedia.org/wiki/Allotropes_of_sulfur",
        ],
        [
          "Cyclo-Hexasulfur",
          "https://en.wikipedia.org/wiki/Allotropes_of_sulfur",
        ],
        [
          "Cyclo-Heptasulfur",
          "https://en.wikipedia.org/wiki/Allotropes_of_sulfur",
        ],
        [
          "Cyclo-Octasulfur",
          "https://en.wikipedia.org/wiki/Allotropes_of_sulfur",
        ],
      ],
    },
    particles: {
      electrons: 16,
      protons: 16,
      neutrons: 16,
    },
    overview: {
      latin_name: "Sulphur",
      discovery: -500,
      discoverer: [["Prehistoric", "Prehistoric"]],
    },
    atomic_properties: {
      atomic_weight: 32.06,
      oxidation_states: [-2, 2, 4, 6],
      electron_shell_configuration: "K2 L8 M6",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>4</sup>",
      atomic_radius: 88,
      covalent_radius: 105,
      van_der_walls_radius: 180,
    },
    thermodynamic_properties: {
      boiling_point: "444.72℃",
      melting_point: "115.21℃",
      phase: "Solid",
      fusion_heat: 1.73,
      specific_heat: 705,
      vaporization_heat: 9.8,
    },
    material_properties: {
      color: "Yellow / Red",
      molar_volume: "1.636•10<sup>-5</sup>",
      density: 1960,
      thermal_conductivity: 0.205,
      mohs_hardness: 2,
      liquid_density: 1819,
      bulk_modulus: 7.7,
      refrective_index: 1.001111,
    },
    reactivity: {
      valence: 6,
      ionization_energy: 999.6,
      electronegativity: 2.58,
      electron_affinity: 200,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.52,
      neutron_mass_absorption: 0.00055,
      quantum_numbers: "<sup>3</sup>P<sub>2</sub>",
      isotopes: [
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49,
      ],
      stable: [32, 33, 34, 36],
    },
    prevalence: {
      universe: "0.05%",
      sun: "0.04%",
      meteorites: "4.00%",
      earth_crust: "0.04%",
      ocean: "0.09%",
      human: "0.20%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "10<sup>-15</sup>",
      magnetic_type: "Diamagnetic",
      electrical_type: "Insulator",
      mass_magnetic_suspectibility: "-6.2•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-1.99•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "-1.22•10<sup>-5</sup>",
      resistivity: "10<sup>15</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Sulphur",
      youtube: "https://youtu.be/mddfu3TXaRw",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Orthorhombic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [1043.7, 1284.5, 2436.9],
      space_group_name: "Fddd",
      space_group_number: 70,
    },
    health_safety: {
      rtecs_number: "WS4250000",
    },
  },
  {
    id: 17,
    neighbour: ["Sulphur", "Argon"],
    description:
      "Chlorine, which at normal conditions is a yellow-green Cl<sub>2</sub> gas, is a very caustic substance. Elemental chlorine corrodes nearly every metal and is toxic for every creature. In nature, it always occurs in compounds, the most famous of those is sodium chloride, NaCl, which is table salt. Chloride is a vitalpart of the body. The compound of Hydrogen and Chlorine, HCl, dissolved in water, gives hydrochloric acid. Chlorine also is part of the very common plastic PVC.",
    general_properties: {
      name: "Chlorine",
      atomic_number: 17,
      group: 17,
      period: 3,
      block: "P",
      cas_number: "7782-50-5",
      cid_number: "24526",
      symbol: "Cl",
    },
    particles: {
      electrons: 17,
      protons: 17,
      neutrons: 18,
    },
    overview: {
      latin_name: "Chlorum",
      discovery: 1774,
      discoverer: [["Carl Wilhelm Scheele", "Carl_Wilhelm_Scheele"]],
    },
    atomic_properties: {
      atomic_weight: 35.45,
      oxidation_states: [-1, 1, 3, 5, 7],
      electron_shell_configuration: "K2 L8 M7",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>5</sup>",
      gas_atom_multiplicities: 2,
      atomic_radius: 79,
      covalent_radius: 102,
      van_der_walls_radius: 175,
    },
    thermodynamic_properties: {
      boiling_point: "-34.04℃",
      melting_point: "-101.5℃",
      phase: "Gas",
      fusion_heat: 3.2,
      specific_heat: 478.2,
      vaporization_heat: 10.2,
      adiabatic_index: 7 / 5,
    },
    material_properties: {
      color: "Yellow",
      molar_volume: "1.103•10<sup>-2</sup>",
      density: 3.214,
      thermal_conductivity: 0.0089,
      sound_speed: 206,
      bulk_modulus: 1.1,
      refrective_index: 1.000773,
    },
    reactivity: {
      valence: 3,
      ionization_energy: 1251.2,
      electronegativity: 3.16,
      electron_affinity: 349,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 35.3,
      neutron_mass_absorption: 0.033,
      quantum_numbers: "<sup>2</sup>P<sub>3/2</sub>",
      isotopes: [
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51,
      ],
      stable: [35, 37],
    },
    prevalence: {
      universe: "0.00010%",
      sun: "0.0008%",
      meteorites: "0.04%",
      earth_crust: "0.02%",
      ocean: "2.00%",
      human: "0.12%",
    },
    electromagnetic_properties: {
      electrical_conductivity: "10<sup>-2</sup>",
      magnetic_type: "Diamagnetic",
      electrical_type: "Insulator",
      mass_magnetic_suspectibility: "-7.2•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-5.11•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "-2.31•10<sup>-8</sup>",
      resistivity: "10<sup>2</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Chlorine",
      youtube: "https://youtu.be/BXCfBl4rmh0",
    },
    atom_structure: {
      crystal_structure: "Base Orthorombhic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [622.35, 445.61, 817.85],
      space_group_name: "Cmca",
      space_group_number: 64,
    },
    health_safety: {
      rtecs_number: "FO2100000",
    },
  },
  {
    id: 18,
    neighbour: ["Chlorine", "Potassium"],
    description:
      "Argon is produced industrially by the fractional distillation of liquid air. Argon is mostly usec as an inert shielding gas in welding and higher high temparature industrial processes where ordinarily unreactive substance become reactive; for example, an argon atmosphere is used in graphite electric furnaces to prevent the graphite from burning",
    general_properties: {
      name: "Argon",
      atomic_number: 18,
      group: 18,
      period: 3,
      block: "P",
      cas_number: "7440-37-1",
      cid_number: "23968",
      symbol: "Ar",
    },
    particles: {
      electrons: 18,
      protons: 18,
      neutrons: 22,
    },
    overview: {
      latin_name: "Argon",
      discovery: 1894,
      discoverer: [
        ["Lord Rayleigh", "Lord_Rayleigh"],
        ["Sir William Ramsay", "William_Ramsay"],
      ],
    },
    atomic_properties: {
      atomic_weight: 39.948,
      oxidation_states: [0],
      electron_shell_configuration: "K2 L8 M8",
      electron_configuration:
        "1s<sup>2</sup> 2s<sup>1</sup> 2p<sup>6</sup> 3s<sup>2</sup> 3p<sup>6</sup>",
      gas_atom_multiplicities: 1,
      atomic_radius: 71,
      covalent_radius: 106,
      van_der_walls_radius: 188,
    },
    thermodynamic_properties: {
      boiling_point: "-185.8℃",
      melting_point: "-189.3℃",
      phase: "Gas",
      fusion_heat: 1.18,
      specific_heat: 520.33,
      vaporization_heat: 6.5,
      adiabatic_index: 1.67,
    },
    material_properties: {
      color: "Colorless",
      molar_volume: "2.239•10<sup>-2</sup>",
      density: 1.784,
      thermal_conductivity: 0.01772,
      sound_speed: 319,
      refrective_index: 1.000281,
    },
    reactivity: {
      valence: 0,
      ionization_energy: 1520.6,
    },
    neuclear_properties: {
      radioactive: "No",
      half_life: "∞",
      lifetime: "∞",
      neutron_cross_section: 0.65,
      neutron_mass_absorption: 0.00059,
      quantum_numbers: "<sup>1</sup>S<sub>0</sub>",
      isotopes: [
        30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53,
      ],
      stable: [36, 38, 40],
    },
    prevalence: {
      universe: "0.02%",
      sun: "0.01%",
      earth_crust: "0.00015%",
      ocean: "0.000045%",
    },
    electromagnetic_properties: {
      magnetic_type: "Diamagnetic",
      mass_magnetic_suspectibility: "-6•10<sup>-9</sup>",
      molar_magnetic_suspectibility: "-2.4•10<sup>-10</sup>",
      volume_magnetic_suspectibility: "-1.07•10<sup>-8</sup>",
    },
    external_links: {
      wikipedia: "https://en.wikipedia.org/wiki/Argon",
      youtube: "https://youtu.be/b3TrEGlpttI",
    },
    atom_structure: {
      crystal_structure: "Face-Centered Cubic",
      lattice_angle: [90, 90, 90],
      lattice_constant: [525.6, 525.6, 525.6],
      space_group_name: "Fm_ 3m",
      space_group_number: 225,
    },
    health_safety: {
      Hazard_class: 2.2,
      dot_number: 1951,
      rtecs_number: "CF2300000",
    },
  },
];
